/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2026-02-13 08:19:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.updown;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.zip.ZipOutputStream;
import java.util.zip.ZipEntry;
import java.net.URLDecoder.*;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.Collections;
import com.nexacro.java.xapi.tx.*;
import com.nexacro.java.xapi.data.*;
import com.oreilly.servlet.*;
import com.oreilly.servlet.MultipartRequest;
import com.oreilly.servlet.multipart.DefaultFileRenamePolicy;
import javax.servlet.ServletException;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public final class fileDownload_005fpostdatatest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


/**
 * HttpServletRequestWrapper를 확장하여 요청 헤더를 추가/변경할 수 있는 래퍼 클래스
 */
public class CustomRequestWrapper extends HttpServletRequestWrapper {
    private final Map<String, String> customHeaders = new HashMap<String, String>();

    public CustomRequestWrapper(HttpServletRequest request) {
        super(request);
    }

    public void setHeader(String name, String value) {
        customHeaders.put(name, value);
    }

    @Override
    public String getHeader(String name) {
        // 커스텀 헤더에 값이 있으면 우선 반환
        String customValue = customHeaders.get(name);
        if (customValue != null) {
            return customValue;
        }
        return super.getHeader(name);
    }

    @Override
    public Enumeration<String> getHeaderNames() {
        // 원래 헤더 이름 + 커스텀 헤더 이름을 합침
        List<String> names = new ArrayList<String>(customHeaders.keySet());
        Enumeration<String> originalNames = super.getHeaderNames();
        while (originalNames.hasMoreElements()) {
            String name = originalNames.nextElement();
            if (!customHeaders.containsKey(name)) {
                names.add(name);
            }
        }
        return Collections.enumeration(names);
    }
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("com.oreilly.servlet");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.nexacro.java.xapi.tx");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.net.URLDecoder");
    _jspx_imports_packages.add("com.nexacro.java.xapi.data");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(19);
    _jspx_imports_classes.add("java.util.zip.ZipOutputStream");
    _jspx_imports_classes.add("java.io.BufferedInputStream");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("java.util.Enumeration");
    _jspx_imports_classes.add("javax.servlet.ServletException");
    _jspx_imports_classes.add("javax.servlet.http.HttpServletResponse");
    _jspx_imports_classes.add("java.io.IOException");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("java.io.FileInputStream");
    _jspx_imports_classes.add("java.io.File");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("javax.servlet.http.HttpServletRequest");
    _jspx_imports_classes.add("com.oreilly.servlet.multipart.DefaultFileRenamePolicy");
    _jspx_imports_classes.add("javax.servlet.ServletOutputStream");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.zip.ZipEntry");
    _jspx_imports_classes.add("java.util.Collections");
    _jspx_imports_classes.add("com.oreilly.servlet.MultipartRequest");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	request.setCharacterEncoding("UTF-8");
	String userAgent = request.getHeader("User-Agent");
	System.out.println("User-Agent: " + userAgent);

	// CustomRequestWrapper로 헤더 값 변경
	CustomRequestWrapper wrapped = new CustomRequestWrapper(request);
	wrapped.setHeader("jsp_download_header", "jsp_download_header_value");

	// 변경된 헤더 값 확인
	String myHeaderValue = wrapped.getHeader("jsp_download_header");

	System.out.println("jsp_download_header 값: " + myHeaderValue);
	// 변경된 헤더 값을 HTTP 응답 헤더에 반영 (패킷에서 확인 가능)
	response.setHeader("jsp_download_header", myHeaderValue);


	// wrapped 객체의 헤더 목록 출력	
	java.util.Enumeration<String> headerNames = wrapped.getHeaderNames();

    System.out.println("====== [HTTP Header List Start] ======");

    // 헤더가 없을 때까지 반복합니다.
    while (headerNames.hasMoreElements()) {
        String key = headerNames.nextElement();      // 헤더 이름 (ID)
        String value = wrapped.getHeader(key);       // wrapped 객체에서 헤더 값 읽기
        
        System.out.println(key + " : " + value);
    }
    
	String contextRealPath = request.getSession().getServletContext().getRealPath("/");
	
	String getFolderName = request.getParameter("filefolder");
	String getName = request.getParameter("filename");

	//String filename = new String(getName.getBytes("iso8859-1"), "utf-8");
	String filename = java.net.URLDecoder.decode(getName, "utf-8");
	String folderName = java.net.URLDecoder.decode(getFolderName, "utf-8");

	String filePath = contextRealPath + folderName + File.separator;
	if (filename.length() <= 0)
	{
		ServletOutputStream out_stream	= null;
		BufferedInputStream in_stream	= null;
		ZipOutputStream		zout_stream	= null;
		try
		{
			response.setContentType("application/octet;charset=utf-8");
			response.setHeader("Content-Disposition", "attachment; filename = \"" + folderName + ".zip" + "\"");
			
			out.clear();
			out = pageContext.pushBody();

			out_stream = response.getOutputStream();
			zout_stream = new ZipOutputStream(out_stream);		
			zout_stream.setLevel(8);
			
			String filedown = "";
			String filedownPath = "";

			File rf = new File(filePath); 
			File[] rfiles = rf.listFiles();
			
			if(rfiles != null)
			{
				for(int i=0; i<rfiles.length; i++)
				{
					if(rfiles[i].isFile())
					{
						filedown = rfiles[i].getName();
						filedownPath = filePath + filedown;
						System.out.println("filepath :" + filedownPath);

						File fis = new File(filedownPath);
						in_stream = new BufferedInputStream(new FileInputStream(fis));
						
						ZipEntry zentry = new ZipEntry(filedown);
						zentry.setTime(fis.lastModified());
						zout_stream.putNextEntry(zentry);
						
						byte[] buffer = new byte[1024];
						int n = 0;
						while ((n = in_stream.read(buffer, 0, 1024)) != -1)
						{
							zout_stream.write(buffer, 0, n);
						}
						
						zout_stream.closeEntry();							
					}
				}
			}			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
		finally
		{
			if (zout_stream != null)
			{
				try
				{
					zout_stream.close();
				}
				catch (Exception e)
				{
					e.printStackTrace();
				}
			}
			if (out_stream != null)
			{
				try
				{
					out_stream.close();
				}
				catch (Exception e)
				{
					e.printStackTrace();
				}
			}
			if (in_stream != null)
			{
				try
				{
					in_stream.close();
				}
				catch (Exception e)
				{
					e.printStackTrace();
				}
			}
		}	
	}
	else
	{
		filePath = contextRealPath + folderName + File.separator + filename;
	
		System.out.println("filepath :" + filePath);
	
		byte[] buffer = new byte[1024];

		ServletOutputStream out_stream	= null;
		BufferedInputStream in_stream	= null;

		File fis = new File(filePath);

		if(fis.exists())
		{
			System.out.println("filepath : fis.exists()-->" + filename);

			try
			{
				response.setContentType("application/octet;charset=utf-8");
				//response.setHeader("Content-Disposition", "attachment; filename = \"" + filename + "\"");
				response.setHeader("Content-Disposition", "attachment; filename = \"" + new String(getName.getBytes("utf-8"), "ISO8859_1") + "\"");
				response.setHeader("Content-Transper-Encoding", "binary");
				response.setHeader("Content-Length", "" + String.valueOf(fis.length()));
				response.setHeader("Pargma", "no-cache");
				response.setHeader("Expires", "-1");

				out.clear();
				out = pageContext.pushBody();

				out_stream = response.getOutputStream();
				in_stream = new BufferedInputStream(new FileInputStream(fis));

				int n = 0;
				while ((n = in_stream.read(buffer, 0, 1024)) != -1)
				{
					out_stream.write(buffer, 0, n);
				}

				System.out.println("fileDownload filename==>"+filename + ", OK!!! ");
				out_stream.flush();
			}
			catch (Exception e)
			{
				e.printStackTrace();
			}
			finally
			{
				if (in_stream != null)
				{
					try
					{
						in_stream.close();
					}
					catch (Exception e)
					{
						e.printStackTrace();
					}
				}
				if (out_stream != null)
				{
					try
					{
						out_stream.close();
					}
					catch (Exception e)
					{
						e.printStackTrace();
					}
				}
			}
		}
		else
		{
			System.out.println("fileDownload filename==>"+filename + ", 파일없음.");
			response.sendRedirect("unknownfile");
		}
	}

      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
