/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-09-03 05:07:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.service_005fjsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.nexacro.java.xapi.tx.*;
import com.nexacro.java.xapi.data.*;
import com.nexacro.java.xapi.data.datatype.*;

public final class B_005fTR_005fXML2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.nexacro.java.xapi.tx");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.nexacro.java.xapi.data");
    _jspx_imports_packages.add("com.nexacro.java.xapi.data.datatype");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    String strCharset = "utf-8";

    /*********************************************************
     * request로 들어온 내용을 parsing하여
     * input variable list, input dataset list에 저장한다.
     * (Nexacro N 에서 보내온 데이터를 parsing한다.)
     *********************************************************/     
    PlatformRequest platformRequest = new PlatformRequest(request.getInputStream(), PlatformType.CONTENT_TYPE_XML);
    platformRequest.receiveData();
    PlatformData inPD = platformRequest.getData();

    VariableList    inVariableList  = inPD.getVariableList();
    DataSetList     inDataSetList   = inPD.getDataSetList();
		
		String strCount = "";
		int nCount = 0;
		
		//Argument 생략 케이스 처리
		if(inVariableList.getString("nCount") != null)
			strCount = inVariableList.getString("nCount");     		
		else
			strCount = "1";
			     			
    nCount = Integer.parseInt(strCount);
    
    DataSet ds = inDataSetList.get("input");
    DataSet ds2 = inDataSetList.get("input2");   	
    DataSet ds3 = inDataSetList.get("input3");   	   	
	
		//System.out.println(ds.saveXml());    

    /*********************************************************
     * response로 보낼 내용을 생성한다.
     * output variable list, output dataset list에 저장한다.
     * (Nexacro N 이 받을 수 있는 데이터 형태로 가공)
     *********************************************************/ 
     out.clear();
     out=pageContext.pushBody();    
     
    PlatformResponse platformResponse = new PlatformResponse(response.getOutputStream(), PlatformType.CONTENT_TYPE_XML, strCharset);   
    PlatformData outPD = platformRequest.getData();
    VariableList    outVariableList  = new VariableList();
    DataSetList     outDataSetList   = new DataSetList();

    try {
    
/////////////////////////////////////////////////////////////////////////
       //output 데이터셋 생성
       DataSet outDataSet  = new DataSet("output");        
       // Output Dataset 컬럼 정의
     for(int i = 0; i < 600; i++){       
				outDataSet.addColumn("Column0"+i,   DataTypes.STRING, 256); 		
    }
		   int newRow = 0;
		 //  for(int i = 0; i < 3; i++)
		//   {

		//		for(int j = 0; j < 20; j++)		
		//			outDataSet.set(newRow, "Column" + j, "Row" + i);					
	  // 	}		
	 			newRow = outDataSet.newRow();
    
		    // Output Dataset 을 Output Dataset List 에 담는다.      									
        outDataSetList.add(outDataSet);
//////////////////////////////////////////////////////////////////////////
       
/////////////////////////////////////////////////////////////////////////
       //output2 데이터셋 생성 
       DataSet outDataSet2  = new DataSet("output2");        
       // Output Dataset 컬럼 정의
      for(int i = 0; i < 20; i++)       
				outDataSet2.addColumn("Column" + i,   DataTypes.STRING, 256); 		
	   
	   
		   newRow = 0;
		   for(int i = 0; i < nCount; i++)
		   {
				newRow = outDataSet2.newRow();	 		
				for(int j = 0; j < 20; j++)
					outDataSet2.set(newRow, "Column" + j, "Row" + i);					
	   	}		
	 		
		    // Output Dataset 을 Output Dataset List 에 담는다.      									
        outDataSetList.add(outDataSet2);
/////////////////////////////////////////////////////////////////////////
       
///////////////////////////////////////////////////////////////////////// 
       //output3 데이터셋 생성 
       DataSet outDataSet3  = new DataSet("output3");        
       // Output Dataset 컬럼 정의
      for(int i = 0; i < 20; i++)       
				outDataSet3.addColumn("Column" + i,   DataTypes.STRING, 256); 		
	   
	   
		   newRow = 0;
		   for(int i = 0; i < nCount; i++)
		   {
				newRow = outDataSet3.newRow();	 		
				for(int j = 0; j < 20; j++)
					outDataSet3.set(newRow, "Column" + j, "Row" + i);					
	   	}		
	 		
		    // Output Dataset 을 Output Dataset List 에 담는다.      									
        outDataSetList.add(outDataSet3);       
///////////////////////////////////////////////////////////////////////// 
        
/////////////////////////////////////////////////////////////////////////        
        // 콜백 함수에 뿌려줄 코드와 메시지.		
        outVariableList.add("ErrorCode", -1);
        outVariableList.add("ErrorMsg",  "조회성공 -1 return");

    } catch(Exception e) {

        // Output Vairable 을 세팅한다.
        outVariableList.add("ErrorCode",  -1);
        outVariableList.add("ErrorMsg", "실패");
        e.printStackTrace();
    }
/////////////////////////////////////////////////////////////////////////
 
	outPD.setDataSetList(outDataSetList);
	outPD.setVariableList(outVariableList);
	platformResponse.setData(outPD);
	platformResponse.sendData();

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
