/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-08-12 05:03:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.service_005fjsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.apache.commons.fileupload2.core.DiskFileItemFactory;
import org.apache.commons.fileupload2.jakarta.JakartaServletFileUpload;
import org.apache.commons.fileupload2.core.FileItem;
import org.apache.commons.io.FilenameUtils;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import org.apache.commons.fileupload2.core.FileUploadException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.ServletException;
import java.io.IOException;
import java.io.File;
import java.util.List;
import java.util.Iterator;
import com.nexacro.java.xapi.data.PlatformData;
import com.nexacro.java.xapi.data.ColumnHeader;
import com.nexacro.java.xapi.data.DataTypes;
import com.nexacro.java.xapi.data.DataSet;
import com.nexacro.java.xapi.data.DataSetList;
import com.nexacro.java.xapi.data.VariableList;
import com.nexacro.java.xapi.tx.PlatformException;
import com.nexacro.java.xapi.tx.PlatformRequest;
import com.nexacro.java.xapi.tx.HttpPlatformRequest;
import com.nexacro.java.xapi.tx.HttpPlatformResponse;
import com.nexacro.java.xapi.tx.PlatformType;

public final class RP_005f103285_005fuploadFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(26);
    _jspx_imports_classes.add("com.nexacro.java.xapi.tx.PlatformType");
    _jspx_imports_classes.add("jakarta.servlet.http.HttpServletRequest");
    _jspx_imports_classes.add("com.nexacro.java.xapi.tx.HttpPlatformRequest");
    _jspx_imports_classes.add("jakarta.servlet.ServletException");
    _jspx_imports_classes.add("com.nexacro.java.xapi.tx.PlatformException");
    _jspx_imports_classes.add("com.nexacro.java.xapi.data.ColumnHeader");
    _jspx_imports_classes.add("com.nexacro.java.xapi.data.PlatformData");
    _jspx_imports_classes.add("com.nexacro.java.xapi.tx.PlatformRequest");
    _jspx_imports_classes.add("com.nexacro.java.xapi.data.VariableList");
    _jspx_imports_classes.add("org.apache.commons.fileupload2.core.DiskFileItemFactory");
    _jspx_imports_classes.add("java.nio.file.Path");
    _jspx_imports_classes.add("com.nexacro.java.xapi.data.DataSet");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("org.apache.commons.fileupload2.core.FileUploadException");
    _jspx_imports_classes.add("java.io.IOException");
    _jspx_imports_classes.add("org.apache.commons.fileupload2.jakarta.JakartaServletFileUpload");
    _jspx_imports_classes.add("jakarta.servlet.http.HttpServlet");
    _jspx_imports_classes.add("java.nio.charset.StandardCharsets");
    _jspx_imports_classes.add("java.io.File");
    _jspx_imports_classes.add("com.nexacro.java.xapi.tx.HttpPlatformResponse");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.nexacro.java.xapi.data.DataTypes");
    _jspx_imports_classes.add("jakarta.servlet.http.HttpServletResponse");
    _jspx_imports_classes.add("org.apache.commons.fileupload2.core.FileItem");
    _jspx_imports_classes.add("org.apache.commons.io.FilenameUtils");
    _jspx_imports_classes.add("com.nexacro.java.xapi.data.DataSetList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


/*
Copyright [2013] [EcoSystem of TOBESOFT]

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/ 

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	//Check that we have a file upload request
	boolean isMultipart = JakartaServletFileUpload.isMultipartContent(request);
	
	PlatformData resData = new PlatformData();
	VariableList resVarList = resData.getVariableList();
	
	if (isMultipart)
	{
		String contextRealPath = request.getSession().getServletContext().getRealPath("/");
		String path = request.getParameter("PATH");
		String savePath = contextRealPath + path;
		//String returnMsg = "";
	
		// Create a factory for disk-based file items
		//DiskFileItemFactory factory = new DiskFileItemFactory();
		DiskFileItemFactory factory = DiskFileItemFactory.builder()
			    .setBufferSize(4096)  // setSizeThreshold 대신 setBufferSize 사용
			    .setCharset(StandardCharsets.UTF_8)
			    .setPath(Path.of(System.getProperty("java.io.tmpdir")))
			    .get();
				

		// Sets the size threshold beyond which files are written directly to disk
		//factory.setSizeThreshold(4096);
		
		// Create a new file upload handler
		JakartaServletFileUpload upload = new JakartaServletFileUpload(factory);
		
		// Specifies the character encoding to be used when reading the headers of individual part
		//upload.setHeaderEncoding("utf-8");
	
		// Set overall request size constraint
		upload.setSizeMax(500 * 1024 * 1024); 
		
		// Sets the maximum allowed size of a single uploaded file
		upload.setFileSizeMax(500 * 1024 * 1024);
		
		try 
		{
			File filePath = new File(savePath); 
			if (!filePath.exists()) 
			{
				filePath.mkdirs();
			}
	
			// Sets the directory used to temporarily store files that are larger than the configured size threshold
			//factory.setRepository(new File(System.getProperty("java.io.tmpdir")));
			//System.out.println("---> getRepository:"+factory.getRepository());
	
			// Parse the request
			List items = upload.parseRequest(request);
			Iterator iter = items.iterator();
			
			
			DataSet ds = new DataSet("ds_output");
			ds.addColumn(new ColumnHeader("filename", DataTypes.STRING));
			ds.addColumn(new ColumnHeader("filesize", DataTypes.INT));
			
			
			// Parse the request
			while (iter.hasNext()) 
			{
				FileItem item = (FileItem) iter.next();
				
				// Process a file upload
				if (!item.isFormField()) 
				{
					// filename on the client
					String fieldName = item.getFieldName();
					String fileName = item.getName();
					long fileSize = item.getSize();
					//System.out.println(">>>>> fileName:"+fileName + "   fieldName:" + fieldName + "   fileSize:" + fileSize);
					
					if (fileName == null || fileName.equals(""))
					{
						continue;
					}
					else
					{
						fileName = FilenameUtils.getName(fileName);
				    	//System.out.println("--->fileName:"+fileName);
				        
						//File uploadedFile = new File(filePath + File.separator + fileName);
						File uploadedFile = new File(filePath + File.separator, fileName);
						Path uploadPath = Path.of(filePath + File.separator, fileName);

						//System.out.println(uploadedFile.getAbsolutePath());
						
						item.write(uploadPath);
						item.delete(); 
						
						int row = ds.newRow();
						ds.set(row, "filename", fileName);
						ds.set(row, "filesize", fileSize);
						
						//if (returnMsg.length() > 0) 
						//{
						//	returnMsg += "\r\n";
						//}
						//returnMsg += fileName;
					}
				}
			}
			
			resData.addDataSet(ds);
			resVarList.add("ErrorCode", 0);
			resVarList.add("ErrorMsg", "SUCC");
			//resVarList.add("ErrorMsg", returnMsg);
		} 
		catch (FileUploadException e) 
		{
			resVarList.add("ErrorCode", -1);
			//resVarList.add("ErrorMsg", returnMsg + " " + e);
			resVarList.add("ErrorMsg", e);
			e.printStackTrace();
		} 
		catch (Exception e) 
		{
			resVarList.add("ErrorCode", -1);
			//resVarList.add("ErrorMsg", returnMsg + " " + e);
			resVarList.add("ErrorMsg", e);
			e.printStackTrace();
		}
	}
	else
	{
		resVarList.add("ErrorCode", -1);
		resVarList.add("ErrorMsg", "Invalid Request");
	}
	
	HttpPlatformResponse res = new HttpPlatformResponse(response);
	res.setData(resData);
	res.sendData();


      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
