/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-08-29 04:24:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.service_005fjsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.commons.logging.*;
import com.nexacro.xapi.tx.*;
import com.nexacro.xapi.data.*;
import com.nexacro.xapi.data.datatype.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;

public final class RP_005f92501_005fNC_005fNoSQL2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(12);
    _jspx_imports_packages.add("com.nexacro.xapi.tx");
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.nexacro.xapi.data");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("org.apache.commons.logging");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.sql");
    _jspx_imports_packages.add("javax.naming");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.nexacro.xapi.data.datatype");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/xml; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");


out.clearBuffer();

String strCharset = "UTF-8";

//PlatformRequest platformRequest = new PlatformRequest(request.getInputStream(), PlatformType.CONTENT_TYPE_XML, strCharset);
PlatformRequest platformRequest = new PlatformRequest(request.getInputStream());
platformRequest.receiveData();
PlatformData inPD = platformRequest.getData();

VariableList    inVL  = inPD.getVariableList();

PlatformData o_xpData = new PlatformData();
    

int nErrorCode = 0;
String strErrorMsg = "START";

    //System.out.println("5초 대기 시작");
   // Thread.sleep(5000);
    //System.out.println("5초 대기 끝");

try
{

//System.out.println("aaa");
DataSet ds = new DataSet("output");
DataSet ds1 = new DataSet("output1");
DataSet ds2 = new DataSet("output2");

	  
ds.addColumn("Column0",DataTypes.STRING, (short)10);
ds.addColumn("Column1",DataTypes.STRING, (short)10);
ds.addColumn("Column2",DataTypes.STRING, (short)10);

ds1.addColumn("Column0",DataTypes.STRING, (short)10);
ds1.addColumn("Column1",DataTypes.STRING, (short)10);
ds1.addColumn("Column2",DataTypes.STRING, (short)10);

ds2.addColumn("Column0",DataTypes.STRING, (short)10);
ds2.addColumn("Column1",DataTypes.STRING, (short)10);
ds2.addColumn("Column2",DataTypes.STRING, (short)10);


int i,j,k;
 
for (i = 0; i < 10; i++)
{
	int row = ds.newRow();
	
	//System.out.println("row::: "+row);

	//ds.set(row, "col0", "不客气");
	//ds.set(row, "col1", "拜托你");
	//ds.set(row, "col2", "你会说英语吗");

	ds.set(row, "Column0", "가나다라");
	ds.set(row, "Column1", "123\n\r456");
	ds.set(row, "Column2", i + "-test3dd");
}

for (j = 0; j < 10; j++)
{
	int row1 = ds1.newRow();
	
	
}



for (k = 0; k < 10; k++)
{
	int row2 = ds2.newRow();
	
	ds2.set(row2, "Column0", k + "-TEST1dd");
	ds2.set(row2, "Column1", k);
	ds2.set(row2, "Column2", k + "-TEST3dd");
}

o_xpData.addDataSet(ds);
o_xpData.addDataSet(ds1);
o_xpData.addDataSet(ds2);

nErrorCode = -1;
strErrorMsg = "조회성공 -1 return";
} catch (Exception e) {
nErrorCode = -1;
strErrorMsg = e.getMessage();
}


VariableList varList = o_xpData.getVariableList();
		
//Thread.sleep(300000);	
varList.add("ErrorCode", nErrorCode);
varList.add("ErrorMsg", strErrorMsg);


HttpPlatformResponse pRes = new HttpPlatformResponse(response, PlatformType.CONTENT_TYPE_XML, "UTF-8");
pRes.setData(o_xpData);

pRes.sendData();

      out.write('	');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
