/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2026-01-30 01:17:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.service_005fjsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.nexacro.java.xapi.tx.*;
import com.nexacro.java.xapi.data.*;
import com.nexacro.java.xapi.data.datatype.*;

public final class test_005f100_005fJSON_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.nexacro.java.xapi.tx");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.nexacro.java.xapi.data");
    _jspx_imports_packages.add("com.nexacro.java.xapi.data.datatype");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

       String strCharset = "utf-8";

    /*********************************************************
     * request로 들어온 내용을 parsing하여
     * input variable list, input dataset list에 저장한다.
     * (MiPlatform 에서 보내온 데이터를 parsing한다.)
     *********************************************************/
    HttpPlatformRequest platformRequest = new HttpPlatformRequest(request.getInputStream(), PlatformType.CONTENT_TYPE_JSON);
    platformRequest.receiveData();
    PlatformData inPD = platformRequest.getData();

    VariableList    inVariableList  = inPD.getVariableList();
    DataSetList     inDataSetList   = inPD.getDataSetList();

    String strUserID   = inVariableList.getString("test");
    //String strUserName = inVariableList.getString("username");
     
    //DataSet ds = inDataSetList.get("input");   	
	
	//System.out.println(ds.saveXml());
	
    //VariableList로부터 값을 직접 참조
	String ag1 = inVariableList.getString("ag1");   //product = Nexacro
	String comp = inVariableList.getString("comp");   //product = Nexacro

	if (ag1 == null)
		ag1 = "1";
	
    /*********************************************************
     * response로 보낼 내용을 생성한다.
     * output variable list, output dataset list에 저장한다.
     * (MiPlatform 이 받을 수 있는 데이터 형태로 가공)
     *********************************************************/ 
     out.clear();
     out=pageContext.pushBody();    
     
    HttpPlatformResponse platformResponse = new HttpPlatformResponse(response, PlatformType.CONTENT_TYPE_JSON, strCharset);   
    PlatformData outPD = platformRequest.getData();
    VariableList    outVariableList  = new VariableList();
    DataSetList     outDataSetList   = new DataSetList();
    /*
	if (comp.equals("true"))
	{
		platformResponse.addProtocolType(PlatformType.PROTOCOL_TYPE_ZLIB); 
		System.out.println("platformResponse 압축");
	}
*/
    //System.out.println("100초 대기 시작");
   //Thread.sleep(100);
    //System.out.println("100초 대기 끝");
	
	Cookie[] cookies = request.getCookies();
 
	//String cookieName = cookies[2].getName();
	//String cookieValue = cookies[2].getValue(); 

	int cc = 0;
	for(Cookie c: cookies)
	{
		cc++;
	}
	
	System.out.println("==========================================="+cc);
	
    try {
       
	   /*for(int i = 0; i < 1; i++)
	   {
			DataSet outDataSet0  = new DataSet("output"+i);        
			// Output Dataset 컬럼 정의
			outDataSet0.addConstantColumn("ConstColumn0", DataTypes.STRING, 30, "A"+i);
			outDataSet0.addConstantColumn("ConstColumn1", DataTypes.STRING, 255, "B"+i);
			outDataSet0.addColumn("Column0",   DataTypes.STRING, 255); 
			outDataSet0.addColumn("Column1",   DataTypes.STRING, 255); 
			outDataSet0.addColumn("Column2",   DataTypes.STRING, 255); 
			outDataSet0.addColumn("useclientlayout_JSON",   DataTypes.STRING, 255); 
			outDataSet0.newRow();
			outDataSetList.add(outDataSet0);
		   
	   }
	   */
       DataSet outDataSet00  = new DataSet("output");        
       // Output Dataset 컬럼 정의

		outDataSet00.addColumn("lotNo",   DataTypes.STRING, 255); 
		outDataSet00.addColumn("eqpId",   DataTypes.STRING, 255); 
		outDataSet00.addColumn("inspItemCd",   DataTypes.STRING, 255); 
		outDataSet00.addColumn("inspItemNm",   DataTypes.STRING, 255); 
		  int newRow = 0;
	   for(int i = 0; i < Integer.parseInt(ag1); i++)
	   {
			newRow = outDataSet00.newRow();	 	
			
			outDataSet00.set(newRow, "lotNo", "lotNo"+i);
			outDataSet00.set(newRow, "eqpId", "eqpId"+i);
				
			outDataSet00.set(newRow, "inspItemCd", "^"+i+"^");
			outDataSet00.set(newRow, "inspItemNm", "^"+i+"^");

		   
	   }
	 		
		// Output Dataset 을 Output Dataset List 에 담는다.      									
        outDataSetList.add(outDataSet00);
        
        // Output Vairable 을 세팅한다.		
        
        outVariableList.add("ErrorMsg",  "조회 성공");
		outVariableList.add("ErrorCode", 1);
		//outVariableList.add("ErrorMsg", strUserName);

        //outVariableList.add("strOutputData", "※ Output Vairable을 받으려면, 화면의 전역변수로 선언하면 됩니다.");

    } catch(Exception e) {

        // Output Vairable 을 세팅한다.
        outVariableList.add("ErrorMsg",  "실패");
        outVariableList.add("ErrorCode", -2);
		outVariableList.add("strOutputData", "실패하였습니다.");
        e.printStackTrace();

    } 
	
	request.setCharacterEncoding("utf-8");
	// 쿠키 지정 name, value
	Cookie cookie = new Cookie("Cookie001", "JSON서버쿠키테스트!!!");
	// 쿠키의 유효시간 설정
	cookie.setMaxAge(10);
	//생성된 쿠기에 path설정
	cookie.setPath("/"); //모든문서(디렉토리)에서 쿠키사용가능함
	// 쿠키 추가
	response.addCookie(cookie);
	
	outPD.setDataSetList(outDataSetList);
	outPD.setVariableList(outVariableList);
	platformResponse.setData(outPD);
	platformResponse.sendData();

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
