(function(){try{var c={pluginName:"autogrow",maxHeight:null,isScroll:!1};G_DEPlugin.autogrow=c;c.onInit=function(){var b="../plugin/autogrow/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/config.js",b="1"==DEXTTOP.DEXT5.config.UseConfigTimeStamp?b+("?t="+DEXTTOP.DEXT5.util.getTimeStamp()):b+("?t="+DEXTTOP.DEXT5.UrlStamp),f=c.configLoaded,a=document.getElementsByTagName("head")[0],d=document.createElement("script");d.type="text/javascript";d.src=b;d.onload=f;a.appendChild(d)};c.onLoaded=function(){"0"!=
DEXTTOP.G_CURREDITOR._config.autoGrowMode&&(G_DEPlugin.autogrow.autoGrowMode=DEXTTOP.G_CURREDITOR._config.autoGrowMode);-1<DEXTTOP.G_CURREDITOR._config.style.height.indexOf("%")&&(DEXTTOP.G_CURREDITOR._config.autoGrowMode="0",G_DEPlugin.autogrow.autoGrowMode="0");DEXTTOP.DEXTWIN==top||"1"!=G_DEPlugin.autogrow.autoGrowMode&&"1"!=DEXTTOP.G_CURREDITOR._config.autoGrowMode||(DEXTTOP.G_CURREDITOR._config.autoGrowMode="0",G_DEPlugin.autogrow.autoGrowMode="0");if("0"!=G_DEPlugin.autogrow.autoGrowMode||"0"!=
DEXTTOP.G_CURREDITOR._config.autoGrowMode)DEXTTOP.G_CURREDITOR._config.useLineBreak="1",DEXTTOP.G_CURREDITOR._config.wordWrapType="1",DEXTTOP.G_CURREDITOR._config.resize_bar="0"};c.configLoaded=function(){var b=G_DEPlugin.autogrow.autoGrowMode,a=parseInt(G_DEPlugin.autogrow.maxHeight);if("string"!=typeof b||"0"==G_DEPlugin.autogrow.autoGrowMode)G_DEPlugin.autogrow.autoGrowMode="1";G_DEPlugin.autogrow.autoGrowMode=b;"number"==typeof a&&a&&(a<=parseInt(DEXTTOP.G_CURREDITOR._config.style.height)&&(a=
parseInt(DEXTTOP.G_CURREDITOR._config.style.height)),G_DEPlugin.autogrow.maxHeight=a)};c.onChange=function(){c.autogrow(DEXTTOP.G_CURREDITOR)};c.autogrow=function(b){if("0"!=G_DEPlugin.autogrow.autoGrowMode&&void 0!=G_DEPlugin.autogrow.autoGrowMode)if("full_size"==b.FrameStatus||"design"!=b._currentMode)b._DOC.documentElement.style.overflow="auto";else{var a=b._DOC.documentElement,c=b._BODY,d=DEXTTOP.DEXTDOC.documentElement,h=DEXTTOP.DEXTDOC.body;if(void 0==G_DEPlugin.autogrow.configHeight||null==
G_DEPlugin.autogrow.configHeight||""==G_DEPlugin.autogrow.configHeight)G_DEPlugin.autogrow.configHeight=0>b._defaultHeight?parseInt(b._config.style.height,10)-b._defaultHeight:parseInt(b._config.style.height,10),G_DEPlugin.autogrow.initHeight=0<=b._defaultHeight?b._defaultHeight:0,null!=G_DEPlugin.autogrow.maxHeight&&G_DEPlugin.autogrow.isScroll||(a.style.overflowY="hidden"),G_DEPlugin.autogrow.initParentHeight=d.scrollHeight;else{null!=G_DEPlugin.autogrow.maxHeight&&G_DEPlugin.autogrow.isScroll||
(a.style.overflowY="hidden");G_DEPlugin.autogrow.previousParentTop=Math.max(d.scrollTop,h.scrollTop);setHeight(G_DEPlugin.autogrow.configHeight,b);var g=Math.max(a.scrollHeight,c.scrollHeight),e;if(G_DEPlugin.autogrow.initHeight!=g){e=0==G_DEPlugin.autogrow.initHeight?G_DEPlugin.autogrow.configHeight+(g-b._defaultHeight):G_DEPlugin.autogrow.configHeight+(g-G_DEPlugin.autogrow.initHeight);null!=G_DEPlugin.autogrow.maxHeight&&e>G_DEPlugin.autogrow.maxHeight?(a.style.overflowY="",G_DEPlugin.autogrow.isScroll=
!0):G_DEPlugin.autogrow.isScroll=!1;setHeight(e,b);try{a.scrollHeight>a.clientHeight?(e+=a.scrollHeight-a.clientHeight+1,setHeight(e,b)):c.scrollHeight>c.clientHeight&&(e+=c.scrollHeight-c.clientHeight+1,setHeight(e,b))}catch(l){DEXTTOP&&DEXTTOP.DEXT5&&DEXTTOP.DEXT5.logMode&&window&&window.console&&console.log(l)}}else e=G_DEPlugin.autogrow.configHeight,setHeight(e,b);G_DEPlugin.autogrow.currHeight=g-G_DEPlugin.autogrow.initHeight;G_DEPlugin.autogrow.diffHeight=G_DEPlugin.autogrow.currHeight-G_DEPlugin.autogrow.preHeight;
G_DEPlugin.autogrow.preHeight=g-G_DEPlugin.autogrow.initHeight;"2"!=G_DEPlugin.autogrow.autoGrowMode&&(d.scrollTop=G_DEPlugin.autogrow.previousParentTop+(d.scrollHeight-G_DEPlugin.autogrow.initParentHeight),h.scrollTop=G_DEPlugin.autogrow.previousParentTop+(d.scrollHeight-G_DEPlugin.autogrow.initParentHeight),G_DEPlugin.autogrow.previousParentTop=Math.max(d.scrollTop,h.scrollTop),G_DEPlugin.autogrow.initParentHeight=d.scrollHeight);if("2"==G_DEPlugin.autogrow.autoGrowMode)try{"function"===typeof DEXTTOP.DEXTWIN.dext_editor_autogrow_event&&
DEXTTOP.DEXTWIN.dext_editor_autogrow_event(b,{diffHeight:G_DEPlugin.autogrow.diffHeight})}catch(m){DEXTTOP&&DEXTTOP.DEXT5&&DEXTTOP.DEXT5.logMode&&window&&window.console&&console.log(m)}}}};c.onInit()}catch(a){DEXTTOP&&DEXTTOP.DEXT5&&DEXTTOP.DEXT5.logMode&&window&&window.console&&console.log(a)}})();
function setHeight(c,a){var b=a.ID;a=DEXTTOP.DEXT5.util._setDEXT5editor(b);var f=G_DEPlugin.autogrow.maxHeight;null!=f&&c>=f&&(c=f);1==a._config.ruler.use&&1==a._config.ruler.mode&&(f=parseInt(document.getElementById("dext_tab_tool3_"+a.ID).style.height,10),c+=f,DEXTTOP.DEXT5.browser.ie&&7>=DEXTTOP.DEXT5.browser.ieVersion&&(c+=1));if(void 0==b||""==b)b=a.ID;var f=DEXTTOP.DEXTDOC.getElementById("dext_frame_holder"+b),b=DEXTTOP.DEXTDOC.getElementById("dext_frame_"+b).contentWindow.document.getElementById("ue_editor_holder_"+
b),k=0,k=a.baseMenuToolbarHeight;isViewMode(a)?a._defaultHeight=parseInt(c,10)-4:a._defaultHeight=parseInt(c,10)-k;-1<c.toString().indexOf("%")||-1<c.toString().indexOf("px")?f.style.height=c:f.style.height=c+"px";b.style.height=a._defaultHeight+"px";"1"==G_DEPlugin.autogrow.autoGrowMode&&(a._config.style.height=c+"px","1"==a._config.ruler.view&&"design"==a._currentMode&&a._FRAMEWIN.showRuler(a),"1"==a._config.autoBodyFit&&(a._BODY.style.minHeight=(a._defaultHeight-parseIntOr0(a._config.defaultBodySpace.configValue.top))/
a._defaultHeight*100+"%"))};
