/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-11-26 05:09:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._21_0_0_1800.JEBI_005fTOPS_005fV21.etc_005ffile;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.commons.logging.*;
import com.nexacro.java.xapi.data.*;
import com.nexacro.java.xapi.tx.*;
import java.util.*;
import java.sql.*;
import java.io.*;

public final class RP_005f97621_005fselect_005fnoDb_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 
	public static String EucToUni(String s) 
	{
		String result = "";

		try {
			//result = new String(s.getBytes("8859_1"), "EUC-KR");
			result = new String(s.getBytes("8859_1"), "UTF-8");
		} catch(Exception e) {
			System.out.println(e);
		}
		return result;
	}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(9);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.nexacro.java.xapi.tx");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("org.apache.commons.logging");
    _jspx_imports_packages.add("com.nexacro.java.xapi.data");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/xml; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');
      out.write('\n');


System.out.println("===============================진입");		

	// PlatformData
	PlatformData out_PlatformData = new PlatformData();
	
// HttpServletRequest를 이용하여 HttpPlatformRequest 생성
HttpPlatformRequest pReq = new HttpPlatformRequest(request);
// XML 데이터 분석
pReq.receiveData();
// 데이터를 PlatformData 형태로 저장
PlatformData i_xpData = pReq.getData();

// PlatformData로부터 List 획득 및 Dataset, 변수 추출
VariableList in_vl 	= i_xpData.getVariableList();
String param 		= in_vl.getString("param");
	

	int nErrorCode  = 0;
	int nCnt = 100;
	int row  = -1;
	int row1  = -1;
	String strErrorMsg = "START";
System.out.println("===============================param " + param);				  
	/********* Dataset **********/    
	DataSet ds = new DataSet("ds_employees");
	ds.addColumn("EMPL_ID"		,DataTypes.STRING, (short)10);
	ds.addColumn("FULL_NAME"	,DataTypes.STRING, (short)10);
	ds.addColumn("DEPT_ID"		,DataTypes.STRING, (short)10);
	ds.addColumn("GENDER"		,DataTypes.STRING, (short)10);
	ds.addColumn("HIRE_DATE"	,DataTypes.STRING, (short)10);
	ds.addColumn("MARRIED"		,DataTypes.STRING, (short)10);
	ds.addColumn("SALARY"		,DataTypes.STRING, (short)10);
	ds.addColumn("EMPL_MEMO"	,DataTypes.STRING, (short)10);
	ds.addColumn("RANK"			,DataTypes.STRING, (short)10);
	ds.addColumn("EMAIL"		,DataTypes.STRING, (short)10);
	
	
	DataSet dsTotal = new DataSet("ds_total");
	dsTotal.addColumn("TOTALCNT"		,DataTypes.BIG_DECIMAL);	
		
	if (param.equals("ALL"))
	{
System.out.println("===============================진입1");	
		for(int i = 0 ; i < nCnt ; i++ )		
		{
			row = ds.newRow();
			ds.set(row, "EMPL_ID"	, "EMPL_ID"+i);
			ds.set(row, "FULL_NAME"	, "FULL_NAME"+i);
			ds.set(row, "DEPT_ID"	, "DEPT_ID"+i);
			ds.set(row, "GENDER"	, "GENDER"+i);
			ds.set(row, "HIRE_DATE"	, "HIRE_DATE"+i);
			ds.set(row, "MARRIED"	, "MARRIED"+i);
			ds.set(row, "SALARY"	, "SALARY"+i);
			ds.set(row, "EMPL_MEMO"	, "EMPL_MEMO"+i);
			ds.set(row, "RANK"		, "RANK"+i);
			ds.set(row, "EMAIL"		, "EMAIL"+i);
		}
		row1 = dsTotal.newRow();	
		dsTotal.set(row1, "TOTALCNT"		, 30);
		
	}
	else
	{
System.out.println("===============================진입2");
	row1 = dsTotal.newRow();
	dsTotal.set(row1, "TOTALCNT"		, 0);
	}
		


	// #1 
	out_PlatformData.addDataSet(ds);
	out_PlatformData.addDataSet(dsTotal);

	// #2
	//DataSetList dataList = out_PlatformData.getDataSetList();
	//dataList.add(ds);

	nErrorCode  = 0;
	strErrorMsg = "SUCC";

	VariableList varList = out_PlatformData.getVariableList();
	varList.add("ErrorCode", nErrorCode);
	varList.add("ErrorMsg" , strErrorMsg);

	/*
	Variable varErrCD = new Variable("ErrorCode");
	varErrCD.set(nErrorCode);

	Variable varErrMSG = new Variable("ErrorMsg");
	varErrMSG.set(strErrorMsg);

	out_PlatformData.addVariable(varErrCD);
	out_PlatformData.addVariable(varErrMSG);
	*/


	HttpPlatformResponse pRes = new HttpPlatformResponse(response, PlatformType.CONTENT_TYPE_XML, "utf-8");
	pRes.setData(out_PlatformData);

	Thread.sleep(3000);


	// Send data
	pRes.sendData();

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
