/*
 GNU Lesser General Public License, http://www.gnu.org/copyleft/lesser.html
 @author  Jan Odvarko, http://odvarko.cz
 @created 2008-06-15
 @updated 2013-04-08
 @link    http://jscolor.com
*/
var jscolor={dir:"../images/jscolor/",bindClass:"color",binding:!0,preloading:!0,clickedElem:null,styleColor:"",actionType:"",excuteFn:null,install:function(){jscolor.addEvent(window,"load",jscolor.init)},init:function(){jscolor.binding&&jscolor.bind();jscolor.preloading&&jscolor.preload()},getDir:function(){if(!jscolor.dir){var c=jscolor.detectDir();jscolor.dir=!1!==c?c:"jscolor/"}return jscolor.dir},detectDir:function(){for(var c=location.href,f=document.getElementsByTagName("base"),a=0;a<f.length;a+=
1)f[a].href&&(c=f[a].href);f=document.getElementsByTagName("script");for(a=0;a<f.length;a+=1)if(f[a].src&&/(^|\/)jscolor\.js([?#].*)?$/i.test(f[a].src))return c=(new jscolor.URI(f[a].src)).toAbsolute(c),c.path=c.path.replace(/[^\/]+$/,""),c.query=null,c.fragment=null,c.toString();return!1},bind:function(){for(var c=new RegExp("(^|\\s)("+jscolor.bindClass+")\\s*(\\{[^}]*\\})?","i"),f=document.getElementsByTagName("div"),a=0;a<f.length;a+=1){var m;if(!f[a].color&&f[a].className&&(m=f[a].className.match(c))){var x=
{};if(m[3])try{x=(new Function("return ("+m[3]+")"))()}catch(G){}f[a].color=new jscolor.color(f[a],x)}}},preload:function(){for(var c in jscolor.imgRequire)jscolor.imgRequire.hasOwnProperty(c)&&jscolor.loadImage(c)},images:{pad:[171,81],sld:[15,81],cross:[20,20],arrow:[3,0]},imgRequire:{},imgLoaded:{},requireImage:function(c){jscolor.imgRequire[c]=!0},loadImage:function(c){jscolor.imgLoaded[c]||(jscolor.imgLoaded[c]=new Image,jscolor.imgLoaded[c].src=jscolor.getDir()+c)},fetchElement:function(c){return"string"===
typeof c?document.getElementById(c):c},addEvent:function(c,f,a){c.addEventListener?c.addEventListener(f,a,!1):c.attachEvent&&c.attachEvent("on"+f,a)},fireEvent:function(c,f){if(c)if(document.createEvent){var a=document.createEvent("HTMLEvents");a.initEvent(f,!0,!0);c.dispatchEvent(a)}else if(document.createEventObject)document.createEventObject();else if(c["on"+f])c["on"+f]()},getElementPos:function(c){var f=c,a=0,m=0;if(f.offsetParent){do a+=f.offsetLeft,m+=f.offsetTop;while(f=f.offsetParent)}for(;(c=
c.parentNode)&&"BODY"!==c.nodeName.toUpperCase();)a-=c.scrollLeft,m-=c.scrollTop;return[a,m]},getElementSize:function(c){return[c.offsetWidth,c.offsetHeight]},getRelMousePos:function(c){var f=0,a=0;c||(c=window.event);"number"===typeof c.offsetX?(f=c.offsetX,a=c.offsetY):"number"===typeof c.layerX&&(f=c.layerX,a=c.layerY);return{x:f,y:a}},getViewPos:function(){return"number"===typeof window.pageYOffset?[window.pageXOffset,window.pageYOffset]:document.body&&(document.body.scrollLeft||document.body.scrollTop)?
[document.body.scrollLeft,document.body.scrollTop]:document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[0,0]},getViewSize:function(){return"number"===typeof window.innerWidth?[window.innerWidth,window.innerHeight]:document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?[document.documentElement.clientWidth,document.documentElement.clientHeight]:
document.body&&(document.body.clientWidth||document.body.clientHeight)?[document.body.clientWidth,document.body.clientHeight]:[0,0]},URI:function(c){function f(a){for(var c="";a;)if("../"===a.substr(0,3)||"./"===a.substr(0,2))a=a.replace(/^\.+/,"").substr(1);else if("/./"===a.substr(0,3)||"/."===a)a="/"+a.substr(3);else if("/../"===a.substr(0,4)||"/.."===a)a="/"+a.substr(4),c=c.replace(/\/?[^\/]*$/,"");else if("."===a||".."===a)a="";else{var f=a.match(/^\/?[^\/]*/)[0];a=a.substr(f.length);c+=f}return c}
this.authority=this.scheme=null;this.path="";this.fragment=this.query=null;this.parse=function(a){a=a.match(/^(([A-Za-z][0-9A-Za-z+.-]*)(:))?((\/\/)([^\/?#]*))?([^?#]*)((\?)([^#]*))?((#)(.*))?/);this.scheme=a[3]?a[2]:null;this.authority=a[5]?a[6]:null;this.path=a[7];this.query=a[9]?a[10]:null;this.fragment=a[12]?a[13]:null;return this};this.toString=function(){var a="";null!==this.scheme&&(a=a+this.scheme+":");null!==this.authority&&(a=a+"//"+this.authority);null!==this.path&&(a+=this.path);null!==
this.query&&(a=a+"?"+this.query);null!==this.fragment&&(a=a+"#"+this.fragment);return a};this.toAbsolute=function(a){a=new jscolor.URI(a);var c=new jscolor.URI;if(null===a.scheme)return!1;null!==this.scheme&&this.scheme.toLowerCase()===a.scheme.toLowerCase()&&(this.scheme=null);null!==this.scheme?(c.scheme=this.scheme,c.authority=this.authority,c.path=f(this.path),c.query=this.query):(null!==this.authority?(c.authority=this.authority,c.path=f(this.path),c.query=this.query):(""===this.path?(c.path=
a.path,c.query=null!==this.query?this.query:a.query):("/"===this.path.substr(0,1)?c.path=f(this.path):(c.path=null!==a.authority&&""===a.path?"/"+this.path:a.path.replace(/[^\/]+$/,"")+this.path,c.path=f(c.path)),c.query=this.query),c.authority=a.authority),c.scheme=a.scheme);c.fragment=this.fragment;return c};c&&this.parse(c)},color:function(c,f,a,m,x,G){function z(b,a,c){if(null===b)return[c,c,c];var e=Math.floor(b),d=c*(1-a);b=c*(1-a*(e%2?b-e:1-(b-e)));switch(e){case 6:case 0:return[c,b,d];case 1:return[b,
c,d];case 2:return[d,c,b];case 3:return[d,b,c];case 4:return[b,d,c];case 5:return[c,d,b]}}function K(b,a){if(!jscolor.picker){jscolor.picker={box:document.createElement("div"),boxB:document.createElement("div"),pad:document.createElement("div"),padB:document.createElement("div"),padM:document.createElement("div"),sld:document.createElement("div"),sldB:document.createElement("div"),sldM:document.createElement("div"),btn:document.createElement("div"),btnS:document.createElement("span"),btnT:document.createTextNode(e.pickerCloseText),
btnOk:document.createElement("input"),btnCancle:document.createElement("input"),lbColor:document.createElement("input"),lbColor2:document.createElement("input"),bottom:document.createElement("div")};for(var t=0;t<jscolor.images.sld[1];t+=4){var f=document.createElement("div");f.style.height="4px";f.style.fontSize="1px";f.style.lineHeight="0";jscolor.picker.sld.appendChild(f)}jscolor.picker.sldB.appendChild(jscolor.picker.sld);jscolor.picker.box.appendChild(jscolor.picker.sldB);jscolor.picker.box.appendChild(jscolor.picker.sldM);
jscolor.picker.padB.appendChild(jscolor.picker.pad);jscolor.picker.box.appendChild(jscolor.picker.padB);jscolor.picker.box.appendChild(jscolor.picker.padM);jscolor.picker.btnS.appendChild(jscolor.picker.btnT);jscolor.picker.btn.appendChild(jscolor.picker.btnS);jscolor.picker.box.appendChild(jscolor.picker.btn);jscolor.picker.boxB.appendChild(jscolor.picker.box);jscolor.picker.lbColor2.setAttribute("type","text");jscolor.picker.lbColor2.setAttribute("id","cp_lb_color2");jscolor.picker.lbColor2.setAttribute("readonly",
"readonly");jscolor.picker.lbColor2.style.border="solid 1px #7D7D7D";jscolor.picker.lbColor2.style.width="34px";jscolor.picker.lbColor2.style.height="19px";jscolor.picker.lbColor.setAttribute("type","text");jscolor.picker.lbColor.setAttribute("id","cp_lb_color");jscolor.picker.lbColor.style.border="solid 1px #7D7D7D";jscolor.picker.lbColor.style.width="58px";jscolor.picker.lbColor.style.height="19px";jscolor.picker.lbColor.style.color="#000000";jscolor.picker.btnOk.setAttribute("type","button");jscolor.picker.btnOk.setAttribute("id",
"cp_btn_ok");jscolor.picker.btnOk.setAttribute("value","Ok");jscolor.picker.btnOk.style.width="40px";jscolor.picker.btnOk.style.color="#000000";jscolor.picker.btnCancle.setAttribute("type","button");jscolor.picker.btnCancle.setAttribute("id","cp_btn_cancle");jscolor.picker.btnCancle.setAttribute("value","Close");jscolor.picker.btnCancle.style.width="54px";jscolor.picker.btnCancle.style.color="#000000";jscolor.picker.bottom.appendChild(jscolor.picker.lbColor2);jscolor.picker.bottom.appendChild(jscolor.picker.lbColor);
jscolor.picker.bottom.appendChild(jscolor.picker.btnOk);jscolor.picker.bottom.appendChild(jscolor.picker.btnCancle);jscolor.picker.boxB.appendChild(jscolor.picker.bottom);jscolor.picker.boxB.setAttribute("id","color_picker")}var d=jscolor.picker;d.box.onmouseup=d.box.onmouseout=function(){c.focus()};d.box.onmousedown=function(){u=!0};d.box.onmousemove=function(b){if(n||p)n&&A(b),p&&B(b),document.selection?document.selection.empty():window.getSelection&&window.getSelection().removeAllRanges(),v()};
"ontouchstart"in window&&d.box.addEventListener("touchmove",function(b){var d={offsetX:b.touches[0].pageX-q.X,offsetY:b.touches[0].pageY-q.Y};if(n||p)n&&A(d),p&&B(d),v();b.stopPropagation();b.preventDefault()},!1);d.padM.onmouseup=d.padM.onmouseout=function(){n&&(n=!1,jscolor.fireEvent(k,"change"))};d.padM.onmousedown=function(b){switch(r){case 0:0===e.hsv[2]&&e.fromHSV(null,null,1);break;case 1:0===e.hsv[1]&&e.fromHSV(null,1,null)}p=!1;n=!0;A(b);v()};"ontouchstart"in window&&d.padM.addEventListener("touchstart",
function(b){q={X:b.target.offsetParent.offsetLeft,Y:b.target.offsetParent.offsetTop};this.onmousedown({offsetX:b.touches[0].pageX-q.X,offsetY:b.touches[0].pageY-q.Y})});d.sldM.onmouseup=d.sldM.onmouseout=function(){p&&(p=!1,jscolor.fireEvent(k,"change"))};d.sldM.onmousedown=function(b){n=!1;p=!0;B(b);v()};"ontouchstart"in window&&d.sldM.addEventListener("touchstart",function(b){q={X:b.target.offsetParent.offsetLeft,Y:b.target.offsetParent.offsetTop};this.onmousedown({offsetX:b.touches[0].pageX-q.X,
offsetY:b.touches[0].pageY-q.Y})});t=H(e);d.box.style.width=t[0]+"px";d.box.style.height=t[1]+"px";d.boxB.style.position="absolute";d.boxB.style.clear="both";d.boxB.style.left=b-6+"px";d.boxB.style.top=a+2+"px";d.boxB.style.zIndex=e.pickerZIndex;d.boxB.style.border=e.pickerBorder+"px solid";d.boxB.style.borderColor=e.pickerBorderColor;d.boxB.style.background=e.pickerFaceColor;d.pad.style.width=jscolor.images.pad[0]+"px";d.pad.style.height=jscolor.images.pad[1]+"px";d.padB.style.position="absolute";
d.padB.style.left=e.pickerFace+"px";d.padB.style.top=e.pickerFace+"px";d.padB.style.border=e.pickerInset+"px solid";d.padB.style.borderColor=e.pickerInsetColor;d.padM.style.position="absolute";d.padM.style.left="0";d.padM.style.top="0";d.padM.style.width=e.pickerFace+2*e.pickerInset+jscolor.images.pad[0]+"px";d.padM.style.height=d.box.style.height;d.padM.style.cursor="crosshair";d.sld.style.overflow="hidden";d.sld.style.width=jscolor.images.sld[0]+"px";d.sld.style.height=jscolor.images.sld[1]+"px";
d.sldB.style.display=e.slider?"block":"none";d.sldB.style.position="absolute";d.sldB.style.right=e.pickerFace+"px";d.sldB.style.top=e.pickerFace+"px";d.sldB.style.border=e.pickerInset+"px solid";d.sldB.style.borderColor=e.pickerInsetColor;d.sldM.style.display=e.slider?"block":"none";d.sldM.style.position="absolute";d.sldM.style.right="0";d.sldM.style.top="0";d.sldM.style.width=jscolor.images.sld[0]+jscolor.images.arrow[0]+e.pickerFace+2*e.pickerInset+"px";d.sldM.style.height=d.box.style.height;try{d.sldM.style.cursor=
"pointer"}catch(l){d.sldM.style.cursor="hand"}d.btn.style.display=e.pickerClosable?"block":"none";d.btn.style.position="absolute";d.btn.style.left=e.pickerFace+"px";d.btn.style.bottom=e.pickerFace+"px";d.btn.style.padding="0 15px";d.btn.style.height="18px";d.btn.style.border=e.pickerInset+"px solid";(function(){var b=e.pickerInsetColor.split(/\s+/);d.btn.style.borderColor=2>b.length?b[0]:b[1]+" "+b[0]+" "+b[0]+" "+b[1]})();d.btn.style.color=e.pickerButtonColor;d.btn.style.font="12px sans-serif";d.btn.style.textAlign=
"center";try{d.btn.style.cursor="pointer"}catch(g){d.btn.style.cursor="hand"}d.btn.onmousedown=function(){e.hidePicker()};d.btnS.style.lineHeight=d.btn.style.height;d.btnOk.style.margin="0 2px 0 4px";d.btnOk.style.verticalAlign="auto";d.btnOk.style.height="19px";d.btnOk.style.cursor="pointer";d.btnOk.onmousedown=function(){var b=document.getElementById("cp_lb_color").value;jscolor.excuteFn(b)};d.lbColor2.style.margin="0 2px 0 0";d.bottom.style.margin="0 0 3px 6px";d.btnCancle.style.verticalAlign=
"auto";d.btnCancle.style.height="19px";d.btnCancle.style.cursor="pointer";d.btnCancle.onmousedown=function(){jscolor.excuteFn("cancel")};switch(r){case 0:var h="hs.png";break;case 1:h="hv.png"}d.padM.style.backgroundImage="url("+KPHOTOTOP.G_CURRKPHOTO._config.webPath.image+"jscolor/cross.gif)";d.padM.style.backgroundRepeat="no-repeat";d.pad.style.backgroundImage="url("+KPHOTOTOP.G_CURRKPHOTO._config.webPath.image+"jscolor/"+h+")";d.pad.style.backgroundRepeat="no-repeat";d.pad.style.backgroundPosition=
"0 0";I();J();jscolor.picker.owner=e;document.getElementsByTagName("body")[0].appendChild(d.boxB)}function H(b){return[2*b.pickerInset+2*b.pickerFace+jscolor.images.pad[0]+(b.slider?2*b.pickerInset+2*jscolor.images.arrow[0]+jscolor.images.sld[0]:0),b.pickerClosable?4*b.pickerInset+3*b.pickerFace+jscolor.images.pad[1]+b.pickerButtonHeight:2*b.pickerInset+2*b.pickerFace+jscolor.images.pad[1]]}function I(){switch(r){case 0:var b=1;break;case 1:b=2}var c=Math.round(e.hsv[0]/6*(jscolor.images.pad[0]-1)),
b=Math.round((1-e.hsv[b])*(jscolor.images.pad[1]-1));jscolor.picker.padM.style.backgroundPosition=e.pickerFace+e.pickerInset+c-Math.floor(jscolor.images.cross[0]/2)+"px "+(e.pickerFace+e.pickerInset+b-Math.floor(jscolor.images.cross[1]/2))+"px";c=jscolor.picker.sld.childNodes;switch(r){case 0:for(var a=z(e.hsv[0],e.hsv[1],1),b=0;b<c.length;b+=1)c[b].style.backgroundColor="rgb("+a[0]*(1-b/c.length)*100+"%,"+a[1]*(1-b/c.length)*100+"%,"+a[2]*(1-b/c.length)*100+"%)";break;case 1:var f,d=[e.hsv[2],0,
0],b=Math.floor(e.hsv[0]),l=b%2?e.hsv[0]-b:1-(e.hsv[0]-b);switch(b){case 6:case 0:a=[0,1,2];break;case 1:a=[1,0,2];break;case 2:a=[2,0,1];break;case 3:a=[2,1,0];break;case 4:a=[1,2,0];break;case 5:a=[0,2,1]}for(b=0;b<c.length;b+=1)f=1-1/(c.length-1)*b,d[1]=d[0]*(1-f*l),d[2]=d[0]*(1-f),c[b].style.backgroundColor="rgb("+100*d[a[0]]+"%,"+100*d[a[1]]+"%,"+100*d[a[2]]+"%)"}}function J(){switch(r){case 0:var b=2;break;case 1:b=1}b=Math.round((1-e.hsv[b])*(jscolor.images.sld[1]-1));jscolor.picker.sldM.style.backgroundPosition=
"0 "+(e.pickerFace+e.pickerInset+b-Math.floor(jscolor.images.arrow[1]/2))+"px"}function y(){return jscolor.picker&&jscolor.picker.owner===e}function L(){k!==c&&e.importColor()}function A(b){var c=jscolor.getRelMousePos(b);b=c.x-e.pickerFace-e.pickerInset;c=c.y-e.pickerFace-e.pickerInset;switch(r){case 0:e.fromHSV(6/(jscolor.images.pad[0]-1)*b,1-c/(jscolor.images.pad[1]-1),null,C);break;case 1:e.fromHSV(6/(jscolor.images.pad[0]-1)*b,null,1-c/(jscolor.images.pad[1]-1),C)}}function B(b){b=jscolor.getRelMousePos(b).y-
e.pickerFace-e.pickerInset;switch(r){case 0:e.fromHSV(null,null,1-b/(jscolor.images.sld[1]-1),D);break;case 1:e.fromHSV(null,1-b/(jscolor.images.sld[1]-1),null,D)}}function v(){e.onImmediateChange&&("string"===typeof e.onImmediateChange?new Function(e.onImmediateChange):e.onImmediateChange).call(e)}jscolor.clickedElem=a;jscolor.styleColor=m;jscolor.actionType=x;jscolor.excuteFn=G;this.slider=this.caps=this.hash=this.adjust=this.required=!0;this.styleElement=this.valueElement=c;this.onImmediateChange=
null;this.hsv=[0,0,1];this.rgb=[1,1,1];this.minH=0;this.maxH=6;this.minS=0;this.maxS=1;this.minV=0;this.maxV=1;this.pickerOnfocus=!1;this.pickerMode="HSV";this.pickerPosition="bottom";this.pickerSmartPosition=!1;this.pickerButtonHeight=0;this.pickerClosable=!1;this.pickerCloseText="Close";this.pickerButtonColor="ButtonText";this.pickerFace=6;this.pickerFaceColor="ThreeDFace";this.pickerBorder=1;this.pickerBorderColor="ThreeDHighlight ThreeDShadow ThreeDShadow ThreeDHighlight";this.pickerInset=1;this.pickerInsetColor=
"ThreeDShadow ThreeDShadow ThreeDShadow ThreeDShadow";this.pickerZIndex=15E3;for(var E in f)f.hasOwnProperty(E)&&(this[E]=f[E]);this.hidePicker=function(){y()&&(delete jscolor.picker.owner,document.getElementsByTagName("body")[0].removeChild(jscolor.picker.boxB))};this.showPicker=function(){if(!y()){var b=jscolor.getElementPos(c),a=jscolor.getElementSize(c),e=jscolor.getViewPos(),f=jscolor.getViewSize(),d=H(this),l,g,h;switch(this.pickerPosition.toLowerCase()){case "left":l=1;g=0;h=-1;break;case "right":l=
1;g=0;h=1;break;case "top":l=0;g=1;h=-1;break;default:l=0,h=g=1}var k=(a[g]+d[g])/2,b=this.pickerSmartPosition?[-e[l]+b[l]+d[l]>f[l]?-e[l]+b[l]+a[l]/2>f[l]/2&&0<=b[l]+a[l]-d[l]?b[l]+a[l]-d[l]:b[l]:b[l],-e[g]+b[g]+a[g]+d[g]-k+k*h>f[g]?-e[g]+b[g]+a[g]/2>f[g]/2&&0<=b[g]+a[g]-k-k*h?b[g]+a[g]-k-k*h:b[g]+a[g]-k+k*h:0<=b[g]+a[g]-k+k*h?b[g]+a[g]-k+k*h:b[g]+a[g]-k-k*h]:[b[l],b[g]+a[g]-k+k*h];K(b[l],b[g])}};this.importColor=function(){k?this.adjust?!this.required&&/^\s*$/.test(k.value)?(k.value="",h.style.backgroundImage=
h.jscStyle.backgroundImage,h.style.backgroundColor=h.jscStyle.backgroundColor,h.style.color=h.jscStyle.color,this.exportColor(w|F)):this.fromString(k.value)||this.exportColor():this.fromString(k.value,w)||(h.style.backgroundImage=h.jscStyle.backgroundImage,h.style.backgroundColor=h.jscStyle.backgroundColor,h.style.color=h.jscStyle.color,this.exportColor(w|F)):this.exportColor()};this.exportColor=function(b){if(!(b&w)&&k){var a=this.toString();this.caps&&(a=a.toUpperCase());this.hash&&(a="#"+a);null!=
document.getElementById("cp_lb_color")&&(document.getElementById("cp_lb_color").value=a)}b&F||!h||(h.style.backgroundImage="none",null!=document.getElementById("cp_lb_color2")&&(document.getElementById("cp_lb_color2").style.backgroundColor="#"+this.toString()));b&D||!y()||I();b&C||!y()||J()};this.fromHSV=function(b,a,c,e){null!==b&&(b=Math.max(0,this.minH,Math.min(6,this.maxH,b)));null!==a&&(a=Math.max(0,this.minS,Math.min(1,this.maxS,a)));null!==c&&(c=Math.max(0,this.minV,Math.min(1,this.maxV,c)));
this.rgb=z(null===b?this.hsv[0]:this.hsv[0]=b,null===a?this.hsv[1]:this.hsv[1]=a,null===c?this.hsv[2]:this.hsv[2]=c);this.exportColor(e)};this.fromRGB=function(b,a,c,e){null!==b&&(b=Math.max(0,Math.min(1,b)));null!==a&&(a=Math.max(0,Math.min(1,a)));null!==c&&(c=Math.max(0,Math.min(1,c)));b=null===b?this.rgb[0]:b;a=null===a?this.rgb[1]:a;var d=null===c?this.rgb[2]:c,f=Math.min(Math.min(b,a),d);c=Math.max(Math.max(b,a),d);var g=c-f;0===g?b=[null,0,c]:(b=b===f?3+(d-a)/g:a===f?5+(b-d)/g:1+(a-b)/g,b=[6===
b?0:b,g/c,c]);null!==b[0]&&(this.hsv[0]=Math.max(0,this.minH,Math.min(6,this.maxH,b[0])));0!==b[2]&&(this.hsv[1]=null===b[1]?null:Math.max(0,this.minS,Math.min(1,this.maxS,b[1])));this.hsv[2]=null===b[2]?null:Math.max(0,this.minV,Math.min(1,this.maxV,b[2]));b=z(this.hsv[0],this.hsv[1],this.hsv[2]);this.rgb[0]=b[0];this.rgb[1]=b[1];this.rgb[2]=b[2];this.exportColor(e)};this.fromString=function(b,a){var c="More".match(/^\W*([0-9A-F]{3}([0-9A-F]{3})?)\W*$/i);return c?(6===c[1].length?this.fromRGB(parseInt(c[1].substr(0,
2),16)/255,parseInt(c[1].substr(2,2),16)/255,parseInt(c[1].substr(4,2),16)/255,a):this.fromRGB(parseInt(c[1].charAt(0)+c[1].charAt(0),16)/255,parseInt(c[1].charAt(1)+c[1].charAt(1),16)/255,parseInt(c[1].charAt(2)+c[1].charAt(2),16)/255,a),!0):!1};this.toString=function(){return(256|Math.round(255*this.rgb[0])).toString(16).substr(1)+(256|Math.round(255*this.rgb[1])).toString(16).substr(1)+(256|Math.round(255*this.rgb[2])).toString(16).substr(1)};var e=this,r="hvs"===this.pickerMode.toLowerCase()?
1:0,u=!1,k=jscolor.fetchElement(this.valueElement),h=jscolor.fetchElement(this.styleElement),n=!1,p=!1,q={},w=1,F=2,D=4,C=8;jscolor.addEvent(c,"click",function(){e.showPicker()});jscolor.addEvent(c,"blur",function(){u?u=!1:window.setTimeout(function(){u||(k===c&&e.importColor(),e.pickerOnfocus&&e.hidePicker());u=!1},0)});k&&(f=function(){e.fromString(k.value,w);v()},jscolor.addEvent(k,"keyup",f),jscolor.addEvent(k,"input",f),jscolor.addEvent(k,"blur",L),k.setAttribute("autocomplete","off"));h&&(h.jscStyle=
{backgroundImage:h.style.backgroundImage,backgroundColor:h.style.backgroundColor,color:h.style.color});switch(r){case 0:jscolor.requireImage("hs.png");break;case 1:jscolor.requireImage("hv.png")}jscolor.requireImage("cross.gif");jscolor.requireImage("arrow.gif");this.importColor()}};
