{
   "Datasets":[
      {
         "ColumnInfo":{
            "Column":[
               {
                  "size":"32",
                  "id":"cd",
                  "type":"string"
               },
               {
                  "size":"32",
                  "id":"cdnm",
                  "type":"string"
               }
            ]
         },
         "id":"output",
         "Rows":[
            {
               "cd":"Y",
               "_RowType_":"N",
               "cdnm":"예"
            },
            {
               "cd":"N",
               "_RowType_":"N",
               "cdnm":"아니오"
            }
         ]
      }
   ],
   "Parameters":[
      {
         "id":"ErrorCode",
         "type":"int",
         "value":"0"
      }
   ],
   "version":"1.0"
}