(function(a,c){"object"===typeof exports&&"undefined"!==typeof module?module.exports=c():"function"===typeof define&&define.amd?define(c):a.Cropper=c()})(this,function(){function a(e){return"number"===typeof e&&!isNaN(e)}function c(e){return"undefined"===typeof e}function b(e){return"object"===("undefined"===typeof e?"undefined":ja(e))&&null!==e}function d(e){if(!b(e))return!1;try{var k=e.constructor,a=k.prototype;return k&&a&&ka.call(a,"isPrototypeOf")}catch(c){return!1}}function g(e){return"function"===
T.call(e).slice(8,-1).toLowerCase()}function n(e){return Array.isArray?Array.isArray(e):"array"===T.call(e).slice(8,-1).toLowerCase()}function u(e){"string"===typeof e&&(e=e.trim?e.trim():e.replace(la,"$1"));return e}function m(e,k){if(e&&g(k)){var t=void 0;if(n(e)||a(e.length))for(var c=e.length,t=0;t<c&&!1!==k.call(e,e[t],t,e);t+=1);else b(e)&&Object.keys(e).forEach(function(a){k.call(e,e[a],a,e)})}return e}function r(e){for(var k=arguments.length,a=Array(1<k?k-1:0),c=1;c<k;c++)a[c-1]=arguments[c];
if(b(e)&&0<a.length){if(Object.assign)return Object.assign.apply(Object,[e].concat(a));a.forEach(function(k){b(k)&&Object.keys(k).forEach(function(a){e[a]=k[a]})})}return e}function z(e,k){for(var a=arguments.length,b=Array(2<a?a-2:0),c=2;c<a;c++)b[c-2]=arguments[c];return function(){for(var a=arguments.length,t=Array(a),c=0;c<a;c++)t[c]=arguments[c];return e.apply(k,b.concat(t))}}function y(e,k){var t=e.style;m(k,function(e,k){ma.test(k)&&a(e)&&(e+="px");t[k]=e})}function B(e,k){return e.classList?
e.classList.contains(k):-1<e.className.indexOf(k)}function v(e,k){if(k)if(a(e.length))m(e,function(e){v(e,k)});else if(e.classList)e.classList.add(k);else{var t=u(e.className);t?0>t.indexOf(k)&&(e.className=t+" "+k):e.className=k}}function G(e,k){k&&(a(e.length)?m(e,function(e){G(e,k)}):e.classList?e.classList.remove(k):0<=e.className.indexOf(k)&&(e.className=e.className.replace(k,"")))}function J(e,k,t){k&&(a(e.length)?m(e,function(e){J(e,k,t)}):t?v(e,k):G(e,k))}function R(e){return e.replace(na,
"$1-$2").toLowerCase()}function N(e,k){return b(e[k])?e[k]:e.dataset?e.dataset[k]:e.getAttribute("data-"+R(k))}function K(e,k,a){b(a)?e[k]=a:e.dataset?e.dataset[k]=a:e.setAttribute("data-"+R(k),a)}function U(e,k){if(b(e[k]))delete e[k];else if(e.dataset)try{delete e.dataset[k]}catch(a){e.dataset[k]=null}else e.removeAttribute("data-"+R(k))}function A(e,k,a){var b=u(k).split(V);1<b.length?m(b,function(k){A(e,k,a)}):e.removeEventListener?e.removeEventListener(k,a,!1):e.detachEvent&&e.detachEvent("on"+
k,a)}function C(e,k,a,b){var c=u(k).split(V),h=a;1<c.length?m(c,function(k){C(e,k,a)}):(b&&(a=function(){for(var b=arguments.length,c=Array(b),M=0;M<b;M++)c[M]=arguments[M];A(e,k,a);return h.apply(e,c)}),e.addEventListener?e.addEventListener(k,a,!1):e.attachEvent&&e.attachEvent("on"+k,a))}function I(e,k,a){if(e.dispatchEvent){var b=void 0;g(Event)&&g(CustomEvent)?b=c(a)?new Event(k,{bubbles:!0,cancelable:!0}):new CustomEvent(k,{detail:a,bubbles:!0,cancelable:!0}):c(a)?(b=document.createEvent("Event"),
b.initEvent(k,!0,!0)):(b=document.createEvent("CustomEvent"),b.initCustomEvent(k,!0,!0,a));return e.dispatchEvent(b)}return e.fireEvent?e.fireEvent("on"+k):!0}function O(e){var k=e||window.event;k.target||(k.target=k.srcElement||document);if(!a(k.pageX)&&a(k.clientX)){var t=e.target.ownerDocument||document;e=t.documentElement;t=t.body;k.pageX=k.clientX+((e&&e.scrollLeft||t&&t.scrollLeft||0)-(e&&e.clientLeft||t&&t.clientLeft||0));k.pageY=k.clientY+((e&&e.scrollTop||t&&t.scrollTop||0)-(e&&e.clientTop||
t&&t.clientTop||0))}return k}function X(e){var k=document.documentElement;e=e.getBoundingClientRect();return{left:e.left+((window.scrollX||k&&k.scrollLeft||0)-(k&&k.clientLeft||0)),top:e.top+((window.scrollY||k&&k.scrollTop||0)-(k&&k.clientTop||0))}}function H(e,k){return e.getElementsByClassName?e.getElementsByClassName(k):e.querySelectorAll("."+k)}function S(e){e.parentNode&&e.parentNode.removeChild(e)}function Y(e){return(e=e.match(oa))&&(e[1]!==location.protocol||e[2]!==location.hostname||e[3]!==
location.port)}function Z(e){var k="timestamp="+(new Date).getTime();return e+(-1===e.indexOf("?")?"?":"&")+k}function pa(e,k){if(e.naturalWidth&&!aa)k(e.naturalWidth,e.naturalHeight);else{var a=document.createElement("img");a.onload=function(){k(this.width,this.height)};a.src=e.src}}function L(e){var k=[],t=e.translateX,b=e.translateY,c=e.rotate,h=e.scaleX;e=e.scaleY;a(t)&&0!==t&&k.push("translateX("+t+"px)");a(b)&&0!==b&&k.push("translateY("+b+"px)");a(c)&&0!==c&&k.push("rotate("+c+"deg)");a(h)&&
1!==h&&k.push("scaleX("+h+")");a(e)&&1!==e&&k.push("scaleY("+e+")");k=k.length?k.join(" "):"none";return{WebkitTransform:k,msTransform:k,transform:k}}function P(e,a){var t=Math.abs(e.degree)%180,b=(90<t?180-t:t)*Math.PI/180,t=Math.sin(b),b=Math.cos(b),c=e.width,h=e.height,f=e.aspectRatio,l=void 0,d=void 0;a?(l=c/(b+t/f),d=l/f):(l=c*b+h*t,d=c*t+h*b);return{width:l,height:d}}function ba(e,k,t){var b=document.createElement("canvas"),c=b.getContext("2d"),h=0,f=0,l=k.naturalWidth,d=k.naturalHeight,p=k.rotate,
g=k.scaleX;k=k.scaleY;var m=a(g)&&a(k)&&(1!==g||1!==k),y=a(p)&&0!==p,r=y||m,n=l*Math.abs(g||1),v=d*Math.abs(k||1),u=void 0,w=void 0,z=void 0;m&&(u=n/2,w=v/2);y&&(z=P({width:n,height:v,degree:p}),n=z.width,v=z.height,u=n/2,w=v/2);b.width=n;b.height=v;t.fillColor&&(c.fillStyle=t.fillColor,c.fillRect(0,0,n,v));r&&(h=-l/2,f=-d/2,c.save(),c.translate(u,w));y&&c.rotate(p*Math.PI/180);m&&c.scale(g,k);c.imageSmoothingEnabled=!!t.imageSmoothingEnabled;t.imageSmoothingQuality&&(c.imageSmoothingQuality=t.imageSmoothingQuality);
c.drawImage(e,Math.floor(h),Math.floor(f),Math.floor(l),Math.floor(d));r&&c.restore();return b}function qa(e){e=e.replace(ra,"");e=atob(e);for(var a=e.length,b=new ArrayBuffer(a),c=new Uint8Array(b),q=void 0,q=0;q<a;q+=1)c[q]=e.charCodeAt(q);return b}function Q(e,a){var b=e.pageX,c=e.pageY,q={endX:b,endY:c};return a?q:r({startX:b,startY:c},q)}function sa(e){var a=r({},e),b=[];m(e,function(e,c){delete a[c];m(a,function(a){var k=Math.abs(e.startX-a.startX),c=Math.abs(e.startY-a.startY),q=Math.abs(e.endX-
a.endX);a=Math.abs(e.endY-a.endY);k=Math.sqrt(k*k+c*c);q=(Math.sqrt(q*q+a*a)-k)/k;b.push(q)})});b.sort(function(e,a){return Math.abs(e)<Math.abs(a)});return b[0]}function ta(e){if(Array.isArray(e)){for(var a=0,b=Array(e.length);a<e.length;a++)b[a]=e[a];return b}return Array.from(e)}function ua(e){var a=0,b=0,c=0;m(e,function(e){var h=e.startY;a+=e.startX;b+=h;c+=1});a/=c;b/=c;return{pageX:a,pageY:b}}var ca={viewMode:0,dragMode:"crop",aspectRatio:NaN,data:null,preview:"",responsive:!0,restore:!0,checkCrossOrigin:!0,
checkOrientation:!0,modal:!0,guides:!0,center:!0,highlight:!0,background:!0,autoCrop:!0,autoCropArea:.8,movable:!0,rotatable:!0,scalable:!0,zoomable:!1,zoomOnTouch:!0,zoomOnWheel:!0,wheelZoomRatio:.1,cropBoxMovable:!0,cropBoxResizable:!0,toggleDragModeOnDblclick:!0,minCanvasWidth:0,minCanvasHeight:0,minCropBoxWidth:0,minCropBoxHeight:0,minContainerWidth:1,minContainerHeight:1,ready:null,cropstart:null,cropmove:null,cropend:null,crop:null,zoom:null},ja="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?
function(e){return typeof e}:function(e){return e&&"function"===typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e},ra=/^data:.*,/,na=/([a-z\d])([A-Z])/g,oa=/^(https?:)\/\/([^:/?#]+):?(\d*)/i,V=/\s+/,ma=/^(width|height|left|top|marginLeft|marginTop)$/,la=/^\s+(.*)\s+$/,E=/(Macintosh|iPhone|iPod|iPad).*AppleWebKit/i,da="undefined"!==typeof window?window.navigator:null,aa=da&&E.test(da.userAgent),E=Object.prototype,T=E.toString,ka=E.hasOwnProperty,ea=String.fromCharCode,fa=
(E="undefined"!==typeof window?window.PointerEvent:null)?"pointerdown":"touchstart mousedown",ga=E?"pointermove":"touchmove mousemove",ha=E?" pointerup pointercancel":"touchend touchcancel mouseup",va=/^(e|w|s|n|se|sw|ne|nw|all|crop|move|zoom)$/,wa=function(){function e(e,a){for(var b=0;b<a.length;b++){var c=a[b];c.enumerable=c.enumerable||!1;c.configurable=!0;"value"in c&&(c.writable=!0);Object.defineProperty(e,c.key,c)}}return function(a,b,c){b&&e(a.prototype,b);c&&e(a,c);return a}}(),xa=/^data:/,
ya=/^data:image\/jpeg;base64,/,ia=void 0,E=function(){function a(k,b){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");this.element=k;this.options=r({},ca,d(b)&&b);this.isImg=this.wheeling=this.limited=this.replaced=this.disabled=this.cropped=this.rotated=this.complete=this.ready=this.loaded=!1;this.originalUrl="";this.previews=this.cropBoxData=this.canvasData=null;this.pointers={};this.init()}wa(a,[{key:"init",value:function(){var a=this.element,e=a.tagName.toLowerCase(),
b=void 0;if(!N(a,"cropper")){K(a,"cropper",this);if("img"===e){this.isImg=!0;this.originalUrl=b=a.getAttribute("src");if(!b)return;b=a.src}else"canvas"===e&&window.HTMLCanvasElement&&(b=a.toDataURL("image/"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgExt,1));this.load(b)}}},{key:"load",value:function(a){var e=this,b=e.options,c=e.element;if(a)if(e.url=a,e.imageData={},b.checkOrientation&&window.ArrayBuffer)if(xa.test(a))ya.test(a)?e.read(qa(a)):e.clone();else{var h=new XMLHttpRequest;h.onerror=function(){e.clone()};
h.onload=function(){e.read(h.response)};b.checkCrossOrigin&&Y(a)&&c.crossOrigin&&(a=Z(a));h.open("get",a);h.responseType="arraybuffer";h.withCredentials="use-credentials"===c.crossOrigin;h.send()}else e.clone()}},{key:"read",value:function(a){var e=this.options,b;b=new DataView(a);var c=b.byteLength,h=void 0,f=void 0,l=void 0,d=f=void 0,g=l=f=void 0,m=f=void 0;if(255===b.getUint8(0)&&216===b.getUint8(1))for(f=2;f<c;){if(255===b.getUint8(f)&&225===b.getUint8(f+1)){l=f;break}f+=1}if(l){f=l+4;l+=10;
c="";m=f;for(f=4+f;m<f;m+=1)c+=ea(b.getUint8(m));"Exif"===c&&(f=b.getUint16(l),!(d=18761===f)&&19789!==f||42!==b.getUint16(l+2,d)||(f=b.getUint32(l+4,d),8<=f&&(g=l+f)))}if(g)for(c=b.getUint16(g,d),m=0;m<c;m+=1)if(f=g+12*m+2,274===b.getUint16(f,d)){f+=8;h=b.getUint16(f,d);aa&&b.setUint16(f,1,d);break}b=h;h=this.imageData;d=0;c=g=1;if(1<b){a=new Uint8Array(a);l=a.length;f="";m=void 0;for(m=0;m<l;m+=1)f+=ea(a[m]);this.url="data:image/jpeg;base64,"+btoa(f);switch(b){case 2:g=-1;break;case 3:d=-180;break;
case 4:c=-1;break;case 5:d=90;c=-1;break;case 6:d=90;break;case 7:d=90;g=-1;break;case 8:d=-90}}e.rotatable&&(h.rotate=d);e.scalable&&(h.scaleX=g,h.scaleY=c);this.clone()}},{key:"clone",value:function(){var a=this.element,e=this.url,b=void 0,c=void 0;this.options.checkCrossOrigin&&Y(e)&&((b=a.crossOrigin)?c=e:(b="anonymous",c=Z(e)));this.crossOrigin=b;this.crossOriginUrl=c;var h=document.createElement("img");b&&(h.crossOrigin=b);h.src=c||e;e=z(this.start,this);b=z(this.stop,this);this.image=h;this.onStart=
e;this.onStop=b;this.isImg?a.complete?this.start():C(a,"load",e):(C(h,"load",e),C(h,"error",b),v(h,"cropper-hide"),a.parentNode.insertBefore(h,a.nextSibling))}},{key:"start",value:function(a){var e=this,b=e.isImg?e.element:e.image;a&&(A(b,"load",e.onStart),A(b,"error",e.onStop));pa(b,function(a,b){r(e.imageData,{naturalWidth:a,naturalHeight:b,aspectRatio:a/b});e.loaded=!0;e.build()})}},{key:"stop",value:function(){var a=this.image;A(a,"load",this.onStart);A(a,"error",this.onStop);S(a);this.image=
null}},{key:"build",value:function(){var a=this,e=a.options,b=a.element,c=a.image;if(a.loaded){a.ready&&a.unbuild();var d=b.parentNode,f=document.createElement("div");f.innerHTML='<div class="cropper-container"><div class="cropper-wrap-box"><div class="cropper-canvas"></div></div><div class="cropper-drag-box"></div><div class="cropper-crop-box"><span class="cropper-view-box"></span><span class="cropper-dashed dashed-h"></span><span class="cropper-dashed dashed-v"></span><span class="cropper-center"></span><span class="cropper-face"></span><span class="cropper-line line-e" data-action="e"></span><span class="cropper-line line-n" data-action="n"></span><span class="cropper-line line-w" data-action="w"></span><span class="cropper-line line-s" data-action="s"></span><span class="cropper-point point-e" data-action="e"></span><span class="cropper-point point-n" data-action="n"></span><span class="cropper-point point-w" data-action="w"></span><span class="cropper-point point-s" data-action="s"></span><span class="cropper-point point-ne" data-action="ne"></span><span class="cropper-point point-nw" data-action="nw"></span><span class="cropper-point point-sw" data-action="sw"></span><span class="cropper-point point-se" data-action="se"></span></div></div>';
var f=H(f,"cropper-container")[0],l=H(f,"cropper-canvas")[0],W=H(f,"cropper-drag-box")[0],p=H(f,"cropper-crop-box")[0],m=H(p,"cropper-face")[0];a.container=d;a.cropper=f;a.canvas=l;a.dragBox=W;a.cropBox=p;a.viewBox=H(f,"cropper-view-box")[0];a.face=m;l.appendChild(c);v(b,"cropper-hidden");d.insertBefore(f,b.nextSibling);a.isImg||G(c,"cropper-hide");a.initPreview();a.bind();e.aspectRatio=Math.max(0,e.aspectRatio)||NaN;e.viewMode=Math.max(0,Math.min(3,Math.round(e.viewMode)))||0;(a.cropped=e.autoCrop)?
e.modal&&v(W,"cropper-modal"):v(p,"cropper-hidden");e.guides||v(H(p,"cropper-dashed"),"cropper-hidden");e.center||v(H(p,"cropper-center"),"cropper-hidden");e.background&&v(f,"cropper-bg");e.highlight||v(m,"cropper-invisible");e.cropBoxMovable&&(v(m,"cropper-move"),K(m,"action","all"));e.cropBoxResizable||(v(H(p,"cropper-line"),"cropper-hidden"),v(H(p,"cropper-point"),"cropper-hidden"));a.setDragMode(e.dragMode);a.render();a.ready=!0;a.setData(e.data);a.completing=setTimeout(function(){g(e.ready)&&
C(b,"ready",e.ready,!0);I(b,"ready");I(b,"crop",a.getData());a.complete=!0},0)}}},{key:"unbuild",value:function(){this.ready&&(this.complete||clearTimeout(this.completing),this.complete=this.ready=!1,this.cropBoxData=this.canvasData=this.containerData=this.initialCropBoxData=this.initialCanvasData=this.initialImageData=null,this.unbind(),this.resetPreview(),this.container=this.canvas=this.dragBox=this.cropBox=this.viewBox=this.previews=null,S(this.cropper),this.cropper=null)}}],[{key:"noConflict",
value:function(){window.Cropper=ia;return a}},{key:"setDefaults",value:function(a){r(ca,d(a)&&a)}}]);return a}();r(E.prototype,{render:function(){this.initContainer();this.initCanvas();this.initCropBox();this.renderCanvas();this.cropped&&this.renderCropBox()},initContainer:function(){var a=this.options,b=this.element,c=this.container,d=this.cropper;v(d,"cropper-hidden");G(b,"cropper-hidden");this.containerData=a={width:Math.max(c.offsetWidth,Number(a.minContainerWidth)||200),height:Math.max(c.offsetHeight,
Number(a.minContainerHeight)||100)};y(d,{width:a.width,height:a.height});v(b,"cropper-hidden");G(d,"cropper-hidden")},initCanvas:function(){var a=this.options.viewMode,b=this.containerData,c=this.imageData,d=90===Math.abs(c.rotate)%180,q=d?c.naturalHeight:c.naturalWidth,h=d?c.naturalWidth:c.naturalHeight,f=q/h,d=b.width,l=b.height;b.height*f>b.width?3===a?d=b.height*f:l=b.width/f:3===a?l=b.width/f:d=b.height*f;q={naturalWidth:q,naturalHeight:h,aspectRatio:f,width:d,height:l};q.left=(b.width-d)/2;
q.top=(b.height-l)/2;q.oldLeft=q.left;q.oldTop=q.top;this.canvasData=q;this.limited=1===a||2===a;this.limitCanvas(!0,!0);this.initialImageData=r({},c);this.initialCanvasData=r({},q)},limitCanvas:function(a,b){var c=this.options,d=c.viewMode,q=this.containerData,h=this.canvasData,f=h.aspectRatio,l=this.cropBoxData,g=this.cropped&&l;if(a){var p=Number(c.minCanvasWidth)||0,c=Number(c.minCanvasHeight)||0;1<d?(p=Math.max(p,q.width),c=Math.max(c,q.height),3===d&&(c*f>p?p=c*f:c=p/f)):0<d&&(p?p=Math.max(p,
g?l.width:0):c?c=Math.max(c,g?l.height:0):g&&(p=l.width,c=l.height,c*f>p?p=c*f:c=p/f));p&&c?c*f>p?c=p/f:p=c*f:p?c=p/f:c&&(p=c*f);h.minWidth=p;h.minHeight=c;h.maxWidth=Infinity;h.maxHeight=Infinity}b&&(d?(f=q.width-h.width,p=q.height-h.height,h.minLeft=Math.min(0,f),h.minTop=Math.min(0,p),h.maxLeft=Math.max(0,f),h.maxTop=Math.max(0,p),g&&this.limited&&(h.minLeft=Math.min(l.left,l.left+(l.width-h.width)),h.minTop=Math.min(l.top,l.top+(l.height-h.height)),h.maxLeft=l.left,h.maxTop=l.top,2===d&&(h.width>=
q.width&&(h.minLeft=Math.min(0,f),h.maxLeft=Math.max(0,f)),h.height>=q.height&&(h.minTop=Math.min(0,p),h.maxTop=Math.max(0,p))))):(h.minLeft=-h.width,h.minTop=-h.height,h.maxLeft=q.width,h.maxTop=q.height))},renderCanvas:function(a){var b=this.canvasData,c=this.imageData,d=c.rotate;if(this.rotated){this.rotated=!1;var q=P({width:c.width,height:c.height,degree:d}),h=q.width/q.height,f=1===c.aspectRatio;if(f||h!==b.aspectRatio){b.left-=(q.width-b.width)/2;b.top-=(q.height-b.height)/2;b.width=q.width;
b.height=q.height;b.aspectRatio=h;b.naturalWidth=c.naturalWidth;b.naturalHeight=c.naturalHeight;if(f&&d%90||d%180)c=P({width:c.naturalWidth,height:c.naturalHeight,degree:d}),b.naturalWidth=c.width,b.naturalHeight=c.height;this.limitCanvas(!0,!1)}}if(b.width>b.maxWidth||b.width<b.minWidth)b.left=b.oldLeft;if(b.height>b.maxHeight||b.height<b.minHeight)b.top=b.oldTop;b.width=Math.min(Math.max(b.width,b.minWidth),b.maxWidth);b.height=Math.min(Math.max(b.height,b.minHeight),b.maxHeight);this.limitCanvas(!1,
!0);b.left=Math.min(Math.max(b.left,b.minLeft),b.maxLeft);b.top=Math.min(Math.max(b.top,b.minTop),b.maxTop);b.oldLeft=b.left;b.oldTop=b.top;y(this.canvas,r({width:b.width,height:b.height},L({translateX:b.left,translateY:b.top})));this.renderImage();this.cropped&&this.limited&&this.limitCropBox(!0,!0);a&&this.output()},renderImage:function(a){var b=this.canvasData,c=this.imageData,d=void 0,q=void 0,h=void 0,q=void 0;c.rotate&&(q=P({width:b.width,height:b.height,degree:c.rotate,aspectRatio:c.aspectRatio},
!0),h=q.width,q=q.height,d={width:h,height:q,left:(b.width-h)/2,top:(b.height-q)/2});r(c,d||{width:b.width,height:b.height,left:0,top:0});y(this.image,r({width:c.width,height:c.height},L(r({translateX:c.left,translateY:c.top},c))));a&&this.output()},initCropBox:function(){var a=this.options,b=a.aspectRatio,a=Number(a.autoCropArea)||.8,c=this.canvasData,d={width:c.width,height:c.height};b&&(c.height*b>c.width?d.height=d.width/b:d.width=d.height*b);this.cropBoxData=d;this.limitCropBox(!0,!0);d.width=
Math.min(Math.max(d.width,d.minWidth),d.maxWidth);d.height=Math.min(Math.max(d.height,d.minHeight),d.maxHeight);d.width=Math.max(d.minWidth,d.width*a);d.height=Math.max(d.minHeight,d.height*a);d.left=c.left+(c.width-d.width)/2;d.top=c.top+(c.height-d.height)/2;d.oldLeft=d.left;d.oldTop=d.top;this.initialCropBoxData=r({},d)},limitCropBox:function(a,b){var c=this.options,d=c.aspectRatio,q=this.containerData,h=this.canvasData,f=this.cropBoxData,l=this.limited;if(a){var g=Number(c.minCropBoxWidth)||0,
c=Number(c.minCropBoxHeight)||0,p=Math.min(q.width,l?h.width:q.width),m=Math.min(q.height,l?h.height:q.height),g=Math.min(g,q.width),c=Math.min(c,q.height);d&&(g&&c?c*d>g?c=g/d:g=c*d:g?c=g/d:c&&(g=c*d),m*d>p?m=p/d:p=m*d);f.minWidth=Math.min(g,p);f.minHeight=Math.min(c,m);f.maxWidth=p;f.maxHeight=m}b&&(l?(f.minLeft=Math.max(0,h.left),f.minTop=Math.max(0,h.top),f.maxLeft=Math.min(q.width,h.left+h.width)-f.width,f.maxTop=Math.min(q.height,h.top+h.height)-f.height):(f.minLeft=0,f.minTop=0,f.maxLeft=q.width-
f.width,f.maxTop=q.height-f.height))},renderCropBox:function(){var a=this.options,b=this.containerData,c=this.cropBoxData;if(c.width>c.maxWidth||c.width<c.minWidth)c.left=c.oldLeft;if(c.height>c.maxHeight||c.height<c.minHeight)c.top=c.oldTop;c.width=Math.min(Math.max(c.width,c.minWidth),c.maxWidth);c.height=Math.min(Math.max(c.height,c.minHeight),c.maxHeight);this.limitCropBox(!1,!0);c.left=Math.min(Math.max(c.left,c.minLeft),c.maxLeft);c.top=Math.min(Math.max(c.top,c.minTop),c.maxTop);c.oldLeft=
c.left;c.oldTop=c.top;a.movable&&a.cropBoxMovable&&K(this.face,"action",c.width===b.width&&c.height===b.height?"move":"all");y(this.cropBox,r({width:c.width,height:c.height},L({translateX:c.left,translateY:c.top})));this.cropped&&this.limited&&this.limitCanvas(!0,!0);this.disabled||this.output()},output:function(){this.preview();this.complete&&I(this.element,"crop",this.getData())}});r(E.prototype,{initPreview:function(){var a=this.options.preview,b=document.createElement("img"),c=this.crossOrigin,
d=c?this.crossOriginUrl:this.url;c&&(b.crossOrigin=c);b.src=d;this.viewBox.appendChild(b);this.image2=b;a&&(this.previews=a=a.querySelector?[a]:document.querySelectorAll(a),m(a,function(a){var b=document.createElement("img");K(a,"preview",{width:a.offsetWidth,height:a.offsetHeight,html:a.innerHTML});c&&(b.crossOrigin=c);b.src=d;for(b.style.cssText='display:block;width:100%;height:auto;min-width:0!important;min-height:0!important;max-width:none!important;max-height:none!important;image-orientation:0deg!important;"';a.firstChild;)a.removeChild(a.firstChild);
a.appendChild(b)}))},resetPreview:function(){m(this.previews,function(a){var b=N(a,"preview");y(a,{width:b.width,height:b.height});a.innerHTML=b.html;U(a,"preview")})},preview:function(){var a=this.imageData,b=this.canvasData,c=this.cropBoxData,d=c.width,q=c.height,h=a.width,f=a.height,l=c.left-b.left-a.left,g=c.top-b.top-a.top;this.cropped&&!this.disabled&&(y(this.image2,r({width:h,height:f},L(r({translateX:-l,translateY:-g},a)))),m(this.previews,function(b){var c=N(b,"preview"),k=c.width,c=c.height,
t=k,m=c,n=1;d&&(n=k/d,m=q*n);q&&m>c&&(n=c/q,t=d*n,m=c);y(b,{width:t,height:m});y(b.getElementsByTagName("img")[0],r({width:h*n,height:f*n},L(r({translateX:-l*n,translateY:-g*n},a))))}))}});r(E.prototype,{bind:function(){var a=this.options,b=this.element,c=this.cropper;g(a.cropstart)&&C(b,"cropstart",a.cropstart);g(a.cropmove)&&C(b,"cropmove",a.cropmove);g(a.cropend)&&C(b,"cropend",a.cropend);g(a.crop)&&C(b,"crop",a.crop);g(a.zoom)&&C(b,"zoom",a.zoom);C(c,fa,this.onCropStart=z(this.cropStart,this));
a.zoomable&&a.zoomOnWheel&&C(c,"wheel mousewheel DOMMouseScroll",this.onWheel=z(this.wheel,this));a.toggleDragModeOnDblclick&&C(c,"dblclick",this.onDblclick=z(this.dblclick,this));C(document,ga,this.onCropMove=z(this.cropMove,this));C(document,ha,this.onCropEnd=z(this.cropEnd,this));a.responsive&&C(window,"resize",this.onResize=z(this.resize,this))},unbind:function(){var a=this.options,b=this.element,c=this.cropper;g(a.cropstart)&&A(b,"cropstart",a.cropstart);g(a.cropmove)&&A(b,"cropmove",a.cropmove);
g(a.cropend)&&A(b,"cropend",a.cropend);g(a.crop)&&A(b,"crop",a.crop);g(a.zoom)&&A(b,"zoom",a.zoom);A(c,fa,this.onCropStart);a.zoomable&&a.zoomOnWheel&&A(c,"wheel mousewheel DOMMouseScroll",this.onWheel);a.toggleDragModeOnDblclick&&A(c,"dblclick",this.onDblclick);A(document,ga,this.onCropMove);A(document,ha,this.onCropEnd);a.responsive&&A(window,"resize",this.onResize)}});r(E.prototype,{resize:function(){var a=this.options,b=this.container,c=this.containerData,d=Number(a.minContainerWidth)||200,q=
Number(a.minContainerHeight)||100;if(!this.disabled&&c.width!==d&&c.height!==q){var h=b.offsetWidth/c.width;if(1!==h||b.offsetHeight!==c.height){var f=void 0,l=void 0;a.restore&&(f=this.getCanvasData(),l=this.getCropBoxData());this.render();a.restore&&(this.setCanvasData(m(f,function(a,b){f[b]=a*h})),this.setCropBoxData(m(l,function(a,b){l[b]=a*h})))}}},dblclick:function(){this.disabled||"none"===this.options.dragMode||this.setDragMode(B(this.dragBox,"cropper-crop")?"move":"crop")},wheel:function(a){var b=
this;a=O(a);var c=Number(b.options.wheelZoomRatio)||.1,d=1;b.disabled||(a.preventDefault(),b.wheeling||(b.wheeling=!0,setTimeout(function(){b.wheeling=!1},50),a.deltaY?d=0<a.deltaY?1:-1:a.wheelDelta?d=-a.wheelDelta/120:a.detail&&(d=0<a.detail?1:-1),b.zoom(-d*c,a)))},cropStart:function(a){if(!this.disabled){var b=this.options,c=this.pointers;a=O(a);var d=void 0;a.changedTouches?m(a.changedTouches,function(a){c[a.identifier]=Q(a)}):c[a.pointerId||0]=Q(a);d=1<Object.keys(c).length&&b.zoomable&&b.zoomOnTouch?
"zoom":N(a.target,"action");va.test(d)&&!1!==I(this.element,"cropstart",{originalEvent:a,action:d})&&(a.preventDefault(),this.action=d,this.cropping=!1,"crop"===d&&(m(c,function(a){a.startX=changeValueForZoom(a.startX,KMINIPHOTOTOP.G_CURRKMINIPHOTO);a.startY=changeValueForZoom(a.startY,KMINIPHOTOTOP.G_CURRKMINIPHOTO);a.endX=changeValueForZoom(a.endX,KMINIPHOTOTOP.G_CURRKMINIPHOTO);a.endY=changeValueForZoom(a.endY,KMINIPHOTOTOP.G_CURRKMINIPHOTO)}),this.cropping=!0,v(this.dragBox,"cropper-modal")))}},
cropMove:function(a){var b=this.action;if(!this.disabled&&b){var c=this.pointers;a=O(a);a.preventDefault();!1!==I(this.element,"cropmove",{originalEvent:a,action:b})&&(a.changedTouches?m(a.changedTouches,function(a){r(c[a.identifier],Q(a,!0))}):r(c[a.pointerId||0],Q(a,!0)),this.change(a))}},cropEnd:function(a){if(!this.disabled){var b=this.action,c=this.pointers;a=O(a);a.changedTouches?m(a.changedTouches,function(a){delete c[a.identifier]}):delete c[a.pointerId||0];b&&(a.preventDefault(),Object.keys(c).length||
(this.action=""),this.cropping&&(this.cropping=!1,J(this.dragBox,"cropper-modal",this.cropped&&this.options.modal)),I(this.element,"cropend",{originalEvent:a,action:b}))}}});r(E.prototype,{change:function(a){var b=this.containerData,c=this.canvasData,d=this.cropBoxData,g=this.options.aspectRatio,h=this.action,f=d.width,l=d.height,n=d.left,p=d.top,y=n+f,r=p+l,v=0,u=0,z=b.width,F=b.height,D=!0,w=void 0;!g&&a.shiftKey&&(g=f&&l?f/l:1);this.limited&&(v=d.minLeft,u=d.minTop,z=v+Math.min(b.width,c.width,
c.left+c.width),F=u+Math.min(b.height,c.height,c.top+c.height));var b=this.pointers,c=b[Object.keys(b)[0]],B=c.endX-c.startX,A=c.endY-c.startY,w=changeValueForZoom(B,KMINIPHOTOTOP.G_CURRKMINIPHOTO),x=changeValueForZoom(A,KMINIPHOTOTOP.G_CURRKMINIPHOTO);switch(h){case "all":n+=w;p+=x;break;case "e":if(0<=w&&(y>=z||g&&(p<=u||r>=F))){D=!1;break}y+w>z&&(w=z-y);f+=w;g&&(l=f/g,p-=w/g/2);0>f&&(h="w",f=0);break;case "n":if(0>=x&&(p<=u||g&&(n<=v||y>=z))){D=!1;break}p+x<u&&(x=u-p);l-=x;p+=x;g&&(f=l*g,n+=x*
g/2);0>l&&(h="s",l=0);break;case "w":if(0>=w&&(n<=v||g&&(p<=u||r>=F))){D=!1;break}n+w<v&&(w=v-n);f-=w;n+=w;g&&(l=f/g,p+=w/g/2);0>f&&(h="e",f=0);break;case "s":if(0<=x&&(r>=F||g&&(n<=v||y>=z))){D=!1;break}r+x>F&&(x=F-r);l+=x;g&&(f=l*g,n-=x*g/2);0>l&&(h="n",l=0);break;case "ne":if(g){if(0>=x&&(p<=u||y>=z)){D=!1;break}l-=x;p+=x;f=l*g}else 0<=w?y<z?f+=w:0>=x&&p<=u&&(D=!1):f+=w,0>=x?p>u&&(l-=x,p+=x):(l-=x,p+=x);0>f&&0>l?(h="sw",f=l=0):0>f?(h="nw",f=0):0>l&&(h="se",l=0);break;case "nw":if(g){if(0>=x&&(p<=
u||n<=v)){D=!1;break}l-=x;p+=x;f=l*g;n+=x*g}else 0>=w?n>v?(f-=w,n+=w):0>=x&&p<=u&&(D=!1):(f-=w,n+=w),0>=x?p>u&&(l-=x,p+=x):(l-=x,p+=x);0>f&&0>l?(h="se",f=l=0):0>f?(h="ne",f=0):0>l&&(h="sw",l=0);break;case "sw":if(g){if(0>=w&&(n<=v||r>=F)){D=!1;break}f-=w;n+=w;l=f/g}else 0>=w?n>v?(f-=w,n+=w):0<=x&&r>=F&&(D=!1):(f-=w,n+=w),0<=x?r<F&&(l+=x):l+=x;0>f&&0>l?(h="ne",f=l=0):0>f?(h="se",f=0):0>l&&(h="nw",l=0);break;case "se":if(g){if(0<=w&&(y>=z||r>=F)){D=!1;break}f+=w;l=f/g}else 0<=w?y<z?f+=w:0<=x&&r>=F&&
(D=!1):f+=w,0<=x?r<F&&(l+=x):l+=x;0>f&&0>l?(h="nw",f=l=0):0>f?(h="sw",f=0):0>l&&(h="ne",l=0);break;case "move":this.move(B,A);D=!1;break;case "zoom":this.zoom(sa(b),a);D=!1;break;case "crop":if(!B||!A){D=!1;break}w=X(this.cropper);n=c.startX-w.left;p=c.startY-w.top;f=d.minWidth;l=d.minHeight;0<B?h=0<A?"se":"ne":0>B&&(n-=f,h=0<A?"sw":"nw");0>A&&(p-=l);this.cropped||(G(this.cropBox,"cropper-hidden"),this.cropped=!0,this.limited&&this.limitCropBox(!0,!0))}D&&(1!=getKMINIPHOTOWINoomValue(KMINIPHOTOTOP.G_CURRKMINIPHOTO)?
(d.width=parseFloat(f),d.height=parseFloat(l)):(d.width=parseInt(f,10),d.height=parseInt(l,10)),d.left=n,d.top=p,this.action=h,this.renderCropBox());m(b,function(a){a.startX=a.endX;a.startY=a.endY})}});r(E.prototype,{crop:function(){this.ready&&!this.disabled&&(this.cropped||(this.cropped=!0,this.limitCropBox(!0,!0),this.options.modal&&v(this.dragBox,"cropper-modal"),G(this.cropBox,"cropper-hidden")),this.setCropBoxData(this.initialCropBoxData));return this},reset:function(){this.ready&&!this.disabled&&
(this.imageData=r({},this.initialImageData),this.canvasData=r({},this.initialCanvasData),this.cropBoxData=r({},this.initialCropBoxData),this.renderCanvas(),this.cropped&&this.renderCropBox());return this},clear:function(){this.cropped&&!this.disabled&&(r(this.cropBoxData,{left:0,top:0,width:0,height:0}),this.cropped=!1,this.renderCropBox(),this.limitCanvas(!0,!0),this.renderCanvas(),G(this.dragBox,"cropper-modal"),v(this.cropBox,"cropper-hidden"));return this},replace:function(a,b){!this.disabled&&
a&&(this.isImg&&(this.element.src=a),b?(this.url=a,this.image.src=a,this.ready&&(this.image2.src=a,m(this.previews,function(b){b.getElementsByTagName("img")[0].src=a}))):(this.isImg&&(this.replaced=!0),this.options.data=null,this.load(a)));return this},enable:function(){this.ready&&(this.disabled=!1,G(this.cropper,"cropper-disabled"));return this},disable:function(){this.ready&&(this.disabled=!0,v(this.cropper,"cropper-disabled"));return this},destroy:function(){var a=this.element,b=this.image;this.loaded?
(this.isImg&&this.replaced&&(a.src=this.originalUrl),this.unbuild(),G(a,"cropper-hidden")):this.isImg?A(a,"load",this.onStart):b&&S(b);U(a,"cropper");return this},move:function(a,b){var d=this.canvasData;return this.moveTo(c(a)?a:d.left+Number(a),c(b)?b:d.top+Number(b))},moveTo:function(b,d){var g=this.canvasData,m=!1;c(d)&&(d=b);b=Number(b);d=Number(d);this.ready&&!this.disabled&&this.options.movable&&(a(b)&&(g.left=b,m=!0),a(d)&&(g.top=d,m=!0),m&&this.renderCanvas(!0));return this},zoom:function(a,
b){var c=this.canvasData;a=Number(a);return this.zoomTo(c.width*(0>a?1/(1-a):1+a)/c.naturalWidth,b)},zoomTo:function(a,b){var c=this.options,d=this.canvasData,g=d.width,h=d.height,f=d.naturalWidth,l=d.naturalHeight;a=Number(a);if(0<=a&&this.ready&&!this.disabled&&c.zoomable){c=f*a;l*=a;if(!1===I(this.element,"zoom",{originalEvent:b,oldRatio:g/f,ratio:c/f}))return this;if(b){var m=this.pointers,f=X(this.cropper),m=m&&Object.keys(m).length?ua(m):{pageX:b.pageX,pageY:b.pageY};d.left-=(m.pageX-f.left-
d.left)/g*(c-g);d.top-=(m.pageY-f.top-d.top)/h*(l-h)}else d.left-=(c-g)/2,d.top-=(l-h)/2;d.width=c;d.height=l;this.renderCanvas(!0)}return this},rotate:function(a){return this.rotateTo((this.imageData.rotate||0)+Number(a))},rotateTo:function(b){b=Number(b);a(b)&&this.ready&&!this.disabled&&this.options.rotatable&&(this.imageData.rotate=b%360,this.rotated=!0,this.renderCanvas(!0));return this},scale:function(b,d){var g=this.imageData,m=!1;c(d)&&(d=b);b=Number(b);d=Number(d);this.ready&&!this.disabled&&
this.options.scalable&&(a(b)&&(g.scaleX=b,m=!0),a(d)&&(g.scaleY=d,m=!0),m&&this.renderImage(!0));return this},scaleX:function(b){var c=this.imageData.scaleY;return this.scale(b,a(c)?c:1)},scaleY:function(b){var c=this.imageData.scaleX;return this.scale(a(c)?c:1,b)},getData:function(a){var b=this.options,c=this.imageData,d=this.canvasData,g=this.cropBoxData,h=void 0,f=void 0;this.ready&&this.cropped?(f={x:g.left-d.left,y:g.top-d.top,width:g.width,height:g.height},h=c.width/c.naturalWidth,m(f,function(b,
c){b/=h;f[c]=a?Math.round(b):b})):f={x:0,y:0,width:0,height:0};b.rotatable&&(f.rotate=c.rotate||0);b.scalable&&(f.scaleX=c.scaleX||1,f.scaleY=c.scaleY||1);return f},setData:function(b){var c=this.options,m=this.imageData,n=this.canvasData,q={},h=void 0,f=void 0,l=void 0;g(b)&&(b=b.call(this.element));this.ready&&!this.disabled&&d(b)&&(c.rotatable&&a(b.rotate)&&b.rotate!==m.rotate&&(m.rotate=b.rotate,this.rotated=h=!0),c.scalable&&(a(b.scaleX)&&b.scaleX!==m.scaleX&&(m.scaleX=b.scaleX,f=!0),a(b.scaleY)&&
b.scaleY!==m.scaleY&&(m.scaleY=b.scaleY,f=!0)),h?this.renderCanvas():f&&this.renderImage(),l=m.width/m.naturalWidth,a(b.x)&&(q.left=b.x*l+n.left),a(b.y)&&(q.top=b.y*l+n.top),a(b.width)&&(q.width=b.width*l),a(b.height)&&(q.height=b.height*l),this.setCropBoxData(q));return this},getContainerData:function(){return this.ready?this.containerData:{}},getImageData:function(){return this.loaded?this.imageData:{}},getCanvasData:function(){var a=this.canvasData,b={};this.ready&&m("left top width height naturalWidth naturalHeight".split(" "),
function(c){b[c]=a[c]});return b},setCanvasData:function(b){var c=this.canvasData,m=c.aspectRatio;g(b)&&(b=b.call(this.element));this.ready&&!this.disabled&&d(b)&&(a(b.left)&&(c.left=b.left),a(b.top)&&(c.top=b.top),a(b.width)?(c.width=b.width,c.height=b.width/m):a(b.height)&&(c.height=b.height,c.width=b.height*m),this.renderCanvas(!0));return this},getCropBoxData:function(){var a=this.cropBoxData,b=void 0;this.ready&&this.cropped&&(b={left:a.left,top:a.top,width:a.width,height:a.height});return b||
{}},setCropBoxData:function(b){var c=this.cropBoxData,m=this.options.aspectRatio,n=void 0,q=void 0;g(b)&&(b=b.call(this.element));this.ready&&this.cropped&&!this.disabled&&d(b)&&(a(b.left)&&(c.left=b.left),a(b.top)&&(c.top=b.top),a(b.width)&&b.width!==c.width&&(n=!0,c.width=b.width),a(b.height)&&b.height!==c.height&&(q=!0,c.height=b.height),m&&(n?c.height=parseInt(c.width/m,10):q&&(c.width=parseInt(c.height*m,10))),this.renderCropBox());return this},getCroppedCanvas:function(a){if(!this.ready||!window.HTMLCanvasElement)return null;
d(a)||(a={});if(!this.cropped)return ba(this.image,this.imageData,a);var b=this.getData(),c=b.width,g=b.height,m=c/g,h=void 0,f=void 0,l=void 0;d(a)&&(h=a.width,f=a.height,h?(f=h/m,l=h/c):f&&(h=f*m,l=f/g));var h=Math.floor(h||c),n=Math.floor(f||g),f=document.createElement("canvas"),m=f.getContext("2d");f.width=h;f.height=n;a.fillColor&&(m.fillStyle=a.fillColor,m.fillRect(0,0,h,n));var p=ba(this.image,this.imageData,a),h=p.width,n=p.height,y=this.canvasData,p=[p],r=b.x+y.naturalWidth*(Math.abs(b.scaleX||
1)-1)/2,b=b.y+y.naturalHeight*(Math.abs(b.scaleY||1)-1)/2,v=y=void 0,u=void 0,z=void 0,A=void 0,B=void 0;r<=-c||r>h?A=u=y=r=0:0>=r?(u=-r,r=0,A=y=Math.min(h,c+r)):r<=h&&(u=0,A=y=Math.min(c,h-r));0>=y||b<=-g||b>n?B=z=v=b=0:0>=b?(z=-b,b=0,B=v=Math.min(n,g+b)):b<=n&&(z=0,B=v=Math.min(g,n-b));p.push(Math.floor(r),Math.floor(b),Math.floor(y),Math.floor(v));l&&(u*=l,z*=l,A*=l,B*=l);0<A&&0<B&&p.push(Math.floor(u),Math.floor(z),Math.floor(A),Math.floor(B));m.imageSmoothingEnabled=!!a.imageSmoothingEnabled;
a.imageSmoothingQuality&&(m.imageSmoothingQuality=a.imageSmoothingQuality);m.drawImage.apply(m,ta(p));return f},setAspectRatio:function(a){var b=this.options;this.disabled||c(a)||(b.aspectRatio=Math.max(0,a)||NaN,this.ready&&(this.initCropBox(),this.cropped&&this.renderCropBox()));return this},setDragMode:function(a){var b=this.options,c=this.dragBox,d=this.face,g=void 0,h=void 0;this.loaded&&!this.disabled&&(g="crop"===a,h=b.movable&&"move"===a,a=g||h?a:"none",K(c,"action",a),J(c,"cropper-crop",
g),J(c,"cropper-move",h),b.cropBoxMovable||(K(d,"action",a),J(d,"cropper-crop",g),J(d,"cropper-move",h)));return this}});"undefined"!==typeof window&&(ia=window.Cropper,window.Cropper=E);return E});(function(a){function c(a){a.webkitImageSmoothingEnabled=!1;a.mozImageSmoothingEnabled=!1;a.msImageSmoothingEnabled=!1;a.imageSmoothingEnabled=!1;return a}function b(a,b,n){b=b||{};this.image=a;this.setAmount(b.amount);var u=function(){this.imageUrl=a.src;this.width=this.image.width;this.height=0==this.image.height?Number(this.image.getAttribute("height")):this.image.height;this.canvas=document.createElement("canvas");this.canvas.width=this.width;this.canvas.height=this.height;this.canvas.style.cssText=
"image-rendering: optimizeSpeed;image-rendering: -moz-crisp-edges;image-rendering: -o-crisp-edges;image-rendering: -webkit-crisp-edges;image-rendering: crisp-edges;image-rendering: -webkit-optimize-contrast;image-rendering: pixelated; -ms-interpolation-mode: nearest-neighbor;";this.canvas.style.display="none";this.ctx=this.canvas.getContext("2d");this.ctx=c(this.ctx);this.image.parentNode.appendChild(this.canvas,this.image);this.image.onload=null;this.pixelImage=new Image;this.pixelImage.onload=function(){this.ready=
!0;n()}.bind(this);this.pixelImage.src=this.imageUrl}.bind(this),m=setInterval(function(){a.complete&&(clearInterval(m),u())},100);return this}window.URL=window.URL||window.webkitURL||window.mozURL;b.prototype.setAmount=function(a){this.amount=1-(a||0);return this};b.prototype.setWidth=function(a){var b=this.height/this.width*a;this.width=a;this.height=b;this.canvas.width=this.width;this.canvas.height=this.height;this.ctx=c(this.ctx);return this};b.prototype.render=function(){if(!this.ready)return this;
var a=this.width*(0>=this.amount?.01:this.amount),b=this.height*(0>=this.amount?.01:this.amount);this.ctx.clearRect(0,0,this.width,this.height);var c=document.createElement("canvas");c.width=this.width;c.height=this.height;c.getContext("2d").drawImage(this.pixelImage,0,0,a,b);this.ctx.clearRect(0,0,this.width,this.height);this.ctx.drawImage(c,0,0,a,b,0,0,this.width,this.height);this.image.src=this.canvas.toDataURL("image/png");return this};"undefined"!==typeof exports?("undefined"!==typeof module&&
module.exports&&(exports=module.exports=b),exports.pixelate=b):"function"===typeof define&&define.amd?define([],function(){return b}):a.Pixelate=b})(this);var console=window&&window.console?window.console:{log:function(){}},KMINIPHOTOTOP=parent,G_CURRCROPTYPE="crop",G_CURRCROPMODE=0;setMiniPhotoWindow();setMiniPhotoDocument();KMINIPHOTOTOP.KMINIPHOTO=parent.KMINIPHOTO;parent.KMINIPHOTOTOP=KMINIPHOTOTOP;KMINIPHOTOTOP.KMINIPHOTO.util.overrideFn(window);Array.prototype.indexOf||(Array.prototype.indexOf=function(a,c){c=c||0;for(var b=this.length;c<b;){if(this[c]===a)return c;++c}return-1});
String.prototype.insertAt||(String.prototype.insertAt=function(a,c){return this.substr(0,a)+c+this.substr(a)});String.prototype.replaceAt||(String.prototype.replaceAt=function(a,c){return this.substr(0,a)+c+this.substr(a+c.length)});
function setMiniPhotoWindow(){try{topURL=top.location.href,"undefined"==typeof topURL?(KMINIPHOTOTOP.KMINIPHOTOWIN=parent,KMINIPHOTOTOP.IsCrossDomain=!0):(KMINIPHOTOTOP.KMINIPHOTOWIN=parent,KMINIPHOTOTOP.IsCrossDomain=!1)}catch(a){KMINIPHOTOTOP.KMINIPHOTOWIN=parent,KMINIPHOTOTOP.IsCrossDomain=!0}}
function setMiniPhotoDocument(){try{topURL=top.location.href,"undefined"==typeof topURL?(KMINIPHOTOTOP.KMINIPHOTODOC=parent.document,KMINIPHOTOTOP.IsCrossDomain=!0):(KMINIPHOTOTOP.KMINIPHOTODOC=parent.document,KMINIPHOTOTOP.IsCrossDomain=!1)}catch(a){KMINIPHOTOTOP.KMINIPHOTODOC=parent.document,KMINIPHOTOTOP.IsCrossDomain=!0}}function raonk_frame_loaded_event(a,c,b){_raonk_miniphoto=new K_MiniPhoto(a,c,b);_raonk_miniphoto.start(c,_raonk_miniphoto)}
function K_MiniPhoto(a,c,b){this._config=c;this._frame=b;this.frameWin=window;this.ID=a;KMINIPHOTOTOP.KMINIPHOTO.RAONKMULTIPLE[b.frameID]=this;KMINIPHOTOTOP.G_CURRKMINIPHOTO=this;this.currDegree=0;this.flipY=this.flipX=!1;this.initImgHeight=this.initImgWidth=this.initImg=this.cropper=null;this.frameStatus=this.initImgExt="";this.arrBlobUrl=[];try{"function"===typeof KMINIPHOTOTOP.KMINIPHOTOWIN.KMINIPHOTO_OnLanguageDefinition&&KMINIPHOTOTOP.KMINIPHOTOWIN.KMINIPHOTO_OnLanguageDefinition(a,KMiniPhoto_Lang)}catch(d){"undefined"!=
typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}}
K_MiniPhoto.prototype={init:function(a){KMINIPHOTOTOP.KMINIPHOTO.util._setKMiniPhoto(a)},reset:function(a){KMINIPHOTOTOP.KMINIPHOTO.util._setKMiniPhoto(a)},start:function(a,c){var b=c._config;getDialogDocument();setZoomValueToBody(document,c);var d=parseInt(b.height);-1<b.height.indexOf("%")&&(d=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(KMINIPHOTOTOP.KMINIPHOTODOC.getElementById("kminiphoto_holder_"+c.ID)),d=d.bottom-d.top);var g=parseInt(b.width);-1<b.width.indexOf("%")&&(g=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(KMINIPHOTOTOP.KMINIPHOTODOC.getElementById("kminiphoto_holder_"+
c.ID)),g=g.right-g.left);getAreaSize(d,b,c);b=""+('<div id="miniPhoto_holder" class="wrap" style="width: '+(g-2)+'px;">')+'<div id="miniPhoto_header" class="miniPhoto_header">';b+="<h3></h3>";b+='<div class="btn-right">';b+='<a id="btn_fullscreen" href="javascript:;" class="K_mini_photo_maximization" title="'+KMiniPhoto_Lang.fullScreen+'"><span class="blind"></span></a><a href="javascript:;" class="K_mini_photo_close" title="'+KMiniPhoto_Lang.close+'"><span class="blind"></span></a>';b+="</div>";
b+="</div>";b+='<div class="miniPhoto_toolbar">';b+='<input id="open_file" type="file" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff,.tif" style="display:none;"/>';b+='<a id="btn_open" href="javascript:;" class="btn-function"><span class="img-open"></span><em>'+KMiniPhoto_Lang.open+"</em></a>";b+='<i class="vertical"></i>';b+='<a id="btn_undo" href="javascript:;" class="btn-do" title="'+KMiniPhoto_Lang.undo+'"><i class="undo deact-u"></i><p class="blind"></p></a>';b+='<a id="btn_redo" href="javascript:;" class="btn-do" title="'+
KMiniPhoto_Lang.redo+'"><i class="redo deact-r"></i><p class="blind"></p></a>';b+='<i class="vertical"></i>';b+='<a id="btn_crop" href="javascript:;" class="btn-function"><span class="img-crop"></span><em>'+KMiniPhoto_Lang.crop+"</em></a>";b+='<ul id="crop_tools_area" class="off">';b+='<li class="" title="Free"><a id="crop_ratio_0" href="javascript:;"><span class="img-ratio-free"></span><em>Free</em></a></li>';b+='<li class="" title="4:3"><a id="crop_ratio_1" href="javascript:;"><span class="img-ratio-4-3"></span><em>4:3</em></a></li>';
b+='<li class="" title="16:9"><a id="crop_ratio_2" href="javascript:;"><span class="img-ratio-16-9"></span><em>16:9</em></a></li>';b+='<li class="" title="1:1"><a id="crop_ratio_3" href="javascript:;"><span class="img-ratio-1-1"></span><em>1:1</em></a></li>';b+='<li class="" title="2:3"><a id="crop_ratio_4" href="javascript:;"><span class="img-ratio-2-3"></span><em>2:3</em></a></li>';b+='<li class="" title="3:4"><a id="crop_ratio_5" href="javascript:;"><span class="img-ratio-3-4"></span><em>3:4</em></a></li>';
b+='<li class="btnForCrop"><a id="crop_ok" href="javascript:;"><span class="btn-apply" title="'+KMiniPhoto_Lang.cropOk+'"></span><p class="blind"></p></a></li>';b+='<li class="btnForCrop"><a id="crop_cancel" href="javascript:;"><span class="btn-cancel" title="'+KMiniPhoto_Lang.cropCancel+'"></span><p class="blind"></p></a></li>';b+="</ul>";b+='<a id="btn_mosaic" href="javascript:;" class="btn-function"><span class="img-mosaic"></span><em>'+KMiniPhoto_Lang.mosaic+"</em></a>";b+='<ul id="mosaic_tools_area" class="off">';
b+='<li class="" style="text-align:center;"><input id="mosaic_slider" class="" type="range" min="0" max="100" value="80"><em id="mosaic_percent" style="line-height: 4.2;">80%</em></li>';b+='<li class="" title="Free"><a id="mosaic_ratio_0" href="javascript:;"><span class="img-ratio-free"></span><em>Free</em></a></li>';b+='<li class="" title="4:3"><a id="mosaic_ratio_1" href="javascript:;"><span class="img-ratio-4-3"></span><em>4:3</em></a></li>';b+='<li class="" title="16:9"><a id="mosaic_ratio_2" href="javascript:;"><span class="img-ratio-16-9"></span><em>16:9</em></a></li>';
b+='<li class="" title="1:1"><a id="mosaic_ratio_3" href="javascript:;"><span class="img-ratio-1-1"></span><em>1:1</em></a></li>';b+='<li class="" title="2:3"><a id="mosaic_ratio_4" href="javascript:;"><span class="img-ratio-2-3"></span><em>2:3</em></a></li>';b+='<li class="" title="3:4"><a id="mosaic_ratio_5" href="javascript:;"><span class="img-ratio-3-4"></span><em>3:4</em></a></li>';b+='<li class="btnForCrop"><a id="mosaic_ok" href="javascript:;"><span class="btn-apply" title="'+KMiniPhoto_Lang.mosaicOk+
'"></span><p class="blind"></p></a></li>';b+='<li class="btnForCrop"><a id="mosaic_cancel" href="javascript:;"><span class="btn-cancel" title="'+KMiniPhoto_Lang.mosaicCancel+'"></span><p class="blind"></p></a></li>';b+="</ul>";b+='<a id="img_rotate_l" href="javascript:;" class="btn-function" title="'+KMiniPhoto_Lang.rotate_l_detail+'"><span class="img-rotationL"></span><em>'+KMiniPhoto_Lang.rotate_l+"</em></a>";b+='<a id="img_rotate_r" href="javascript:;" class="btn-function" title="'+KMiniPhoto_Lang.rotate_r_detail+
'"><span class="img-rotationR"></span><em>'+KMiniPhoto_Lang.rotate_r+"</em></a>";b+='<a id="img_flip_h" href="javascript:;" class="btn-function" title="'+KMiniPhoto_Lang.flip_x_detail+'"><span class="img-flipV"></span><em>'+KMiniPhoto_Lang.flip_x+"</em></a>";b+='<a id="img_flip_v" href="javascript:;" class="btn-function" title="'+KMiniPhoto_Lang.flip_y_detail+'"><span class="img-flipH"></span><em>'+KMiniPhoto_Lang.flip_y+"</em></a>";b+='<div class="buttonArea">';b+='<a id="btn_apply" href="javascript:;" class="btnApply" title="'+
KMiniPhoto_Lang.apply+'"><span>'+KMiniPhoto_Lang.apply+'</span></a><a id="btn_reset" href="javascript:;" class="btnCancel" title="'+KMiniPhoto_Lang.reset+'"><span>'+KMiniPhoto_Lang.reset+"</span></a>";b+="</div>";b+="</div>";b+="<table>";b+="<tbody>";b+='<tr class="imageArea"><td><span id="span_processing" class="RAONK_photo_loading_img" style="display:none;">Processing...</span><div id="miniPhoto_image" style="height:'+c.areaSize.imageAreaHeight+'px; border:0; overflow:auto;"><div style="position:relative; background-image:url(\'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAAA3NCSVQICAjb4U/gAAAABlBMVEXMzMz////TjRV2AAAACXBIWXMAAArrAAAK6wGCiw1aAAAAHHRFWHRTb2Z0d2FyZQBBZG9iZSBGaXJld29ya3MgQ1M26LyyjAAAABFJREFUCJlj+M/AgBVhF/0PAH6/D/HkDxOGAAAAAElFTkSuQmCC\')"></div></div></td></tr>';
b+='<tr class="sizeArea">';b+="<td>";b+='<div class="t-l" style="display:none;">';b+="<span>"+KMiniPhoto_Lang.current_size+"</span>";b+='<em id="crop_box_size">0 x 0 px</em>';b+="</div>";b+='<div class="t-r">';b+='<span class="hhh">'+KMiniPhoto_Lang.original_size+"</span>";b+='<em id="original_size">0 x 0 px</em>';b+="</div>";b+="</td>";b+="</tr>";b+="</tbody>";b+="</table>";b+="</div>";b+="</div>";document.body.style.overflow="hidden";document.body.innerHTML=b;setPage(c)},_raonkCommands:function(a,
c,b,d){G_LAST_CMD=c},_setLazyLoadFrame:function(a){"0"==KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.hideContextMenu&&KMINIPHOTO_CONTEXT._create(a)}};
function setPage(a){KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_header_"+a.ID).getElementsByTagName("h3")[0].innerHTML=KMiniPhoto_Lang.title;KMINIPHOTOTOP.document.getElementById("btn_fullscreen_"+a.ID).title=KMiniPhoto_Lang.fullScreen;KMINIPHOTOTOP.document.getElementById("btn_close_"+a.ID).title=KMiniPhoto_Lang.close;setImageArea();KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(window,"resize",function(){setZoomValueToBody(document,a)});try{"function"===typeof a._config.creationCompleteEvent&&
a._config.creationCompleteEvent(a.ID)}catch(c){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}}
function loadImage(a){null==a.src?(a.isInit&&setEvent(),displayOriginalSize()):(displayProcessing(!0),setTimeout(function(){var c=document.getElementById("miniPhoto_image").firstChild;c&&(c.style.width="0px",c.style.height="0px");c.innerHTML="";KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage=null;KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage=void 0;KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree=0;var b=new Image;b.style.display="none";c.appendChild(b);var d=document.createElement("canvas");d.id="image_canvas";c.appendChild(d);
b.crossOrigin="anonymous";b.onerror=function(){try{var a={strType:"ImageLoad",strCode:"C201",strMessage:"Error load image"};if("function"===typeof DEXTTOP.G_CURREDITOR._config.event.onError)DEXTTOP.G_CURREDITOR._config.event.onError(DEXTTOP.G_CURREDITOR.ID,a);else"function"===typeof DEXTTOP.DEXTWIN.dext_editor_on_error_event?DEXTTOP.DEXTWIN.dext_editor_on_error_event(DEXTTOP.G_CURREDITOR.ID,a):alert(a.strMessage)}catch(b){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}fn_close()};b.onload=
function(){KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree=0;KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipX=!1;KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipY=!1;KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage=b;var c,n,u=b.naturalWidth,m=b.naturalHeight;c=a.width&&""!=a.width?a.width:u;n=a.height&&""!=a.height?a.height:m;var r=KMINIPHOTOTOP.G_CURREDITOR._config.maxImageWidthSize,z=KMINIPHOTOTOP.G_CURREDITOR._config.maxImageHeightSize,y=KMINIPHOTOTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.msg.alert_exec_iamgesize;if(0!=r&&r<c)y+=KMINIPHOTOTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.msg.alert_width.replace("{0}",
r),alert(y),document.getElementById("image_canvas").parentNode.removeChild(document.getElementById("image_canvas")),displayProcessing(!1);else if(0!=z&&z<n)y+=KMINIPHOTOTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.msg.alert_height.replace("{0}",z),alert(y),document.getElementById("image_canvas").parentNode.removeChild(document.getElementById("image_canvas")),displayProcessing(!1);else{d.width=parseInt(c,10);d.height=parseInt(n,10);d.parentNode.style.width=d.width+"px";d.parentNode.style.height=d.height+
"px";d.getContext("2d").drawImage(b,0,0,u,m,0,0,d.width,d.height);b.style.display="none";setCanvasPostionCenter();a.isInit?(setEvent(),G_HISTORY.reset(),KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImg=b,KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgWidth=a.width,KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgHeight=a.height,c=d.toDataURL("image/"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgExt,1),loadImage({src:c,isResized:!0})):a.isResized&&(KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImg=b);a.isOpen&&(G_HISTORY.reset(),KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImg=
b,KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgWidth=b.naturalWidth,KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgHeight=b.naturalHeight);displayProcessing(!1);try{b=void 0}catch(B){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}}};0==a.src.indexOf("blob")&&KMINIPHOTOTOP.G_CURRKMINIPHOTO.arrBlobUrl.push(a.src);c=document.getElementById("open_file");c.value="";KMINIPHOTOTOP.KMINIPHOTO.browser.ie&&10==KMINIPHOTOTOP.KMINIPHOTO.browser.ieVersion&&(c.type="text",c.type="file");b.src=a.src},50))}
function displayOriginalSize(){var a=document.getElementById("original_size"),c=document.getElementById("image_canvas");a.innerHTML=c?c.width+" x "+c.height+" px":"0 x 0 px"}function getDialogWindow(){var a=KMINIPHOTOTOP.window;null!=KMINIPHOTOTOP.G_CURRKMINIPHOTO.dialogWindow&&(a=KMINIPHOTOTOP.G_CURRKMINIPHOTO.dialogWindow);return a}
function getDialogDocument(){var a=KMINIPHOTOTOP.window.document;null!=KMINIPHOTOTOP.G_CURRKMINIPHOTO.dialogWindow&&(a=KMINIPHOTOTOP.G_CURRKMINIPHOTO.dialogWindow.document);return a}function getAreaSize(a,c,b){b.areaSize={headerHeight:30,toolHeight:56,imageAreaHeight:a-30-56-20-2,footerHeight:20}}
function setImageArea(){var a=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(document.getElementById("miniPhoto_image").parentNode),a=a.right-a.left,c=document.getElementById("miniPhoto_image");c.style.width=a+"px";c.style.height=KMINIPHOTOTOP.G_CURRKMINIPHOTO.areaSize.imageAreaHeight+"px"}
function setCanvasPostionCenter(){var a=document.getElementById("image_canvas");if(a){var c=a.parentNode.parentNode,b;c.clientWidth?(b=c.clientWidth,c=c.clientHeight):(c=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(c),b=c.width,c=c.height);c=Math.round(c/2-a.height/2);0>c&&(c=0);b=Math.round(b/2-a.width/2);0>b&&(b=0);a&&(a.parentNode.style.top=c+"px",isRTL()?a.parentNode.style.right=b+"px":a.parentNode.style.left=b+"px");displayOriginalSize()}}
function setEvent(){function a(a){null!=document.getElementById("image_canvas")&&(null==KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper?(displayProcessing(!0),a="A"==a.target.tagName?a.target:a.target.parentElement,G_CURRCROPTYPE=a.id.replace("btn_",""),setTimeout(function(){var a=document.getElementById("image_canvas");a.style.left=a.parentNode.style.left;a.style.top=a.parentNode.style.top;a.parentNode.style.width=a.width+"px";a.parentNode.style.height=a.height+"px";KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper=
new Cropper(a,{zoomOnWheel:!1,autoCrop:!1,toggleDragModeOnDblclick:!1,ready:function(){document.getElementById(G_CURRCROPTYPE+"_tools_area").className="";document.getElementById("crop_box_size").parentNode.style.display="";selectCropType(0);displayProcessing(!1)},crop:function(a){a=a.detail;if(KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper)try{var b=parseInt(a.width,10),c=parseInt(a.height,10);if(0==b){var d=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCropBoxData();"undefined"!=typeof d.width&&(b=d.width=1,
KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.setCropBoxData(d))}0==c&&(d=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCropBoxData(),"undefined"!=typeof d.height&&(c=d.height=1,KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.setCropBoxData(d)));document.getElementById("crop_box_size").innerHTML=b+" x "+c+" px"}catch(g){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}}})},50)):(a="A"==a.target.tagName?a.target:a.target.parentElement,a=a.id.replace("btn_",""),a!=G_CURRCROPTYPE&&(closeCropArea(!0),G_CURRCROPTYPE=
a,selectCropType(G_CURRCROPMODE),document.getElementById(G_CURRCROPTYPE+"_tools_area").className="")))}function c(){cropCancel()}function b(){cropOk()}function d(){setCropBox(0);selectCropType(0)}function g(){setCropBox(4/3);selectCropType(1)}function n(){setCropBox(16/9);selectCropType(2)}function u(){setCropBox(1);selectCropType(3)}function m(){setCropBox(2/3);selectCropType(4)}function r(){setCropBox(.75);selectCropType(5)}var z=document.getElementById("open_file");z.onchange=function(){var a=
z.files[0];if(a){var b=KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.maxImageFileSize;if(0<b&&a.size>b){var c=KMiniPhoto_Lang.msg.max_file_size,c=c.replace("{0}",KMINIPHOTOTOP.KMINIPHOTO.util.bytesToSize(b).toString);alert(c)}else 0!=KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.maxTotalFileSize&&KMINIPHOTOTOP.G_CURRKMINIPHOTO.addedTotalFileSize+a.size>KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.maxTotalFileSize?(c=KMiniPhoto_Lang.msg.max_total_file_size,c=c.replace("{0}",KMINIPHOTOTOP.KMINIPHOTO.util.bytesToSize(KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.maxTotalFileSize).toString),
c=c.replace("{1}",KMINIPHOTOTOP.KMINIPHOTO.util.bytesToSize(KMINIPHOTOTOP.G_CURRKMINIPHOTO.addedTotalFileSize).toString),c=c.replace("{2}",KMINIPHOTOTOP.KMINIPHOTO.util.bytesToSize(a.size).toString),alert(c)):(b=getImageExtensionFromType(a.type),a=(window.URL||window.webkitURL||window).createObjectURL(a),KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgExt=b,loadImage({isInit:!1,isOpen:!0,src:a}))}};document.getElementById("btn_open").onclick=function(){cropCancel();fileOpen()};document.getElementById("btn_undo").onclick=
function(){if(null!=document.getElementById("image_canvas")){cropCancel();var a=document.getElementById("image_canvas");G_HISTORY.undo(a,a.getContext("2d"))}};document.getElementById("btn_redo").onclick=function(){if(null!=document.getElementById("image_canvas")){cropCancel();var a=document.getElementById("image_canvas");G_HISTORY.redo(a,a.getContext("2d"))}};document.getElementById("img_rotate_r").onclick=function(){fn_imageChange({degree:90,flip:0})};document.getElementById("img_rotate_l").onclick=
function(){fn_imageChange({degree:-90,flip:0})};document.getElementById("img_flip_h").onclick=function(){fn_imageChange({degree:0,flip:1})};document.getElementById("img_flip_v").onclick=function(){fn_imageChange({degree:0,flip:-1})};document.getElementById("btn_crop").onclick=a;document.getElementById("btn_mosaic").onclick=a;document.getElementById("crop_cancel").onclick=c;document.getElementById("mosaic_cancel").onclick=c;document.getElementById("crop_ok").onclick=b;document.getElementById("mosaic_ok").onclick=
b;document.getElementById("crop_ratio_0").onclick=d;document.getElementById("mosaic_ratio_0").onclick=d;document.getElementById("crop_ratio_1").onclick=g;document.getElementById("mosaic_ratio_1").onclick=g;document.getElementById("crop_ratio_2").onclick=n;document.getElementById("mosaic_ratio_2").onclick=n;document.getElementById("crop_ratio_3").onclick=u;document.getElementById("mosaic_ratio_3").onclick=u;document.getElementById("crop_ratio_4").onclick=m;document.getElementById("mosaic_ratio_4").onclick=
m;document.getElementById("crop_ratio_5").onclick=r;document.getElementById("mosaic_ratio_5").onclick=r;document.getElementById("btn_reset").onclick=function(){fn_reset()};document.getElementById("btn_apply").onclick=function(){fn_apply()};KMINIPHOTOTOP.document.getElementById("btn_fullscreen_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).onclick=function(){fn_fullscreen()};KMINIPHOTOTOP.document.getElementById("btn_close_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).onclick=function(){fn_close()};KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(document,
"keydown",document_keydown);KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(document.body,"paste",fn_pasteEvt);KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(document,"dragover",documentDragOver);KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(document,"drop",insertDropImage);KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(window,"unload",_kminiphotoiframe_Unload)}
function _kminiphotoiframe_Unload(a){try{var c=getPhotoFromUnloadEvent(a);if("1"==c._config.autoDestroy.use)try{KMINIPHOTOTOP.KMINIPHOTO.Destroy(c)}catch(b){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}}catch(d){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}}
function document_keydown(a){var c="which"in a?a.which:a.keyCode,b=a.ctrlKey;if(KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper&&0==b)if(37==c){KMINIPHOTOTOP.KMINIPHOTO.util.cancelEvent(a);var d=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCropBoxData();--d.left;KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.setCropBoxData(d)}else 39==c?(KMINIPHOTOTOP.KMINIPHOTO.util.cancelEvent(a),d=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCropBoxData(),d.left+=1,KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.setCropBoxData(d)):38==c?(KMINIPHOTOTOP.KMINIPHOTO.util.cancelEvent(a),
d=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCropBoxData(),--d.top,KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.setCropBoxData(d)):40==c?(KMINIPHOTOTOP.KMINIPHOTO.util.cancelEvent(a),d=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCropBoxData(),d.top+=1,KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.setCropBoxData(d)):27==c&&cropCancel();1==b&&(a.altKey||86!=c||(KMINIPHOTOTOP.KMINIPHOTO.browser.ie&&11<=KMINIPHOTOTOP.KMINIPHOTO.browser.ieVersion||KMINIPHOTOTOP.KMINIPHOTO.browser.gecko)&&fn_makePasteEvt(a))}
function fileOpen(){document.getElementById("open_file").click()}function setCropBox(a){KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.options.aspectRatio=a;var c={};if(0!=a){var b=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCropBoxData();c.width=parseInt(b.height*a,10);c.height=parseInt(b.height,10)}KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.setCropBoxData(c)}
function fn_imageChange(a){null!=document.getElementById("image_canvas")&&(displayProcessing(!0),setTimeout(function(){KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper&&cropCancel();var c=document.getElementById("image_canvas"),b=c.getContext("2d");G_HISTORY.saveState(c);b.setTransform(1,0,0,1,0,0);b.clearRect(0,0,c.width,c.height);fn_rotate(a.degree,c,b);fn_flip(a.flip,c,b);b.drawImage(KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage,0,0);setCanvasPostionCenter();displayProcessing(!1)},50))}
function fn_rotate(a,c,b){a&&(KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree+=a,360==KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree?KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree=0:0>KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree&&(KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree=360+KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree));switch(KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree){case 90:c.width=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalHeight;c.height=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalWidth;c.parentNode.style.width=
c.width+"px";c.parentNode.style.height=c.height+"px";b.rotate(KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree*Math.PI/180);b.translate(0,-c.width);break;case 180:c.width=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalWidth;c.height=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalHeight;c.parentNode.style.width=c.width+"px";c.parentNode.style.height=c.height+"px";b.rotate(KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree*Math.PI/180);b.translate(-1*c.width,-1*c.height);break;case 270:c.width=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalHeight;
c.height=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalWidth;c.parentNode.style.width=c.width+"px";c.parentNode.style.height=c.height+"px";b.rotate(KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree*Math.PI/180);b.translate(-1*c.height,0);break;case 0:c.width=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalWidth,c.height=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalHeight,c.parentNode.style.width=c.width+"px",c.parentNode.style.height=c.height+"px",b.translate(0,0)}}
function fn_flip(a,c,b){var d;d=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalWidth;c=KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage.naturalHeight;1==a?90==KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree||270==KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree?KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipY=KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipY?!1:!0:KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipX=KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipX?!1:!0:-1==a&&(90==KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree||270==KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree?
KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipX=KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipX?!1:!0:KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipY=KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipY?!1:!0);a=KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipX?-1*d:0;c=KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipY?-1*c:0;b.scale(KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipX?-1:1,KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipY?-1:1);b.translate(a,c)}
function fn_reset(){null!=document.getElementById("image_canvas")&&(cropCancel(),G_HISTORY.reset(),loadImage({isInit:!1,src:KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImg.src,width:KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgWidth,height:KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgHeight}))}
function fn_apply(){if(null!=document.getElementById("image_canvas")){cropCancel();var a={src:"",width:"",height:""},c=document.getElementById("image_canvas");a.src=c.toDataURL("image/"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgExt,1);a.width=c.width+"px";a.height=c.height+"px";fn_close();try{"function"===typeof KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.saveCompleteEvent&&KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.saveCompleteEvent(KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID,a)}catch(b){"undefined"!=typeof RAONWIZDLW&&
RAONWIZDLW&&RAONWIZDLW()}}}function closeCropArea(a){a||(KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper=null);document.getElementById("image_canvas");document.getElementById(G_CURRCROPTYPE+"_tools_area").className="off";a=document.getElementById("crop_box_size");a.innerHTML="0 x 0 px";a.parentNode.style.display="none"}function cropCancel(){KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper&&(KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.destroy(),closeCropArea())}
function cropOk(){KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCropBoxData()&&!KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCropBoxData().hasOwnProperty("width")?alert(KMiniPhoto_Lang.no_selected_area):(displayProcessing(!0),setTimeout(function(){G_HISTORY.saveState(document.getElementById("image_canvas"));var a=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.getCroppedCanvas(),c=a.toDataURL("image/"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgExt,1);"mosaic"==G_CURRCROPTYPE?runMosaicFunc(a,c):(closeCropArea(),loadImage({isInit:!1,
src:c}))},50))}function displayProcessing(a){document.getElementById("span_processing").style.display=a?"":"none"}var G_originScrollSize,G_originPhotoSize=[],G_originfull={},G_origianPopupPos=[],G_relativePos,G_isRelativePos;
function fn_close(){displayProcessing(!1);cropCancel();var a=KMINIPHOTOTOP.G_CURRKMINIPHOTO.arrBlobUrl.length;if(0<a)for(var c=0;c<a;c++)try{(window.URL||window.webkitURL||window).revokeObjectURL(KMINIPHOTOTOP.G_CURRKMINIPHOTO.arrBlobUrl[c])}catch(b){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}if(a=document.getElementById("image_canvas"))c=a.getContext("2d"),c.setTransform(1,0,0,1,0,0),c.clearRect(0,0,a.width,a.height),a=a.parentNode,a.style.width="0px",a.style.height="0px",a.innerHTML=
"";G_HISTORY.reset();"fullscreen"==KMINIPHOTOTOP.G_CURRKMINIPHOTO.frameStatus&&fullSreenToOriginalSize();KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.display="none";KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_body_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.display="none";(a=KMINIPHOTOTOP.document.getElementById("kminiphoto_popup_background"))&&KMINIPHOTOTOP.document.body.removeChild(a)}
function fn_fullscreen(){var a=KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID),c=document.getElementById("miniPhoto_holder"),b=document.getElementById("miniPhoto_image");if(""==KMINIPHOTOTOP.G_CURRKMINIPHOTO.frameStatus){var d=KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.dialogWindow?KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.dialogWindow:KMINIPHOTOTOP.window;G_originScrollSize=getWindowScrollPos(d);G_originPhotoSize.push(a.style.width);G_originPhotoSize.push(a.style.height);
G_originfull.margin1=KMINIPHOTOTOP.document.documentElement.style.margin;G_originfull.padding1=KMINIPHOTOTOP.document.documentElement.style.padding;G_originfull.border1=KMINIPHOTOTOP.document.documentElement.style.border;G_originfull.height1=KMINIPHOTOTOP.document.documentElement.style.height;G_originfull.overflow1=KMINIPHOTOTOP.document.documentElement.style.overflow;"1"==KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.fullscreenType&&(G_originfull.margin2=KMINIPHOTOTOP.document.body.style.margin,G_originfull.padding2=
KMINIPHOTOTOP.document.body.style.padding,G_originfull.border2=KMINIPHOTOTOP.document.body.style.border,G_originfull.height2=KMINIPHOTOTOP.document.body.style.height,G_originfull.overflow2=KMINIPHOTOTOP.document.body.style.overflow);KMINIPHOTOTOP.document.documentElement.style.overflow="hidden";KMINIPHOTOTOP.document.documentElement.style.padding="0";KMINIPHOTOTOP.document.documentElement.style.margin="0";KMINIPHOTOTOP.document.documentElement.style.border="0";KMINIPHOTOTOP.document.documentElement.style.height=
"100%";"1"==KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.fullscreenType&&(KMINIPHOTOTOP.document.body.style.overflow="hidden",KMINIPHOTOTOP.document.body.style.padding="0",KMINIPHOTOTOP.document.body.style.margin="0",KMINIPHOTOTOP.document.body.style.border="0",KMINIPHOTOTOP.document.body.style.height="100%");G_originfull.overflow3=a.style.overflow;G_originfull.position3=a.style.position;G_originfull.zIndex=a.style.zIndex;KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(a);a.style.overflow="hidden";a.style.position=
"absolute";a.style.width="100%";a.style.height="100%";var g=getWindowClientSize(d);a.style.width=g[0]+"px";a.style.height=g[1]+"px";c.style.width=g[0]-2+"px";b.style.width=g[0]-2+"px";b.style.height=g[1]-30-56-20-2+"px";KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_header_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.width=g[0]-2+"px";G_origianPopupPos.push(a.style.left);G_origianPopupPos.push(a.style.top);a.style.left="0px";a.style.top="0px";c=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(a);
G_relativePos=isRelativePosition(a);0<c.left||0<c.top?G_isRelativePos=!0:"0"==KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.fullscreenType&&(0<G_originScrollSize[0]&&(a.style.left=G_originScrollSize[0]+"px"),0<G_originScrollSize[1]&&(a.style.top=G_originScrollSize[1]+"px"));"1"==KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.fullscreenType&&adjustPopupPosition();setBackupHiddenStyle(a,d);KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(d,"resize",resizeForFullscreen);KMINIPHOTOTOP.G_CURRKMINIPHOTO.frameStatus="fullscreen";
KMINIPHOTOTOP.document.getElementById("btn_fullscreen_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.backgroundPosition="0 -50px";KMINIPHOTOTOP.document.getElementById("btn_fullscreen_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).title=KMiniPhoto_Lang.originalScreen;setCanvasPostionCenter()}else fullSreenToOriginalSize()}
function adjustPopupPosition(a){void 0==a&&(a=document.getElementById("miniPhoto_holder"));var c=KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_header_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID);c&&(c=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(c),0>c.top&&(a.style.top=KMINIPHOTOTOP.KMINIPHOTO.util.parseIntOr0(a.style.top)-KMINIPHOTOTOP.KMINIPHOTO.util.parseIntOr0(c.top)+"px"))}
function getWindowScrollPos(a){var c=0,b=0;"number"===typeof a.pageYOffset?(c=a.pageXOffset,b=a.pageYOffset):a.document.body&&(a.document.body.scrollLeft||a.document.body.scrollTop)?(c=a.document.body.scrollLeft,b=a.document.body.scrollTop):a.document.documentElement&&(a.document.documentElement.scrollLeft||a.document.documentElement.scrollTop)&&(c=a.document.documentElement.scrollLeft,b=a.document.documentElement.scrollTop);c=changeValueForZoom(c,KMINIPHOTOTOP.G_CURRKMINIPHOTO);b=changeValueForZoom(b,
KMINIPHOTOTOP.G_CURRKMINIPHOTO);return[c,b]}
function getWindowClientSize(a){var c=0,b=0;"number"==typeof a.innerWidth?(c=a.innerWidth,b=a.innerHeight):a.document.documentElement&&(a.document.documentElement.clientWidth||a.document.documentElement.clientHeight)?(c=a.document.documentElement.clientWidth,b=a.document.documentElement.clientHeight):a.document.body&&(a.document.body.clientWidth||a.document.body.clientHeight)&&(c=a.document.body.clientWidth,b=a.document.body.clientHeight);c=changeValueForZoom(c,KMINIPHOTOTOP.G_CURRKMINIPHOTO);b=changeValueForZoom(b,
KMINIPHOTOTOP.G_CURRKMINIPHOTO);return[c,b]}function isRelativePosition(a){for(;null!=a&&(!a.tagName||"body"!=a.tagName.toLowerCase());)if(a=a.parentNode,"relative"==a.style.position)return!0;return!1}
function setBackupHiddenStyle(a,c){G_originStylebackup=[];for(var b=a;null!=b&&(!b.tagName||"body"!=b.tagName.toLowerCase());){if(b!=a){var d;(d=c.getComputedStyle?c.getComputedStyle(b,""):b.currentStyle)&&d.overflow&&"hidden"==d.overflow&&(G_originStylebackup.push(b),b.style.setProperty?b.style.setProperty("overflow","visible",null):b.style.setAttribute("overflow","visible"))}b=b.parentNode}}
function resizeForFullscreen(){var a=KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID),c=document.getElementById("miniPhoto_holder"),b=document.getElementById("miniPhoto_image"),d=KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.dialogWindow?KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.dialogWindow:KMINIPHOTOTOP.window,g=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(a);a.style.left=KMINIPHOTOTOP.KMINIPHOTO.util.parseIntOr0(a.style.left)+-1*g.left+"px";a.style.top=KMINIPHOTOTOP.KMINIPHOTO.util.parseIntOr0(a.style.top)+
-1*g.top+"px";d=getWindowClientSize(d);a.style.width=d[0]+"px";a.style.height=d[1]+"px";KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_header_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.width=d[0]-2+"px";c.style.width=d[0]-2+"px";c.style.height=d[1]+"px";b.style.width=d[0]-2+"px";b.style.height=d[1]-30-56-20-2+"px";setCanvasPostionCenter()}
function fullSreenToOriginalSize(){var a=KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID),c=document.getElementById("miniPhoto_holder"),b=document.getElementById("miniPhoto_image");KMINIPHOTOTOP.KMINIPHOTO.util.removeEvent(KMINIPHOTOTOP.window,"resize",resizeForFullscreen);KMINIPHOTOTOP.document.documentElement.style.margin=G_originfull.margin1;KMINIPHOTOTOP.document.documentElement.style.padding=G_originfull.padding1;KMINIPHOTOTOP.document.documentElement.style.border=
G_originfull.border1;KMINIPHOTOTOP.document.documentElement.style.height=G_originfull.height1;KMINIPHOTOTOP.document.documentElement.style.overflow=G_originfull.overflow1;"1"==KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.fullscreenType&&(KMINIPHOTOTOP.document.body.style.margin=G_originfull.margin2,KMINIPHOTOTOP.document.body.style.padding=G_originfull.padding2,KMINIPHOTOTOP.document.body.style.border=G_originfull.border2,KMINIPHOTOTOP.document.body.style.height=G_originfull.height2,KMINIPHOTOTOP.document.body.style.overflow=
G_originfull.overflow2);a.style.overflow=G_originfull.overflow3;a.style.position=G_originfull.position3;0<G_originPhotoSize.length&&(a.style.width=G_originPhotoSize[0],a.style.height=G_originPhotoSize[1],c.style.width=parseInt(G_originPhotoSize[0],10)-2+"px",KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_header_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.width=parseInt(G_originPhotoSize[0],10)-2+"px",b.style.width=parseInt(G_originPhotoSize[0],10)-2+"px",b.style.height=parseInt(G_originPhotoSize[1],
10)-30-56-20-2+"px",G_originPhotoSize=[]);0<G_origianPopupPos.length&&(a.style.left=G_origianPopupPos[0],a.style.top=G_origianPopupPos[1],G_origianPopupPos=[]);setRestorreHiddenStyle();G_toolHeight=0;null!=G_originScrollSize&&(KMINIPHOTOTOP.window.scroll(G_originScrollSize[0],G_originScrollSize[1]),G_originScrollSize=null);KMINIPHOTOTOP.G_CURRKMINIPHOTO.frameStatus="";KMINIPHOTOTOP.document.getElementById("btn_fullscreen_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.backgroundPosition="0 0";KMINIPHOTOTOP.document.getElementById("btn_fullscreen_"+
KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).title=KMiniPhoto_Lang.fullScreen;setCanvasPostionCenter()}function setRestorreHiddenStyle(){for(var a=G_originStylebackup.length,c=0;c<a;c++){var b=G_originStylebackup[c];b.style.setProperty?b.style.setProperty("overflow","hidden",null):b.style.setAttribute("overflow","hidden")}G_originStylebackup=[]}
function showPhotoPopup(a){var c=KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID);c.parentNode.style.display="";document.getElementById("miniPhoto_holder");document.getElementById("miniPhoto_image");var b=getWindowClientSize(KMINIPHOTOTOP.window),d=getWindowScrollPos(KMINIPHOTOTOP.window),g;if(null==document.getElementById("kminiphoto_popup_background")){g=document.createElement("div");g.setAttribute("id","kminiphoto_popup_background");var n='<div style="'+
KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.popupBackgroundStyle+" z-index:"+(KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.zIndex-1)+'; position:fixed; _position:absolute; left:0px; top:0px;overflow:hidden;width:100%;height:100%;"></div>',n=n+('<iframe frameborder="0" scrolling="no" style="filter:alpha(opacity=0); opacity:0; -moz-opacity:0; -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=0); -khtml-opacity: 0; left: 0px; top: 0px; width: 100%; height: 100%; display: block; position: absolute; z-index: '+
(KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.zIndex-2)+';"></iframe>');g.innerHTML=n;KMINIPHOTOTOP.document.body.appendChild(g);g.getElementsByTagName("iframe")[0].style.height=b[1]+d[1]+"px"}c.style.display="";c.style.position="absolute";c.style.zIndex=KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.zIndex;n=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(c);g=n.right-n.left;n=n.bottom-n.top;isFixedPhotoPosition({component:KMINIPHOTOTOP.G_CURRKMINIPHOTO})&&(c.style.position="fixed",d[0]=0,d[1]=0);c.style.left=d[0]+
b[0]/2-g/2+"px";c.style.top=d[1]+b[1]/2-n/2+"px";adjustPopupPosition();makeDragPopup(c);setImageArea();null!=a.url&&(KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgExt=getImageExtensionFromUrl(a.url));null!=a.addedTotalFileSize&&(KMINIPHOTOTOP.G_CURRKMINIPHOTO.addedTotalFileSize=a.addedTotalFileSize);loadImage({isInit:!0,src:a.url,width:a.width,height:a.height});KMINIPHOTOTOP.KMINIPHOTO.browser.ie?setTimeout(function(){try{window.focus(),document.focus(),document.body.focus()}catch(a){"undefined"!=typeof RAONWIZDLW&&
RAONWIZDLW&&RAONWIZDLW()}},0):setTimeout(function(){try{window.focus(),document.body.focus()}catch(a){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}},0);if(a=document.getElementById("mosaic_slider"))c=function(){document.getElementById("mosaic_percent").innerText=document.getElementById("mosaic_slider").value+"%"},KMINIPHOTOTOP.G_CURRKMINIPHOTO._config.parentEditor._FRAMEWIN.DEXTTOP.DEXT5.browser.ie?a.onchange=c:a.oninput=c}var G_drag=!1,G_dragPopup;
function makeDragPopup(a){G_drag=!1;var c=a.firstChild;KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(c,"mousedown",startDrag);KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(c,"mouseover",function(){c.style.cursor="move"});KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(c,"mouseout",function(){c.style.cursor="default"});G_dragPopup=a}
function startDrag(a){""==KMINIPHOTOTOP.G_CURRKMINIPHOTO.frameStatus&&(a||(a=KMINIPHOTOTOP.window.event),G_offsetX=a.clientX,G_offsetY=a.clientY,G_dragPopup.style.left||(G_dragPopup.style.left="0px"),G_dragPopup.style.top||(G_dragPopup.style.top="0px"),G_coordX=parseInt(G_dragPopup.style.left),G_coordY=parseInt(G_dragPopup.style.top),G_drag=!0,KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_body_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.display="",KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(KMINIPHOTOTOP.document,
"mousemove",dragDiv),KMINIPHOTOTOP.KMINIPHOTO.util.addEvent(KMINIPHOTOTOP.document,"mouseup",stopDrag));KMINIPHOTOTOP.KMINIPHOTO.util.cancelEvent(a)}
function dragDiv(a){if(G_drag){a||(a=KMINIPHOTOTOP.window.event);var c=getWindowClientSize(KMINIPHOTOTOP.window),b=KMINIPHOTOTOP.KMINIPHOTO.util.getClientRect(G_dragPopup),b=[b.right-b.left||0,b.bottom-b.top||0];currentScrollPos=getWindowScrollPos(KMINIPHOTOTOP.window);isFixedPhotoPosition({component:KMINIPHOTOTOP.G_CURRKMINIPHOTO})&&(G_dragPopup.style.position="fixed",currentScrollPos[0]=0,currentScrollPos[1]=0);var d=G_coordX+a.clientX-G_offsetX,g=G_coordY+a.clientY-G_offsetY;0>=d-currentScrollPos[0]&&
(d=currentScrollPos[0]);0>=g-currentScrollPos[1]&&(g=currentScrollPos[1]);d+b[0]>=c[0]+currentScrollPos[0]&&(d=c[0]-b[0]+currentScrollPos[0]);g+b[1]>=c[1]+currentScrollPos[1]&&(g=c[1]-b[1]+currentScrollPos[1]);G_dragPopup.style.left=d+"px";G_dragPopup.style.top=g+"px";KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_header_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID);adjustPopupPosition(G_dragPopup);KMINIPHOTOTOP.KMINIPHOTO.util.stopEvent(a);KMINIPHOTOTOP.KMINIPHOTO.util.cancelEvent(a)}}
function stopDrag(a){G_drag=!1;G_dragPopup.style.cursor="";KMINIPHOTOTOP.KMINIPHOTO.util.removeEvent(KMINIPHOTOTOP.document,"mousemove",dragDiv);KMINIPHOTOTOP.KMINIPHOTO.util.removeEvent(KMINIPHOTOTOP.document,"mouseup",stopDrag);KMINIPHOTOTOP.document.getElementById("kminiphoto_holder_body_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.ID).style.display="none"}
function selectCropType(a){for(var c=0;6>c;c++)document.getElementById(G_CURRCROPTYPE+"_ratio_"+c).parentNode.style.backgroundColor=a==c?"#b5d0f1":"";G_CURRCROPMODE=a}function getImageExtensionFromType(a){var c="png";try{a&&""!=a&&(a=a.split("/")[1]),a&&0<a.length&&(c="gif"==a||"png"==a?"png":"jpeg")}catch(b){c="png"}return c}
function getImageExtensionFromUrl(a){var c="";try{if(0==a.indexOf("data:")){var b=a.split(",");2==b.length&&(c=getExtFromImageDataSrc(b[0]))}else var d=a.split("?"),g=d[0].lastIndexOf("."),c=d[0].substring(g+1,d[0].length),c=c.toLowerCase();c="gif"==c||"png"==c?"png":"jpeg"}catch(n){c="png"}return c}function getExtFromImageDataSrc(a){var c="";a=a.replace("data:","").split(";");0<a.length&&(a=a[0].split("/"),2==a.length&&(c=a[1]));return c}
function getPhotoFromUnloadEvent(a){var c=null;try{if(null!=a){var b=a.target?a.target:a.srcElement;if(b)try{a="",b._raonk_miniphoto?a="kminiphoto_frame_"+b._raonk_miniphoto.ID:b.defaultView&&(a="kminiphoto_frame_"+KMINIPHOTOTOP.G_CURRKMINIPHOTO),c=KMINIPHOTOTOP.KMINIPHOTO.RAONKMULTIPLE[a]}catch(d){c=KMINIPHOTOTOP.G_CURRKMINIPHOTO}else c=KMINIPHOTOTOP.G_CURRKMINIPHOTO}else c=KMINIPHOTOTOP.G_CURRKMINIPHOTO}catch(g){c=KMINIPHOTOTOP.G_CURRKMINIPHOTO}return c}
function fn_makePasteEvt(a){try{if(a&&(KMINIPHOTOTOP.G_CURRKMINIPHOTO=getPhotoFromEvent(a)),KMINIPHOTOTOP.KMINIPHOTO.browser.ie){var c=document.createElement("div");c.id="pasteDiv";c.innerHTML=unescape("%uFEFF");c.style.position="absolute";c.style.filter="alpha(opacity=0)";c.style.overflow="hidden";c.style.left="-1000px";c.style.top="-1000px";c.style.width="0px";c.style.height="0px";c.contentEditable=!0;document.body.appendChild(c);c.focus()}else if(KMINIPHOTOTOP.KMINIPHOTO.browser.gecko){var b=document.createElement("iframe");
b.id="pasteIframe";b.frameBorder=0;b.style.width="0px";b.style.height="0px";b.style.position="absolute";b.style.left="0px";b.style.top="0px";if(KMINIPHOTOTOP.KMINIPHOTO.browser.mobile||KMINIPHOTOTOP.KMINIPHOTO.browser.iOS)b.style.overflow="hidden",b.style.display="inline-block";var d="document.open();"+(KMINIPHOTOTOP.KMINIPHOTO.browser.isCustomDomain(document)?'document.domain="'+document.domain+'";':"")+" document.close();",d=KMINIPHOTOTOP.KMINIPHOTO.browser.ie?"javascript:void(function(){"+encodeURIComponent(d)+
"}())":"";b.src=d;document.body.appendChild(b);var g=KMINIPHOTOTOP.KMINIPHOTO.util.getIframeDocument(b);g.open("text/html","replace");KMINIPHOTOTOP.KMINIPHOTO.browser.isCustomDomain(document)&&(g.domain=document.domain);g.write('<body contenteditable="true">'+unescape("%uFEFF")+"</body>");g.close();g.body.contentEditable=!0;g.body.onpaste=fn_pasteEvt;g.body.focus()}}catch(n){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}}
function fn_pasteEvt(a){try{var c=KMINIPHOTOTOP.G_CURRKMINIPHOTO;document.createElement("canvas").getContext("2d");if(KMINIPHOTOTOP.KMINIPHOTO.browser.ie||KMINIPHOTOTOP.KMINIPHOTO.browser.gecko)setTimeout(function(){var a=null,b=null;if(KMINIPHOTOTOP.KMINIPHOTO.browser.ie)b=a=document.getElementById("pasteDiv");else if(KMINIPHOTOTOP.KMINIPHOTO.browser.gecko)try{var d=document.getElementById("pasteIframe");d&&(a=KMINIPHOTOTOP.KMINIPHOTO.util.getIframeDocument(d).body,b=d)}catch(g){a=null}a&&(a.blur(),
a=a.getElementsByTagName("img"),0<a.length&&(c.initImgExt="png",loadImage({isInit:!1,isOpen:!0,src:a[0].src})),b.parentNode.removeChild(b))},0);else if(KMINIPHOTOTOP.KMINIPHOTO.browser.chrome||KMINIPHOTOTOP.KMINIPHOTO.browser.opera){var b=a.clipboardData.items,d=b.length;for(a=0;a<d;++a){var g=b[a].getAsFile(),n=new FileReader;n.onload=function(a){a=a.target.result;c.initImgExt="png";loadImage({isInit:!1,isOpen:!0,src:a});n=void 0};n.readAsDataURL(g)}}}catch(u){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&
RAONWIZDLW()}}function getPhotoFromEvent(a){var c=null;try{if(null!=a){var b=a.target?a.target:a.srcElement;if(b){a=null;a=9!=b.nodeType?b.ownerDocument:b;try{a=a.defaultView?a.defaultView:a.parentWindow,c=KMINIPHOTOTOP.KMINIPHOTO.RAONKMULTIPLE[a.frameElement.id]}catch(d){c=KMINIPHOTOTOP.G_CURRKMINIPHOTO}}else c=KMINIPHOTOTOP.G_CURRKMINIPHOTO}else c=KMINIPHOTOTOP.G_CURRKMINIPHOTO}catch(g){c=KMINIPHOTOTOP.G_CURRKMINIPHOTO}return c}
function documentDragOver(a){KMINIPHOTOTOP.KMINIPHOTO.util.cancelEvent(a)}function insertDropImage(a){var c=a.dataTransfer.files;a.stopPropagation();a.preventDefault();if(0<c.length&&c[0].type&&0==c[0].type.indexOf("image")){var b=getImageExtensionFromType(c[0].type),d=new FileReader;d.onload=function(a){a=a.target.result;"data:"==a.substring(0,5)&&2==a.split(",").length&&(KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgExt=b,loadImage({isInit:!1,isOpen:!0,src:a}));d=void 0};d.readAsDataURL(c[0])}}
function getKMINIPHOTOWINoomValue(a){var c=1;try{if("1"==a._config.autoSetZoom.use){var b=KMINIPHOTOTOP.KMINIPHOTOWIN.document.body;a._config.autoSetZoom&&null!=a._config.autoSetZoom.checkNode&&(b=a._config.autoSetZoom.checkNode);var d=KMINIPHOTOTOP.KMINIPHOTOWIN.getComputedStyle(b,null).zoom;void 0!=d&&(c=d)}}catch(g){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}return c}
function setZoomValueToBody(a,c){if("1"==c._config.autoSetZoom.use)try{var b=getKMINIPHOTOWINoomValue(c);a.body.style.zoom=b}catch(d){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}}function changeValueForZoom(a,c){var b=a;if("1"==c._config.autoSetZoom.use)var d=getKMINIPHOTOWINoomValue(c),b=b/d;return b}
function isFixedPhotoPosition(a){var c=!1;a=a.component._config;if("1"==a.useFixedPositionToDialog)c=!0;else if("auto"==a.useFixedPositionToDialog){a=frameElement.parentNode;for(var b=!1;null!=a&&"BODY"!=a.tagName;){if("fixed"==(a.style&&a.style.position?a.style.position:"")){b=!0;break}a=a.parentNode}b&&(c=!0)}return c}
function canvasBugFix(a){var c=null;try{c=document.createElement("canvas");c.width=100;c.height=100;var b=c.getContext("2d");b.drawImage(a,0,0,100,100);b.getImageData(0,0,100,100)}catch(d){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}}
function runMosaicFunc(a,c){var b=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.cropBoxData.top,d=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.cropBoxData.left,g=new Image,n=a.width,u=0==a.height?Number(a.getAttribute("height")):a.height;g.width=n;g.height=u;g.style.display="none";g.src=c;document.getElementById("miniPhoto_image").firstChild.appendChild(g);null!=KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper&&KMINIPHOTOTOP.G_CURRKMINIPHOTO.cropper.destroy();g.onload=function(){var a=new Pixelate(g,void 0,function(){var c=
document.getElementById("mosaic_slider").value;a.setAmount(Number(c)/100).render();setTimeout(function(){var c=document.getElementById("image_canvas"),r=c.getContext("2d");canvasBugFix(g);r.setTransform(1,0,0,1,0,0);KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree=0;KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipX=!1;KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipY=!1;r.drawImage(g,d,b,n,u);a.canvas.removeNode?(a.canvas.removeNode(),g.removeNode()):(a.canvas.remove(),g.remove());setCurrImageFromCanvas(c);closeCropArea();displayProcessing(!1)},
50)})}}function setCurrImageFromCanvas(a){var c=new Image,b=a.width,d=0==a.height?Number(a.getAttribute("height")):a.height;c.width=b;c.height=d;c.style.display="none";c.src=a.toDataURL("image/"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgExt,1);KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage=c}function isRTL(a){var c=!1;a=(a?a:document).documentElement.getAttribute("dir");"string"==typeof a&&"rtl"==a&&(c=!0);return c};var G_HISTORY={redo_list:[],undo_list:[],saveState:function(a,c,b,d){b||(this.redo_list=[]);d?(c||this.undo_list).push(d.src):(a=a.toDataURL("image/"+KMINIPHOTOTOP.G_CURRKMINIPHOTO.initImgExt,1),(c||this.undo_list).push(a));this.displayBtn()},undo:function(a,c){this.restoreState(a,c,this.undo_list,this.redo_list)},redo:function(a,c){this.restoreState(a,c,this.redo_list,this.undo_list)},restoreState:function(a,c,b,d){var g=this;b.length&&(displayProcessing(!0),setTimeout(function(){g.saveState(a,d,
!0);var c=b.pop(),u=new Image;u.onload=function(){document.getElementById("miniPhoto_image");var b=a.getContext("2d");b.setTransform(1,0,0,1,0,0);b.clearRect(0,0,a.width,a.height);KMINIPHOTOTOP.G_CURRKMINIPHOTO.currDegree=0;KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipX=!1;KMINIPHOTOTOP.G_CURRKMINIPHOTO.flipY=!1;KMINIPHOTOTOP.G_CURRKMINIPHOTO.currImage=u;a.width=u.naturalWidth;a.height=u.naturalHeight;a.parentNode.style.width=u.naturalWidth+"px";a.parentNode.style.height=u.naturalHeight+"px";b.drawImage(u,
0,0);u.style.display="none";setCanvasPostionCenter();displayProcessing(!1);try{u=void 0}catch(c){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}};u.src=c;g.displayBtn()},50))},reset:function(){this.redo_list=[];this.undo_list=[];this.displayBtn()},displayBtn:function(){document.getElementById("btn_redo").firstChild.className=0<this.redo_list.length?"redo":"redo deact-r";document.getElementById("btn_undo").firstChild.className=0<this.undo_list.length?"undo":"undo deact-u"}};
