var console=window&&window.console?window.console:{log:function(){}},DEXTTOP=parent;DEXTTOP.DEXT5=parent.DEXT5;DEXTTOP.G_CURREDITOR=null;parent.DEXTTOP=DEXTTOP;DEXTTOP.DEXTDOC=parent.document;DEXTTOP.G_LIGHTVIEWDOC||(DEXTTOP.G_LIGHTVIEWDOC={});
function loadEditorFn(a,c,b){var d=document.getElementById("editorContentArea"),g;g=""+('<div id="ue_editor_main_'+a+'" class="DEXT_fiVe_EdiTor" style="z-index:99999; width:100%; "  oncontextmenu="return false">')+('\t<div id="ue_editor_holder_'+a+'" class="ue_editor_'+c.style.skinName+'_lr" ');if(DEXTTOP.DEXT5.browser.mobile||DEXTTOP.DEXT5.browser.iOS)g="1"==_this._config.view_mode_auto_height?g+' style="overflow:hidden;"':g+' style="overflow:scroll; -webkit-overflow-scrolling:touch;"';g+="\t></div>";
d.innerHTML=g;d=document.getElementById("ue_editor_holder_"+a);"0"==c.editorborder&&(d.style.borderWidth="0px");var f=document.createElement("iframe");f.id="dext5_lightview_"+a;f.title="dext5_lightview_"+a;f.frameBorder=0;f.style.width="100%";f.style.height="100%";f.style.borderWidth="0px";if(DEXTTOP.DEXT5.browser.mobile||DEXTTOP.DEXT5.browser.iOS)f.style.overflow="hidden",f.style.display="inline-block";g="document.open();"+(DEXTTOP.DEXT5.util.DEXT5_IsCustomDomain(document)?'document="'+document+
'";':"")+" document.close();";g=DEXTTOP.DEXT5.browser.ie&&12>DEXTTOP.DEXT5.browser.ieVersion?"javascript:void(function(){"+encodeURIComponent(g)+"}())":"";f.src=g;g=c.style.height;if(0<DEXTTOP.DEXT5.util.parseIntOr0(g))if(-1<g.toString().indexOf("%"))d.style.height=g;else{var e=2;7==DEXTTOP.DEXT5.browser.trident||12<=DEXTTOP.DEXT5.browser.ieVersion||!DEXTTOP.DEXT5.browser.quirks||(e=0);d.style.height=parseInt(g,10)-e+"px"}b._PageProp={};b._setting={};_dextSetting(b,c);b._PageProp.doctype="HTML 5";
""!=c.docType&&(b._PageProp.doctype=c.docType);f.onload=function(){f.onload=null;var d=f.contentDocument?f.contentDocument:f.contentWindow.document;if("1"==c.setDefaultStyle.value||"2"==c.setDefaultStyle.value){d.body.id=c.setDefaultStyle.body_id;var g=createEditorDefaultStyleInnerHTML(c,b._setting.font_family,b._setting.font_size,b._setting.line_height,b._setting.word_break_type,b._setting.word_wrap_type),e=document.createElement("style");e.type="text/css";e.setAttribute("data-destyle","deDefaultStyle");
e.styleSheet?e.styleSheet.cssText=g:e.textContent=g;d.head.appendChild(e)}d.body.spellcheck="false";d.body.contentEditable="false";d.body.style.cursor="auto";b._BODY=d.body;b._DOC=d;DEXTTOP.G_LIGHTVIEWDOC[a]=d;b._config.userCssUrl&&""!=b._config.userCssUrl&&(g=d.createElement("link"),g.type="text/css",g.rel="stylesheet",g.href=b._config.userCssUrl,d.getElementsByTagName("head")[0].appendChild(g));DEXTTOP.DEXT5.LIGHTVIEWEVT||(DEXTTOP.DEXT5.LIGHTVIEWEVT={});g=function(a){var b="which"in a?a.which:a.keyCode;
(a.ctrlKey||a.metaKey)&&-1==DEXTTOP.G_CURREDITOR._config.viewModeAllowShortcut.indexOf("copy")&&67==b&&DEXTTOP.DEXT5.util.cancelEvent(a)};e=function(a){"0"==DEXTTOP.G_CURREDITOR._config.viewModeContextMenu&&DEXTTOP.DEXT5.util.cancelEvent(a)};DEXTTOP.DEXT5.LIGHTVIEWEVT._lightView_Keydown=g;DEXTTOP.DEXT5.LIGHTVIEWEVT._lightView_Contextmenu=e;DEXTTOP.DEXT5.util.addEventEx(d,"keydown",g,!1);DEXTTOP.DEXT5.util.addEventEx(d,"contextmenu",e,!1);try{"function"==typeof b._config.event.loadedEvent?b._config.event.loadedEvent(b):
"function"==typeof b._config.LoadedEvent?b._config.LoadedEvent(b):"function"==typeof DEXTTOP.dext_editor_loaded_event&&DEXTTOP.dext_editor_loaded_event(b)}catch(h){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}DEXTTOP.DEXT5.InitEditorDataHashTable&&(d=DEXTTOP.DEXT5.InitEditorDataHashTable.getItem(b.ID),"undefined"!=typeof d&&("object"==typeof d?"setHtmlValueExWithDocType"==d.mode?DEXTTOP.DEXT5.setHtmlValueExWithDocType(d.value,b.ID):"setHtmlValueEx"==d.mode?DEXTTOP.DEXT5.setHtmlValueEx(d.value,
b.ID):"setHtmlValue"==d.mode?DEXTTOP.DEXT5.setHtmlValue(d.value,b.ID):"setBodyValueEx"==d.mode?DEXTTOP.DEXT5.setBodyValueEx(d.value,b.ID):"setBodyValueExLikeDiv"==d.mode?DEXTTOP.DEXT5.setBodyValueExLikeDiv(d.value,b.ID):"setBodyValue"==d.mode?DEXTTOP.DEXT5.setBodyValue(d.value,b.ID):"setOriginalHtmlValue"==d.mode?DEXTTOP.DEXT5.setOriginalHtmlValue(d.value,b.ID):"setHtmlContents"==d.mode&&DEXTTOP.DEXT5.setHtmlContents(d.value,b.ID):DEXTTOP.DEXT5.setHtmlContentsEw(d,b.ID),DEXTTOP.DEXT5.InitEditorDataHashTable.removeItem(b.ID)))};
d.appendChild(f)}
function lightViewFunc(a,c,b){var d="",g="",f=b._FRAMEWIN.document.getElementById("dext5_lightview_"+b.ID),f=f.contentDocument?f.contentDocument:f.contentWindow.document,g=f.getElementsByTagName("head")[0].outerHTML;b._docType[b._PageProp.doctype]&&(d=b._docType[b._PageProp.doctype]);switch(a){case "setEditorMode":"edit"==c&&(d=DEXTTOP.DEXT5.userConfigList[b.ID],d.Mode=c,d.Id=b.ID,DEXTTOP.G_LIGHTVIEWDOC[b.ID]=DEXTTOP.G_LIGHTVIEWDOC[b.ID].body.outerHTML,delete DEXTTOP.DEXT5.DEXTMULTIPLE["dext_frame_"+b.ID],
new DEXTTOP.Dext5editor(d));break;case "setBodyValue":openWriteClose(f,d+"<html>"+g+("<body>"+c+"</body>")+"</html>",b);break;case "setBodyValueEx":openWriteClose(f,d+"<html>"+g+c+"</html>",b);break;case "setBodyValueExLikeDiv":var e=c.substr(0,4);a=c.substr(c.length-6,6);"<div"==e.toLowerCase()&&"</div>"==a.toLowerCase()&&(e=e.replace(e,"<body"),a=a.replace(a,"</body>"),c=c.substring(4,c.length-6),c=e+c+a);openWriteClose(f,d+"<html>"+g+c+"</html>",b);break;case "setHtmlValue":c=getRemoveHeadScript(c);
c=c.html;b._config.userCssUrl&&""!=b._config.userCssUrl&&b._config.userCssAlwaysSet&&"1"==b._config.userCssAlwaysSet&&(html=userCssSet(html,b._config.userCssUrl));openWriteClose(f,d+"<html>"+c+"</html>",b);break;case "setHtmlValueEx":c=getRemoveHeadScript(c);c=c.html;b._config.userCssUrl&&""!=b._config.userCssUrl&&b._config.userCssAlwaysSet&&"1"==b._config.userCssAlwaysSet&&(c=userCssSet(c,b._config.userCssUrl));openWriteClose(f,d+c,b);break;case "setHtmlValueExWithDocType":c=getRemoveHeadScript(c);
c=c.html;b._config.userCssUrl&&""!=b._config.userCssUrl&&b._config.userCssAlwaysSet&&"1"==b._config.userCssAlwaysSet&&(c=userCssSet(c,b._config.userCssUrl));openWriteClose(f,c,b);break;case "setOriginalHtmlValue":b._config.userCssUrl&&""!=b._config.userCssUrl&&b._config.userCssAlwaysSet&&"1"==b._config.userCssAlwaysSet&&(c=userCssSet(c,b._config.userCssUrl)),openWriteClose(f,c,b)}}
function isViewMode(a){var c=a;if(void 0==a||null==a)c=DEXTTOP.G_CURREDITOR;return"view"==c._config.mode||"lightview"==c._config.mode?!0:!1}function groupingIcon(a){}function getClientRect(a){var c={left:0,top:0,right:0,bottom:0};try{c=a.getBoundingClientRect()}catch(b){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}return c}
function set_view_mode_auto_height(a){try{setTimeout(function(){var b=DEXTTOP.G_CURREDITOR;a&&(b=a);if("1"==b._config.view_mode_auto_height||"1"==b._config.view_mode_auto_width){var d=DEXTTOP.G_LIGHTVIEWDOC[a.ID].body,c=b._DOC.documentElement,f=b._config.style.height,e=b._config.style.width,l=0;0>f.indexOf("%")&&(l=parseInt(f,10));var m=0;0>e.indexOf("%")&&(m=parseInt(e,10));var k=0,h=0,k=DEXTTOP.document.getElementById(b._config.holderID),h=getClientRect(k),n,p;void 0==h.height?n=k.offsetHeight:
n=h.height;void 0==h.width?p=k.offsetWidth:p=h.width;n=Math.round(n);p=Math.round(p);if("1"==b._config.view_mode_auto_height){f="";DEXTTOP.DEXT5.browser.mobile&&DEXTTOP.DEXT5.browser.iOS&&(f=d.style,d.style="overflow:initial !important");k=Math.max(d.scrollHeight,d.offsetHeight,c.clientHeight,c.scrollHeight,c.offsetHeight);n>k&&(k=n);DEXTTOP.DEXT5.browser.mobile&&DEXTTOP.DEXT5.browser.iOS&&(d.style=f);var q=document.body.offsetWidth<d.scrollWidth,r=document.body.offsetHeight<d.scrollHeight;if(q||
r)k+=30}else k=l,-1<f.indexOf("%")&&(k=f);if("1"==b._config.view_mode_auto_width){if(h=Math.max(d.scrollWidth,d.offsetWidth,c.clientWidth,c.scrollWidth,c.offsetWidth),q||r)h+=10}else h=m,-1<e.indexOf("%")&&(h=e);p>h&&(h=p);DEXTTOP.DEXT5.setSize(h,k,b.ID)}},250)}catch(c){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}}
function openWriteClose(a,c,b){a.open("text/html","replace");a.write(c);a.close();set_view_mode_auto_height(b);DEXTTOP.DEXT5.util.addEventEx(a,"keydown",DEXTTOP.DEXT5.LIGHTVIEWEVT._lightView_Keydown,!1);DEXTTOP.DEXT5.util.addEventEx(a,"contextmenu",DEXTTOP.DEXT5.LIGHTVIEWEVT._lightView_Contextmenu,!1);try{"function"==typeof b._config.event.setComplete?b._config.event.setComplete(b.ID):"function"==typeof DEXTTOP.dext_editor_set_complete_event&&DEXTTOP.dext_editor_set_complete_event(b.ID)}catch(d){"undefined"!=
typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}}
function getRemoveHeadScript(a){var c={html:a,scriptsAry:[]},b=a.toLowerCase().indexOf("<head"),d=a.toLowerCase().indexOf("</head>"),g=a.substring(0,b),b=a.substring(b,d+7);a=a.substring(d+7,a.length);var d=RegExp("<script[^>]*src=([\\s\\S]*?)>[\\s\\S]*?\x3c/script>","gi"),f=b.match(d);if(f){for(var e=f.length,l=0;e>l;l++)d=RegExp('<script[^>]*src="([\\s\\SS]*?)"([\\s\\S]*?)>[sS]*?\x3c/script>',"gi"),d.test(f[l]),c.scriptsAry.push(RegExp.$1);d=RegExp("<script[^>]*src=([\\s\\S]*?)>[\\s\\S]*?\x3c/script>","gi");
b=b.replace(d,"");c.html=g+b+a}return c}function userCssSet(a,c){var b=strRetvalue=a,d='<link href="'+c+'" rel="stylesheet" type="text/css">';try{if(-1==a.indexOf(d)){var g=a.indexOf("</head>");if(-1==g){var f=a.indexOf("<body");strRetvalue=-1==f?"<head>"+d+"</head><body>"+a+"</body>":a.substring(0,f)+"<head>"+d+"</head>"+a.substring(f)}else strRetvalue=a.substring(0,g)+d+a.substring(g)}}catch(e){strRetvalue=b}return strRetvalue}
function removeTitleInStyleNode(a,c){var b=a;/<style [^>]*?title=.*?>/i.test(b)&&(b=b.replace(/<style [^>]*?(title=".*?").*?>/gi,function(a,b){return a.replace(b,"")}),b=b.replace(/<style [^>]*?(title=.*?)[ |>]/gi,function(a,b){return a.replace(b,"")}));return b}
function _dextSetting(a,c){a._setting.grid_color=c.gridColor;a._setting.grid_color_nm=c.gridColorName;a._setting.grid_spans=c.gridSpans;a._setting.grid_form=c.gridForm;a._setting.encoding=c.encoding;a._PageProp.encoding=a._setting.encoding;a._setting.word_break_type=DEXTTOP.DEXT5.util.getWordBreakStyle(c);a._setting.word_wrap_type=DEXTTOP.DEXT5.util.getWordWrapStyle(c);a._setting.page_title=c.document.docTitle;"1"==c.enforceDoctype||"2"!=c.enforceDoctype||DEXTTOP.DEXT5.browser.ie||(c.enforceDoctype=
"1");a._setting.xmlnsname=c.xmlnsname;a._PageProp.xmlnsname=a._setting.xmlnsname;a._setting.lang=c.lang;if((a._PageProp.lang=a._setting.lang)&&0<a._setting.lang.length){var b=document.getElementsByTagName("html")[0],d=a._setting.lang;-1<d.indexOf("-")&&(d=d.split("-")[0]);b.setAttribute("lang",d);b.setAttribute("xml:lang",d);0<a._setting.xmlnsname.length&&b.setAttribute("xmlns",a._setting.xmlnsname)}a._setting.font_family=c.defaultFontFamily;a._setting.font_size=c.defaultFontSize;a._setting.line_height=
c.defaultLineHeight;a._setting.show_font_real=c.showRealFont;"1"==c.useLineBreak&&"1"==c.saveLineBreakToLocalStorage&&DEXTTOP.DEXT5.browser.LocalStorageSupported&&((b=DEXTTOP.DEXT5.util.loadJsonFromLocalStorage("dext_"+this.ID+"_line_break"))?(d=b.word_wrap_type,a._setting.word_break_type=b.word_break_type,a._setting.word_wrap_type=d):(a._setting.word_break_type="1"==c.wordBreakType?"break-all":"2"==c.wordBreakType?"keep-all":"normal",a._setting.word_wrap_type="1"==c.wordWrapType?"break-word":"normal"));
DEXTTOP.DEXT5.browser.LocalStorageSupported&&(a._setting.config_paste_to_image=c.pasteToImage);a._docType={};a._docType.Auto=DEXTTOP.DEXT5.util.getDocType(DEXTTOP.document);a._docType.None="";a._docType["XHTML 1.1"]='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">';a._docType["XHTML 1.0 Transitional"]='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">';a._docType["XHTML 1.0 Strict"]=
'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">';a._docType["XHTML 1.0 Frameset"]='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">';a._docType["HTML 5"]="<!DOCTYPE html>";a._docType["HTML 4.01 Transitional"]='<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">';a._docType["HTML 4.01 Strict"]='<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">';
a._docType["HTML 4.01 Frameset"]='<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">';a._docType["HTML 3.2"]='<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">';a._docType["HTML 2.0"]='<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN">'}
function createEditorDefaultStyleInnerHTML(a,c,b,d,g,f){var e="";if(void 0==c||""==c)c=DEXTTOP.G_CURREDITOR._setting.font_family;if(void 0==b||""==b)b=DEXTTOP.G_CURREDITOR._setting.font_size;if(void 0==d||""==d)d=DEXTTOP.G_CURREDITOR._setting.line_height;if(void 0==g||""==g)g="normal";if(void 0==f||""==f)f="normal";var l="";"1"==a.defaultImemode&&(l="-ms-image-mode: active; ime-mode: active;");var m="";"1"==a.defaultBodySpace.use?(m="1"==a.defaultBodySpace.mode?"margin:":"2"==a.defaultBodySpace.mode?
G_BodyFit&&1==G_BodyFit.widthFixStatus&&"1"==a.ruler.use?"margin:10px 10px 10px 10px; padding:":"margin:0px; padding:":"margin:",m="1"==a.horizontalLine.use?m+("0px "+a.defaultBodySpace.configValue.right+" "+a.defaultBodySpace.configValue.bottom+" "+a.defaultBodySpace.configValue.left+";"):m+(a.defaultBodySpace.configValue.top+" "+a.defaultBodySpace.configValue.right+" "+a.defaultBodySpace.configValue.bottom+" "+a.defaultBodySpace.configValue.left+";")):m="margin:0px;";"1"==a.setDefaultStyle.value||
"2"==a.setDefaultStyle.value?(e+="#"+a.setDefaultStyle.body_id+" { cursor:text; "+m+" font-family:"+changeFontFamily(c)+"; font-size:"+b+";"+l+" word-break:"+g+"; word-wrap:"+f+"; }",e+="#"+a.setDefaultStyle.body_id+" p { line-height:"+d+"; margin-top:"+a.defaultFontMarginTop+"; margin-bottom:"+a.defaultFontMarginBottom+"; }",e+="#"+a.setDefaultStyle.body_id+" li { line-height:"+d+"; margin-top:"+a.defaultFontMarginTop+"; margin-bottom:"+a.defaultFontMarginBottom+"; }",e+="#"+a.setDefaultStyle.body_id+
" .raon_placeholder { display: inline-block; }",e+="#"+a.setDefaultStyle.body_id+" .raon_placeholder:empty:before { content: attr(placeholder); color: #EE0000; }",e+="#"+a.setDefaultStyle.body_id+" .raon_placeholder:focus:before { content: none; }"):(e+="body { cursor:text; "+m+" font-family:"+changeFontFamily(c)+"; font-size:"+b+";"+l+" word-break:"+g+"; word-wrap:"+f+"; }",e+="p { line-height:"+d+"; margin-top:"+a.defaultFontMarginTop+"; margin-bottom:"+a.defaultFontMarginBottom+"; }",e+="li { line-height:"+
d+"; margin-top:"+a.defaultFontMarginTop+"; margin-bottom:"+a.defaultFontMarginBottom+"; }",e+=".raon_placeholder { display: inline-block; }.raon_placeholder:empty:before { content: attr(placeholder); color: #EE0000; }",e+=".raon_placeholder:focus:before { content: none; }");"1"==a.highlight.use&&"undefined"!=typeof a.highlight.color&&""!=a.highlight.color&&(e+=" .raon_highlighter { background-color: "+a.highlight.color+"; } ");return e}
function changeFontFamily(a){a=a.split(",");for(var c="",b=0;b<a.length;b++){var d=a[b],d=DEXTTOP.DEXT5.util.trim(d);if(-1<d.indexOf(".")||-1<d.indexOf(" "))d=d.replace(/"/,""),d=d.replace(/'/,"");c+=d;b!=a.length-1&&(c+=", ")}return c};
