(function(){function q(a){var d={};a=a.split(",");for(var c=0;c<a.length;c++)d[a[c]]=!0;return d}var v=50,x=",span,strong,b,",y="p div a abbr acronym applet basefont bdo big br button cite code del dfn em font i iframe img input ins kbd label map object q s samp script select small strike sub sup textarea tt u var".split(" "),u=[],r=/^<([-A-Za-z0-9_]+)((?:\s+\w+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,z=/^<\/([-A-Za-z0-9_:@.]+)[^>]*>/,B=/([-A-Za-z0-9_]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,
t=/^<([-A-Za-z0-9_:-]+)((?:\s+[a-zA-Z_0-9:-]+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,C=/([-A-Za-z0-9_:-]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,D=q("colgroup,col"),E=q("area,base,basefont,br,col,frame,hr,img,input,isindex,link,meta,param,embed");q("area,base,basefont,br,col,frame,img,input,isindex,link,meta,param,embed");var F=q("address,applet,blockquote,button,center,dd,del,dir,div,dl,dt,fieldset,form,frameset,hr,iframe,ins,isindex,li,map,menu,noframes,noscript,object,ol,p,pre,script,table,tbody,td,tfoot,th,thead,tr,ul,h1,h2,h3,h4,h5,h6,figure,nav,section,article"),
A=!1,m="a,abbr,acronym,applet,b,basefont,bdo,big,br,button,cite,code,del,dfn,em,font,i,iframe,img,input,ins,kbd,label,map,object,q,s,samp,script,select,small,span,strike,strong,sub,sup,textarea,tt,u,var",w=q(m),G=q("colgroup,dd,dt,li,options,p,td,tfoot,th,thead,tr"),H=q("checked,compact,declare,defer,disabled,ismap,multiple,nohref,noresize,noshade,nowrap,readonly,selected"),I=q("");"undefined"==typeof DEXT5_EDITOR&&(DEXT5_EDITOR={});DEXT5_EDITOR.HTMLParser=function(a,d,c){function h(a,b,f,d){b=b.toLowerCase();
if(F[b]){for("table"!=l.last()&&"tbody"!=l.last()||"td"!=b||h("","tr","","");l.last()&&w[l.last()];)e("",l.last());"p"!=l.last()||"table"!=b&&"hr"!=b&&"center"!=b&&"figure"!=b||e("","p")}G[b]&&l.last()==b&&e("",b);(d=E[b]||!!d)||l.push(b);if(c.start){var g=[];a=r.test(a)?B:C;f.replace(a,function(a,b,f,c,d){f=f?f:c?c:d?d:H[b]?b:"";c="";""!=a&&(a=a.substring(a.indexOf(b)+b.length),a=a.substring(a.indexOf("=")+1),a=a.replace(/^\s+/,""),c=a.substring(0,1),"'"!=c&&'"'!=c&&(c=""));g.push({name:b,value:f,
escaped:f.replace(/(^|[^\\])"/g,'$1\\"'),quotationmark:c})});c.start&&c.start(b,g,d)}}function e(a,b){if(b)for(b=b.toLowerCase(),f=l.length-1;0<=f&&l[f]!=b;f--);else var f=0;if(0<=f){for(var d=l.length-1;d>=f;d--)c.end&&c.end(l[d]);l.length=f}}var b,f,l=[],m=a;for(l.last=function(){return this[this.length-1]};a;){f=!0;if(l.last()&&I[l.last()])a=a.replace(new RegExp("(.*)</"+l.last()+"[^>]*>"),function(a,b){b=b.replace(/\x3c!--(.*?)--\x3e/g,"$1").replace(/<!\[CDATA\[(.*?)]]\x3e/g,"$1");c.chars&&c.chars(b);
return""}),e("",l.last());else{var g=a.indexOf("<");b=a.indexOf(">")+1;var k=a.substring(g,b);if(0==a.indexOf("\x3c!--"))b=a.indexOf("--\x3e"),0<=b&&(c.comment&&("style"==l.last()?c.comment(a.substring(4,b),!0):c.comment(a.substring(4,b))),a=a.substring(b+3),f=!1);else if(0==a.toLowerCase().indexOf("<?xml"))b=a.indexOf("/>"),0<=b&&(a=a.substring(b+2),f=!1);else if(0!=a.indexOf("<")&&"</"+l.last()+">"==k.replace(/ /ig,""))f=a.substring(0,g),a=a.substring(b),a=f+"</"+l.last()+">"+a,f=!0;else if(0==
a.indexOf("</")){if(b=a.match(z))a=a.substring(b[0].length),b[0].replace(z,e),f=!1}else if(0==a.indexOf("<"))if(b=a.match(r))a=a.substring(b[0].length),b[0].replace(r,h),f=!1;else if(b=a.match(t))a=a.substring(b[0].length),b[0].replace(t,h),f=!1;else{if("1"==DEXTTOP.G_CURREDITOR._config.removeIncorrectAttribute&&(b=a.indexOf("<"),k=a.indexOf(">"),0==b&&0<k)){var p=a.substring(0,k+1),n=g=b=0;0<p.indexOf('\ub9d1\uc740=""')?(b=p.indexOf('\ub9d1\uc740=""'),g=5,n=p.split('\ub9d1\uc740=""').length):0<p.indexOf("\ub9d1\uc740=''")&&
(b=p.indexOf("\ub9d1\uc740=''"),g=5,n=p.split("\ub9d1\uc740=''").length);if(2==n&&0<b&&(k=a.substring(k+1),n=p.substring(0,b).lastIndexOf(" "),n<b+g))if(a=p.substring(n,b+g),p=p.replace(a,""),a=p+k,b=a.match(r))a=a.substring(b[0].length),b[0].replace(r,h),f=!1;else if(b=a.match(t))a=a.substring(b[0].length),b[0].replace(t,h),f=!1}g=/^<([-a-zA-Z._]*@[-a-zA-Z._]*)()>/;if(b=a.match(g))a=a.substring(b[0].length),b[0].replace(g,h),f=!1}f&&(b=a.indexOf("<"),f=0>b?a:a.substring(0,b),a=0>b?"":a.substring(b),
c.chars&&(l.last()&&w[l.last()]&&"textarea"!=l.last()&&"script"!=l.last()&&0>l.indexOf("pre")&&0>l.indexOf("xmp")&&(b=!1,g=RegExp("\\S\\n","g"),g.test(f)&&(b=!0),g=RegExp("\\n\\S","g"),g.test(f)&&(b=!0),g=RegExp("\\S\\n\\S","g"),g.test(f)&&(b=!0),b?f=f.replace(/\n/g," "):(g=RegExp("\\n\\n","g"),g.test(f)&&""==f.trim()?f=f.replace(/\n\n/g,""):f==unescape("%20%20")&&(b=new RegExp(unescape("%20"),"g"),f=f.replace(b,"&nbsp;")))),"1"==DEXTTOP.G_CURREDITOR._config.replaceSpace&&d&&(b=new RegExp(unescape("%20%20"),
"g"),f=f.replace(b,"&nbsp; ")),c.chars(f)))}if(a==m)throw"Parse Error: "+a;m=a}e()};DEXT5_EDITOR.HTMLParser.HTMLtoXML=function(a,d){var c="",h=DEXTTOP.G_CURREDITOR._config.skipTagInParser;if(""!=h&&0==A){m=m.replace(/,/g,",,");m=","+m+",";for(var h=h.split(","),e=h.length,b=0;b<e;b++)m=m.replace(","+h[b]+",","");m=m.replace(/,,/g,",");m=m.replace(/^,/g,"");m=m.replace(/,$/g,"");w=q(m);A=!0}DEXT5_EDITOR.HTMLParser(a,d,{start:function(a,b,d){c+="<"+a;for(a=0;a<b.length;a++)c="href"==b[a].name||"src"==
b[a].name?c+(" "+b[a].name+"="+b[a].quotationmark+b[a].value+b[a].quotationmark):""!=b[a].quotationmark?c+(" "+b[a].name+"="+b[a].quotationmark+b[a].value+b[a].quotationmark):c+(" "+b[a].name+'="'+b[a].escaped+'"');c+=(d?"/":"")+">"},end:function(a){D[a]||(c+="</"+a+">")},chars:function(a){c+=a},comment:function(a,b){c="0"==DEXTTOP.G_CURREDITOR._config.removeComment||b?c+("\x3c!--"+a+"--\x3e"):c+""}});return c};DEXT5_EDITOR.HTMLParser.RemoveOfficeTag=function(a,d){if(""==a||void 0==a)return"";a=DEXT5_EDITOR.HTMLParser.RemoveOfficeTag2(a);
a=DEXTTOP.DEXT5.util.replaceOneSpaceToNbsp(a);d&&(a=a.replace(/(<span[^>]*>)\s<\/span>/gi,"$1&nbsp;</span>"),a=a.replace(/>\s+</g,"><"));return a};DEXT5_EDITOR.HTMLParser.RemoveOfficeTag2=function(a){var d=RegExp("<o:p></o:p>","gi");a=a.replace(d,"");d=RegExp("<o:p>\\s+</o:p>","gi");a=a.replace(d,"");d=RegExp("<o:p>&nbsp;</o:p>","gi");a=a.replace(d,"&nbsp;");d=RegExp("<o:p ([^>]+)></o:p>","gi");a=a.replace(d,"");d=RegExp("<o:p ([^>]+)>\\s+</o:p>","gi");a=a.replace(d,"");d=RegExp("<o:p ([^>]+)>&nbsp;</o:p>",
"gi");a=a.replace(d,"&nbsp;");d=RegExp("<w:sdt[^>]*>","gi");a=a.replace(d,"");d=RegExp("</w:sdt>","gi");a=a.replace(d,"");"1"==DEXTTOP.G_CURREDITOR._config.removeLangAttribute&&(d=RegExp('(<[^>]+)(lang=["]?en-us["])([^>]*>)',"gi"),d.test(a)&&(a=a.replace(d,"$1$3")));"1"==DEXTTOP.G_CURREDITOR._config.removeMsoClass&&(d=RegExp('(<[^>]+\\sclass=[\\"]?)(mso\\w+)([\\"]?[^>]*>)',"gi"),d.test(a)&&(a=a.replace(d,"$1$3")));d=RegExp("(<[^>]+)(mso-ascii-font-family\\s*:\\s*(&quot;)?[a-z\u3131-\ud7a3 ]*(&quot;)?;?)([^>]*>)",
"gi");d.test(a)&&(a=a.replace(d,"$1$5"));d=RegExp("<v:shapetype ([^>]+)>[\\s\\S]*?</v:shapetype>","gi");a=a.replace(d,"");d=RegExp("<v:shape [^>]+>[\\s\\S]*?(<img [^>]+>)*?</v:shape>","gi");a=a.replace(d,"$1");d=RegExp("<v:shape ([^>]+)>[\\s\\S]*?</v:shape>","gi");a=a.replace(d,"");return a=a.replace(/<\!\[if ppt\]>/gi,"")};DEXT5_EDITOR.HTMLParser.CheckNeedNestedHTML=function(a,d,c){var h=!1;"undefined"!=typeof d&&""!=d&&(v=d);d=[];var e="p";"undefined"!=typeof c&&""!=c&&(e=c);c=e.split(",");var b=
c.length;if(1<b)for(e=0;e<b;e++){var f=a.getElementsByTagName(c[e]);try{d=d.concat(Array.prototype.slice.call(f,0))}catch(l){for(var m=f.length,g=0;g<m;g++)d.push(f[g])}}else d=a.getElementsByTagName(e);u=JSON.parse(JSON.stringify(y));if(""!=DEXTTOP.G_CURREDITOR._config.cleanNestedTagOptions.removeTag){a=DEXTTOP.G_CURREDITOR._config.cleanNestedTagOptions.removeTag.split(",");for(e=a.length-1;0<=e;e--)c=u.indexOf(a[e]),-1<c&&u.splice(c,1);x=","+DEXTTOP.G_CURREDITOR._config.cleanNestedTagOptions.removeTag+
","}e=0;for(a=d.length;e<a;e++)if(DEXT5_EDITOR.HTMLParser.GetChildrenCount(d[e],!0)>v){h=!0;break}return h};DEXT5_EDITOR.HTMLParser.GetChildrenCount=function(a,d){var c=0;a.childNodes&&(c=DEXT5_EDITOR.HTMLParser.getChildrenCountForNestedHTML(a,d)-a.childNodes.length);return c};DEXT5_EDITOR.HTMLParser.getChildrenCountForNestedHTML=function(a,d){for(var c=0,h=a.childNodes.length,e=0;e<h;e++)1==a.childNodes[e].nodeType&&-1<x.indexOf(","+a.childNodes[e].tagName.toLowerCase()+",")&&(d&&(c+=DEXT5_EDITOR.HTMLParser.getChildrenCountForNestedHTML(a.childNodes[e],
d)),c++);return c};DEXT5_EDITOR.HTMLParser.CleanNestedHtml=function(a,d,c,h,e){function b(a){for(var b="",c=Array(a.childNodes.length),d=0;d<c.length;d++){c[d]=[];c[d].push(a.childNodes[d]);f(a.childNodes[d],c[d]);var e=d,g=c[d],l=[],k=0;a:for(;k<g.length;k++){for(var h=0;h<l.length;h++)if(l[h]==g[k])continue a;l[l.length]=g[k]}c[e]=l;b+=c[d].join("")}return b}function f(a,b){for(var d=a.childNodes,c=0;c<d.length;c++)b.push(d[c]),d[c].hasChildNodes()&&1==d[c].nodeType&&"table"!=d[c].nodeName.toLowerCase()&&
f(d[c],b);for(var d=0,e;d<b.length;d++){c=b[d];if(1==c.nodeType)if("table"==c.nodeName.toLowerCase())c=c.outerHTML;else{e=c.nodeName;if(-1==(" "+u.join(" ").toUpperCase()+" ").search(" "+e.toUpperCase()+" ")){b.splice(d,1);d--;continue}e=c;for(var g="",k=0,h=void 0;k<e.attributes.length;k++)h=e.attributes[k],1==h.specified&&("style"==h.name?(h=l(e),""!=h&&(g+=' style="'+l(e)+'"')):""!=h.value&&(g+=" "+h.name+'="'+h.value+'"'));e=g;c="<"+c.nodeName.toLowerCase()+e+">"}else 3==c.nodeType&&(c=c.nodeValue.replace(/\n/g,
""),c=c.replace(/(\s)\s+/g,"$1"),c=c.replace(/</g,"&lt;"),c=c.replace(/>/g,"&gt;"));b[d]=c}return b}function l(a){for(var b="",c=0,d=m.length,e;c<d;c++)a.currentStyle?e=a.currentStyle[m[c]]:window.getComputedStyle&&(e=document.defaultView.getComputedStyle(a,null).getPropertyValue(m[c])),b+=m[c]+":"+e+";";return b}var m=[];u=JSON.parse(JSON.stringify(y));if(""!=a._config.cleanNestedTagOptions.removeTag){for(var g=a._config.cleanNestedTagOptions.removeTag.split(","),k=g.length-1;0<=k;k--){var p=u.indexOf(g[k]);
-1<p&&u.splice(p,1)}x=","+a._config.cleanNestedTagOptions.removeTag+","}0<a._config.cleanNestedTagOptions.allowStyle.length&&(m=a._config.cleanNestedTagOptions.allowStyle);"undefined"!=typeof c&&""!=c&&(v=parseInt(c));k="p";"undefined"!=typeof h&&""!=h&&(k=h);h=a._DOC;"undefined"!=typeof e&&""!=e&&(h=e);var n=[];e=k.split(",");c=e.length;if(1<c)for(k=0;k<c;k++){g=h.getElementsByTagName(e[k]);try{n=n.concat(Array.prototype.slice.call(g,0))}catch(q){for(var p=g.length,r=0;r<p;r++)n.push(g[r])}}else n=
h.getElementsByTagName(k);e=!1;k=0;for(c=n.length;k<c;k++)if(DEXT5_EDITOR.HTMLParser.GetChildrenCount(n[k],!0)>v){e=!0;break}if(e)if(h&&h!=a._DOC)try{k=0;c=n.length;for(var t;k<c;k++)DEXT5_EDITOR.HTMLParser.GetChildrenCount(n[k],!0)>v&&(t=b(n[k]),t=DEXT5_EDITOR.HTMLParser.HTMLtoXML(t),n[k].innerHTML=t);return h.innerHTML}catch(w){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}else showProcessingBackground(),setTimeout(function(){a._BODY.contentEditable=!1;try{if("2"==d)DEXTTOP.DEXT5.DextCommands("select_all",
a.ID),DEXTTOP.DEXT5.DextCommands("remove_css",a.ID),DEXTTOP.DEXT5.DextCommands("remove_format",a.ID),a._FRAMEWIN.setFocusToBody(),setTimeout(function(){a._FRAMEWIN.doSetCaretPosition(a._BODY.firstChild,0)},20);else for(var c=0,e=n.length,f;c<e;c++)DEXT5_EDITOR.HTMLParser.GetChildrenCount(n[c],!0)>v&&(f=b(n[c]),f=DEXT5_EDITOR.HTMLParser.HTMLtoXML(f),n[c].innerHTML=f)}catch(g){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}hideProcessingBackground();a._BODY.contentEditable=!0},G_Progress_LoadTime)};
DEXT5_EDITOR.HTMLParser.makeMap=function(a){return q(a)}})();
