function htmlTagRevision(a,b,c){if(0<DEXTTOP.G_CURREDITOR._config.htmlCorrectionLimitLength&&a.length>DEXTTOP.G_CURREDITOR._config.htmlCorrectionLimitLength)return a;var d=a;if(""!=d&&(DEXTTOP.DEXT5.browser.ie&&11>=DEXTTOP.DEXT5.browser.ieVersion||DEXTTOP.DEXT5.browser.gecko))try{var e=d.toLowerCase().indexOf("<body"),f=d.toLowerCase().lastIndexOf("<body");if(-1<e&&-1<f&&e!=f)return a;if("ieplugin"!=DEXTTOP.G_CURREDITOR._config.runtimes&&-1<d.indexOf("mso-fareast-font-family")){var g=RegExp("<[^>]+style=(.*?)>",
"gi"),h="",e=!1;try{var l=d.match(g);if(l){for(var k=l.length,g=0;g<k;g++)d=d.replace(l[g],"_DEXT_T_S{"+g+"}_");for(g=0;g<k;g++){var m=l[g];-1<m.indexOf("-font-family")&&(m=m.replace("-font-family","-font-dext-family"));f=!1;0>m.indexOf("font-family")&&(f=!0);-1<m.indexOf("-font-dext-family")&&(m=m.replace("-font-dext-family","-font-family"));f&&(m=m.replace(/mso-fareast-font-family/gi,"font-family"));d=d.replace("_DEXT_T_S{"+g+"}_",m)}}}catch(r){e=!0}e&&(d=a)}b&&(d=DEXT5_EDITOR.HTMLParser.RemoveOfficeTag(d,
c));var h=d.toLowerCase(),n=realValue2=d,p=h.lastIndexOf("<body"),q=h.indexOf("</body");if(-1<p&&-1<q)try{var t=n.substring(q),u=n.substring(p).indexOf(">"),v=n.substring(0,p+u+1),d=n.substring(p+u+1,q)}catch(w){p=q=-1,d=realValue2}realValue2=null;d=DEXT5_EDITOR.HTMLParser.HTMLtoXML(d,c);-1<p&&-1<q&&(d=v+d+t)}catch(x){return a}else if(d="1"==DEXTTOP.G_CURREDITOR._config.removeComment?d.replace(/(<style[^>]*>\s*\x3c!--)|(\x3c!--.*?--\x3e)|(\x3c!--[\w\W\n\s]+?--\x3e)/gi,"$1"):d.replace(/--\x3e\s</gi,
"--\x3e<"),"1"==DEXTTOP.G_CURREDITOR._config.removeCarriageReturnInTag)try{for(g=RegExp("(<[^>]*?)\n([^]*?>)","gi");g.test(d);)d=d.replace(g,"$1 $2")}catch(y){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}return d}var G_wordProcessorType="";
function SetCorrectOfficeHtml(a){var b=a;if(-1<a.indexOf("<meta name=ProgId content=Word.Document>")||-1<a.indexOf('<meta name=Generator content="Microsoft Word'))G_wordProcessorType="DOC",a=GetMsWordHtml(a);else if(-1<a.indexOf("<meta name=ProgId content=Excel.Sheet>"))G_wordProcessorType="XLS",a=GetMsExcelHtml(a);else if(-1<a.indexOf("<meta name=ProgId content=PowerPoint.Slide>")){if(G_wordProcessorType="PPT",a=GetMsPptHtml2(a),"1"==DEXTTOP.G_CURREDITOR._config.removeTdStyleInPastePpt){for(var c=
RegExp("<(td|th)([^>]*?)style='([^']*?)(font-size:18.0pt;)([^']*?)'>","gi");c.test(a);)a=a.replace(c,"<$1$2style='$3$5'>");for(c=RegExp('<(td|th)([^>]*?)style="([^"]*?)(font-size:18.0pt;)([^"]*?)">',"gi");c.test(a);)a=a.replace(c,'<$1$2style="$3$5">');for(c=RegExp("<(td|th)([^>]*?)style='([^']*?)(font-family:Arial;)([^']*?)'>","gi");c.test(a);)a=a.replace(c,"<$1$2style='$3$5'>");for(c=RegExp('<(td|th)([^>]*?)style="([^"]*?)(font-family:Arial;)([^"]*?)">',"gi");c.test(a);)a=a.replace(c,'<$1$2style="$3$5">')}}else if(-1<
a.indexOf('<meta name=Generator content="Jungum Global">'))G_wordProcessorType="GUL",a=GetJungumHtml(a);else if(isHwpPasteAction(a))G_wordProcessorType="HWP",a=GetHanHwpHtml(a);else if(-1<a.indexOf(' xmlns:m="http://schemas.microsoft.com/office/')){if(G_wordProcessorType="PPT",a=GetMsPptHtml2(a),"1"==DEXTTOP.G_CURREDITOR._config.removeTdStyleInPastePpt){for(c=RegExp("<(td|th)([^>]*?)style=('|\")([^']*?)(font-size:18.0pt;)([^']*?)('|\")>","gi");c.test(a);)a=a.replace(c,"<$1$2style=$3$4$6$7>");for(c=
RegExp("<(td|th)([^>]*?)style=('|\")([^']*?)(font-family:Arial;)([^']*?)('|\")>","gi");c.test(a);)a=a.replace(c,"<$1$2style=$3$4$6$7>")}}else-1<a.indexOf('<meta name=Generator content="Microsoft')?(G_wordProcessorType="DOC",a=GetMsWordHtml(a)):DEXTTOP.DEXT5.browser.ie||(b=a.indexOf("\x3c!--StartFragment--\x3e"),c=a.lastIndexOf("\x3c!--EndFragment--\x3e"),-1<b&&-1<c&&(b=a.substr(b+20),c=b.lastIndexOf("\x3c!--EndFragment--\x3e"),-1<c&&(a=b=b.substring(0,c))));a=DEXTTOP.DEXT5.util.replaceAll(a,"<![if !supportEmptyParas]>",
"");a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--[if !supportEmptyParas]--\x3e","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--[if !supportLists]--\x3e","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--[endif]--\x3e","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--StartFragment--\x3e","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--EndFragment--\x3e","");return a=DEXTTOP.DEXT5.util.replaceAll(a,"<![if ppt]>","")}
function GetMsWordHtml(a){var b=a,c,b=a.indexOf("/* Style Definitions */"),d=a.indexOf("</head>");-1<b&&-1<d&&(b=a.substr(b+23),d=b.indexOf("</head>"),-1<d&&(c=b.substring(0,d),c=GetStyleMap(c)));var b=a,d=!1,e="\x3c!--StartFragment--\x3e",f="\x3c!--EndFragment--\x3e",g=a.indexOf(e),h=a.indexOf(f);if(-1==g&&-1==h){var e="<body ",f="</body>",l=a.indexOf(e);-1<l&&(h=a.indexOf(">",l),e=a.Mid(l,h-l+1),g=a.indexOf(e),h=a.indexOf(f))}if(-1<g&&-1<h&&(b=a.substr(g+e.length),h=b.indexOf(f),-1<h)){for(;;)if(a=
b.indexOf(f,h+f.length),-1<a)h=a;else break;a=b=b.substring(0,h);d=!0}if(d){a=b;var k="<div class=WordSection1>",f=a.indexOf(k);-1==f&&(k='<div class="WordSection1">',f=a.indexOf(k));-1<f&&(k=DEXTTOP.DEXT5.util.replaceAll(a,k,""),k.length!=a.length&&(a=k,k=a.lastIndexOf("/"),-1<k&&(a=a.substring(0,k-1))));e="\x3c!--[if supportFields]>";for(f="<![endif]--\x3e";;){g=a.indexOf(e);-1<g&&(h=a.indexOf(f,g+e.length));k=a.length;if(g>k||h>k)break;if(-1<g&&-1<h){if(g<h){var m,b=a.substring(0,g);m=a.substr(h+
f.length);a=b+m}}else break;h=-1}}if(d)try{a=replaceMsComment("\x3c!--[if gte vml 1]>","<![endif]--\x3e",a,!0),a=replaceMsComment("\x3c!--[if mso & !supportInlineShapes & supportFields]>","<![endif]--\x3e",a,!0),a=replaceMsComment("<![if !mso]>","<![endif]>",a),a=a.replace(/<!\[if !vml\]>((.|\s|\n)*?)<!\[endif\]>/gi,"$1"),a=a.replace(/\x3c!--\[if !mso & vml\]>((.|\s|\n)*?)<!\[endif\]--\x3e/gi,"$1")}catch(r){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}e="\x3c!--[if gte mso 9]>";f="<![endif]--\x3e";
try{for(;;){g=a.indexOf(e);if(-1<g)h=a.indexOf(f,g+e.length);else break;k=a.length;if(g>k||h>k){a=DEXTTOP.DEXT5.util.replaceAll(a,e,"");a=DEXTTOP.DEXT5.util.replaceAll(a,f,"");break}if(-1<g&&-1<h)g>h?(b=a.substring(0,g),m=a.substr(g),b=DEXTTOP.DEXT5.util.replaceAll(b,f,"")):(b=a.substring(0,g),m=a.substr(h+f.length)),a=b+m;else break}}catch(n){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}a=a.replace(/\x3c!--\[if .*?\]>[\s\S]*?<!\[endif\]--\x3e/g,"");d&&(a=DEXTTOP.DEXT5.util.replaceAll(a,
"><![endif]></span>"," /></span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]></span>","</span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"</span><![endif]>","</span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>",""),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![if !vml]>",""));a=RepaireSpanInImageTag4MsWord(a);if(0<DEXTTOP.G_CURREDITOR._config.clipImageHex.length){try{var p=RegExp("<img[^>]+file://[^>]+>","gi"),q=a.match(p);if(q){var t=q.length;if(t==DEXTTOP.G_CURREDITOR._config.clipImageHex.length)for(var u=
0;u<t;u++){var v=DEXTTOP.DEXT5.util.hexToBytes(DEXTTOP.G_CURREDITOR._config.clipImageHex[u].hex),v=DEXTTOP.DEXT5.util.bytesToBase64(v),p=/<img[^>]*src=["']?([^>"']+)["']?[^>]*>/;if(p.test(q[u])){var w=q[u].replace(RegExp.$1,"data:"+DEXTTOP.G_CURREDITOR._config.clipImageHex[u].type+";base64,"+v);a=a.replace(q[u],w)}}}else{var x=a.match(RegExp("<v:imagedata[^>]+file://[^>]+>","gi"));if(x&&(t=x.length,t==DEXTTOP.G_CURREDITOR._config.clipImageHex.length))for(u=0;u<t;u++)v=DEXTTOP.DEXT5.util.hexToBytes(DEXTTOP.G_CURREDITOR._config.clipImageHex[u].hex),
v=DEXTTOP.DEXT5.util.bytesToBase64(v),w="<img",p=/<v:imagedata[^>]*style=["']?([^>"']+)["']?[^>]*>/,p.test(x[u])&&(w+=' style="'+RegExp.$1+'" '),w+=' src="data:'+DEXTTOP.G_CURREDITOR._config.clipImageHex[u].type+";base64,"+v+'">',a=a.replace(x[u],w)}}catch(y){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}DEXTTOP.G_CURREDITOR._config.clipImageHex=[]}a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:rect ","<div ");a=DEXTTOP.DEXT5.util.replaceAll(a,"</v:rect>","</div>");a=DEXTTOP.DEXT5.util.replaceAll(a,
"<v:shadow ","<hr ");a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:shape ","<span ");a=DEXTTOP.DEXT5.util.replaceAll(a,"</v:shape>","</span>");a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:imagedata","<img border=0");a=DEXTTOP.DEXT5.util.replaceAll(a,"<![if !supportLists]>","");a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>","");return a=setPasteClassStyle(c,a,!0)}
function GetMsExcelHtml(a){var b=a,c,b=a.indexOf("<style>"),d=a.indexOf("</head>");-1<b&&-1<d&&(b=a.substr(b+7),d=b.indexOf("</head>"),-1<d&&(c=b.substring(0,d),c=GetStyleMap(c)));var b=a,d=!1,e=a.indexOf("<table"),f=a.indexOf("</body>");-1<e&&-1<f&&(b=a.substr(e),f=b.indexOf("</body>"),-1<f&&(b=b.substring(0,f),d=!0));if(d){d=!1;a=b;try{a=replaceMsComment("\x3c!--[if gte vml 1]>","<![endif]--\x3e",a,!0),a=a.replace(/<!\[if !vml\]>((.|\s|\n)*?)<!\[endif\]>/gi,"$1"),a=a.replace(/\x3c!--\[if !mso & vml\]>((.|\s|\n)*?)<!\[endif\]--\x3e/gi,
"$1")}catch(g){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}}d&&(a=DEXTTOP.DEXT5.util.replaceAll(a,"></span><![endif]>"," /></span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"</span><![endif]>","</span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>",""),b=_T("<![if !vml]>"),a=DEXTTOP.DEXT5.util.replaceAll(a,b,""));a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:rect ","<div ");a=DEXTTOP.DEXT5.util.replaceAll(a,"</v:rect>","</div>");a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:shadow ","<hr ");a=DEXTTOP.DEXT5.util.replaceAll(a,
"<v:shape ","<span ");a=DEXTTOP.DEXT5.util.replaceAll(a,"</v:shape>","</span>");a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:imagedata","<img border=0");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--StartFragment--\x3e","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--EndFragment--\x3e","");b=a.indexOf("<col ");-1<b&&(a=a.substring(0,b)+"\n<colgroup>\n"+a.substring(b,a.length+1));b=a.indexOf("<tr ");-1<b&&(a=a.substring(0,b)+"\n<tbody>\n"+a.substring(b,a.length+1),b=a.lastIndexOf("</table>"),-1<b&&(a=a.substring(0,
b)+"\n</tbody>\n"+a.substring(b,a.length+1)));a=setPasteClassStyle(c,a,!1,!0);"1"==DEXTTOP.G_CURREDITOR._config.officeLineFix&&(a=DEXTTOP.DEXT5.util.replaceAll(a,"border-left:none;",""),a=DEXTTOP.DEXT5.util.replaceAll(a,"border-top:none;",""),a=DEXTTOP.DEXT5.util.replaceAll(a,"border-right:none;",""),a=DEXTTOP.DEXT5.util.replaceAll(a,"border-bottom:none;",""));a=DEXTTOP.DEXT5.util.replaceAll(a,"\r","");return a=DEXTTOP.DEXT5.util.replaceAll(a,"\n","")}
function GetMsPptHtml2(a){var b=a,c,b=a.indexOf("\x3c!--tr"),d=a.indexOf("</head>");-1<b&&-1<d&&(b=a.substr(b+6),d=b.indexOf("</head>"),-1<d&&(c=b.substring(0,d),c=GetStyleMap(c)));b=a.indexOf("\x3c!--StartFragment--\x3e");d=a.indexOf("\x3c!--EndFragment--\x3e");if(-1<b&&-1<d&&(b=a.substr(b+20),d=b.indexOf("\x3c!--EndFragment--\x3e"),-1<d)){for(;;)if(a=b.indexOf("\x3c!--EndFragment--\x3e",d+18),-1<a)d=a;else break;a=b=b.substring(0,d)}a=setPasteClassStyle(c,a);"1"==DEXTTOP.G_CURREDITOR._config.officeLineFix&&
(a=DEXTTOP.DEXT5.util.replaceAll(a,"border-right:none;",""));c=RegExp("<spanstyle","ig");a=a.replace(c,"<span style");return a=a.replace(c,"<p style")}
function GetJungumHtml(a){if("1"==DEXTTOP.G_CURREDITOR._config.useHtmlProcessByWorker)return a;var b=a.indexOf("<body>"),c=a.indexOf("</body>"),d=!1;-1<b&&-1<c&&(strTemp=a.substr(b+6),c=strTemp.indexOf("</body>"),-1<c&&(a=strTemp=strTemp.substring(0,c),d=!0));if(d){b=document.createElement("div");b.innerHTML=a;a=b.getElementsByTagName("table");for(var c=a.length,e,f,d=0;d<c;d++)""!=a[d].getAttribute("width")&&(e=parseInt(a[d].getAttribute("width"),10)),""!=a[d].getAttribute("height")&&(f=parseInt(a[d].getAttribute("height"),
10)),e&&(a[d].style.width=e+"px"),f&&(a[d].style.height=f+"px");a=b.innerHTML}return a}
function GetHanHwpHtml(a){var b=a,b=">\x3c!--p.",c="</head>",d,e=a.indexOf(b),f=a.indexOf(c);-1==e&&(b=">\r\n\x3c!--p.",e=a.indexOf(b));-1==e&&(b="\x3c!--p.",e=a.indexOf(b));-1==e&&(b="\x3c!--@list",e=a.indexOf(b));-1==f&&(c="</HEAD>",f=a.indexOf(c));-1<e&&-1<f&&(b=a.substr(e+(b.length-3)),f=b.indexOf(c),-1<f&&(d=b.substring(0,f),d=GetStyleMap(d)));b=a;c=!1;e=a.indexOf("\x3c!--StartFragment--\x3e");f=a.indexOf("\x3c!--EndFragment--\x3e");if(-1<e&&-1<f&&(b=a.substr(e+20),f=b.indexOf("\x3c!--EndFragment--\x3e"),
-1<f)){for(;;)if(c=b.indexOf("\x3c!--EndFragment--\x3e",f+18),-1<c)f=c;else break;b=b.substring(0,f);c=!0}if(c){c=!1;a=b;if("1"==DEXTTOP.G_CURREDITOR._config.compatibility.hwpPasteImageInHtml5)try{var g=a.match(/\x3c!--\[data-hwpjson]({[\s\S]*?})--\x3e/i);if(g){var h=JSON.parse(g[1]);if(h){var l={};a=a.replace(/(<img[^>]*\bsrc=")file:\/\/\/.*?("[\s\S]*?>)/gi,function(b,c,d){var f=b;try{var g=b.match(/v:shapes="(.*?)"/),e=b.match(/alt="([\s\S]*?)"/);if(g&&e){var k=a.match(new RegExp('<v:shape[^>]*\\bid="'+
g[1]+'" [\\s\\S]*?src="(.*?)"[\\s\\S]*?<\\/v:shape>',"i"));if(k){var q=k[1];if("string"!=typeof l[q]){var m=e[1],m=m.replace(/&#xA;/g,"\n");b="";for(var p in h.cs){var n=h.cs[p];if("string"==typeof n.sc&&n.sc==m&&n.rc&&n.rc.img&&"string"==typeof n.rc.img.bi&&0<n.rc.img.bi.length){b=n.rc.img.bi;""==n.sc&&""==n.sc&&delete h.cs[p];break}}if(""!=b&&(m="",h.bidt&&"string"==typeof h.bidt[b])){var t=DEXTTOP.DEXT5.util.getExtensionFromFileName(b);"jpg"==t&&(t="jpeg");m="data:image/"+t+";base64,"+h.bidt[b];
l[q]=m;delete h.bidt[b]}}var r=l[q];"string"==typeof r&&0<r.length&&(f=c+r+d)}}}catch(z){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}return f});var k=RegExp("(<td[^>]*\\bbackground:)&quot;(c:.*?)&quot;([\\s\\S]*?>)","gi"),m=a.match(k),g=0;m&&(g=m.length);for(f=b=0;f<g;f++){var r=m[f].match(/&quot;(c:.*?)&quot;/i)[1];if("string"==typeof l[r])b++;else if(h.bidt)for(var n in h.bidt)if("string"==typeof h.bidt[n]){var p=DEXTTOP.DEXT5.util.getExtensionFromFileName(n);"jpg"==p&&(p="jpeg");l[r]=
"data:image/"+p+";base64,"+h.bidt[n];delete h.bidt[n];b++;break}}if(h.bidt)for(n in h.bidt)"string"==typeof h.bidt[n]&&b++;0<g&&g==b&&(a=a.replace(k,function(a,b,c,d){try{var f=l[c];"string"==typeof f&&0<f.length&&(a=b+"url("+f+"); background-repeat: no-repeat; background-size: 100% 100%;"+d)}catch(g){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}return a}))}}}catch(q){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}try{a=replaceMsComment("\x3c!--[if gte vml 1]>","<![endif]--\x3e",
a,!0),a=a.replace(/<!\[if !vml\]>((.|\s|\n)*?)<!\[endif\]>/gi,"$1"),a=a.replace(/\x3c!--\[if !mso & vml\]>((.|\s|\n)*?)<!\[endif\]--\x3e/gi,"$1")}catch(t){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}}a=setPasteClassStyle(d,a);c&&(a=DEXTTOP.DEXT5.util.replaceAll(a,"/><![endif]>"," />"),a=DEXTTOP.DEXT5.util.replaceAll(a,"</span><![endif]>","</span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>",""),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![if !vml]>",""));a=DEXTTOP.DEXT5.util.replaceAll(a,
"<![if !supportEmptyParas]>&nbsp;<![endif]>","");a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>","");for(k=RegExp("(<p [^>]*)(background:#000000;)","gi");k.test(a);)a=a.replace(k,"$1");for(k=RegExp("(<[^>]*)(background: rgb\\(255, 255, 255\\);)","gi");k.test(a);)a=a.replace(k,"$1");for(k=RegExp("(<[^>]*)(background:#ffffff;)","gi");k.test(a);)a=a.replace(k,"$1");for(k=RegExp("(<[^>]*)(mso-fareast-)","gi");k.test(a);)a=a.replace(k,"$1");for(k=RegExp("(<[^>]*)(mso-hansi-)","gi");k.test(a);)a=a.replace(k,
"$1");for(k=RegExp("(<[^>]*)(mso-ascii-)","gi");k.test(a);)a=a.replace(k,"$1");for(k=RegExp("(<[^>]*)(mso-bidi-)","gi");k.test(a);)a=a.replace(k,"$1");for(k=RegExp("(<[^>]*)(mso-)","gi");k.test(a);)a=a.replace(k,"$1");return a}
function GetStyleMap(a){var b={};a=a.split("}");for(var c="",d=a.length,e=0;e<d;e++){var f=a[e].split("{"),g=f.length;if(2==g)for(var h=0;h<g-1;h++){var l=f[h],k=f[h+1],l=l.replace(/\r\n/g,""),l=l.replace(/\r/g,""),l=l.replace(/\n/g,""),l=l.replace(/\t/g,""),k=k.replace(/\r\n/g,""),k=k.replace(/\r/g,""),k=k.replace(/\n/g,""),k=k.replace(/\t/g,"");""==c&&"td"==l&&(c=k=DEXTTOP.DEXT5.util.replaceAll(k,"'",'"'));if(0<l.length)if(k=DEXTTOP.DEXT5.util.replaceAll(k,"'",'"'),"."==l.substring(0,1)&&0<c.length)if(k=
k.replace(/font-family:&quot,/g,"font-family:"),"XLS"==G_wordProcessorType){var m=k.indexOf("vertical-align:"),r=c+k;if(-1<m)try{var n=k.substring(m,k.length).split(";")[0];if(!isNaN(n.split(":")[1]))var p=c.indexOf("vertical-align:"),q=c.substring(p,c.length).split(";")[0],k=k.replace(n+";",""),r=c.replace(q,"vertical-align:middle")+k}catch(t){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}b[l]=r}else b[l]=c+k;else b[l]=k}}return b}
function RepaireSpanInImageTag4MsWord(a){for(var b,c,d,e,f;;)if(b="<v:shape ",c=a.indexOf(b),-1==c&&(b="<v:shape\r\n",c=a.indexOf(b)),-1<c)if(d=a.indexOf("</v:shape>",c+b.length),e=a.indexOf("<v:imagedata",c+b.length),-1<d&&-1<e&&e<d)if(f=a.indexOf("/>",e+12),-1<f)e=a.substring(0,c),c=a.substr(c,f-c+2),a=a.substr(d+10),c=DEXTTOP.DEXT5.util.replaceAll(c,"<v:imagedata"," "),c=DEXTTOP.DEXT5.util.replaceAll(c,b,"<v:imagedata "),c=DEXTTOP.DEXT5.util.replaceAll(c,">"," "),c=DEXTTOP.DEXT5.util.rtrim(c),
c+=">",c=DEXTTOP.DEXT5.util.replaceAll(c,"/>"," />"),c=DEXTTOP.DEXT5.util.replaceAll(c,"  "," "),a=e+c+a;else break;else break;else break;return a}
function setPasteClassStyle(a,b,c,d){var e=function(a){a=DEXTTOP.DEXT5.util.replaceAll(a,"hairline ","dotted ");a=DEXTTOP.DEXT5.util.replaceAll(a," hairline;"," dotted;");a=DEXTTOP.DEXT5.util.replaceAll(a,"dot-dot-dash ","dotted ");a=DEXTTOP.DEXT5.util.replaceAll(a," dot-dot-dash;"," dotted;");a=DEXTTOP.DEXT5.util.replaceAll(a,"dot-dash ","dotted ");a=DEXTTOP.DEXT5.util.replaceAll(a," dot-dash;"," dotted;");a=DEXTTOP.DEXT5.util.replaceAll(a,"dot-dash-slanted ","dotted ");return a=DEXTTOP.DEXT5.util.replaceAll(a,
" dot-dash-slanted;"," dotted;")};if("HWP"==G_wordProcessorType&&"1"==DEXTTOP.G_CURREDITOR._config.compatibility.hwpPasteBulletInHtml5){var f={};b=b.replace(/<p[^>]*style="[^"]*mso-list:\s*l[^"]*"[^>]*>/gi,function(b){try{var c=b.match(/mso-list:(.*?);/);if(c){var d=c[1].split(" "),g=a["@list "+d[0]],c=!1;"string"==typeof g&&""!=g&&-1<g.indexOf("mso-list-type:numberic;")&&(c=!0);var e="@list "+d[0]+":"+d[1],h=a[e],d="";if(c){if("number"!=typeof f[e]){var k=h.match(/mso-level-start-at:(.*?);/);k&&
(f[e]=parseInt(k[1],10))}else f[e]++;"number"==typeof f[e]&&(d=f[e]+".")}else{var l=h.match(/mso-level-text:(.*?);/);if(l){var m=l[1],n=RegExp("[a-zA-Z]","g"),e=!1;-1<["\u009f","\u00a7","\u00a4","\u00fe","\u00fc"].indexOf(m)&&(e=!0);d=m;if(n.test(m)||e){var m="",p=h.match(/font-family:(.*?);/);p&&(m=p[1]);d='<span style="font-family:'+m+';">'+d+"</span>"}}}""!=d&&(b=b.replace(">",">"+d+" "))}}catch(r){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}return b})}if(d&&null!=a.td){var g=e(a.td);
b=b.replace(RegExp("(<td[^>]*(.*?))","gi"),function(a){return 0>a.indexOf("class")?setStyleToNonClass(a,"td",g):a})}for(var h in a){d=e(a[h]);"HWP"==G_wordProcessorType&&/mso-style-name:[ "']xl[0-9]/i.test(d)&&(d=d.replace(/background:.*?;/gi,""));h=h.split(",")[0];h=h.substring(h.indexOf("."));if("."==h.substring(0,1)){var l=new RegExp("<[^>]*class=(\"|'|)"+h.substr(1)+"(\"|'|) [\\s\\S]*?>","i");b=setStyleToClass(b,l,h,d);l=new RegExp("<[^>]*class=(\"|'|)"+h.substr(1)+"(\"|'|)>","i");b=setStyleToClass(b,
l,h,d)}if(c&&(l=h.toLowerCase(),(-1<l.indexOf("h1")||-1<l.indexOf("h2")||-1<l.indexOf("h3")||-1<l.indexOf("h4")||-1<l.indexOf("h5")||-1<l.indexOf("h6")||-1<l.indexOf("em"))&&""!=d&&(l=new RegExp("<"+h+"[^>]*>","igm"),l=b.match(l)))){d=d.replace(/"/g,"&quot;");for(var k=l.length,m=0;k>m;m++){var r=b.substring(0,b.indexOf(l[m])),n=l[m];b=b.substring(b.indexOf(l[m])+l[m].length);var p=/(style=("|'|))/i,n=1==p.test(n)?n.replace(p,RegExp.$1+d):n.replace(new RegExp("<"+h,"i"),"<"+h+" style='"+d+"'");b=
r+n+b}}}return b}
function setStyleToClass(a,b,c,d){if(DEXTTOP.DEXT5.browser.DOMParserSupported){b=(new DOMParser).parseFromString("","text/html").createElement("div");b.innerHTML=a.replace(/&nbsp;&nbsp;/g,"&nbsp; ");var e=[];try{e=b.querySelectorAll(c)}catch(f){e=b.getElementsByClassName(c.substring(1))}for(var g=e.length-1;0<=g;g--){a=e[g];var h=c.substring(1);DEXTTOP.DEXT5.util.removeClass(a,h);h=a.className;"string"==typeof h&&""==h&&a.removeAttribute("class");var h=a.getAttribute("style"),l=d;"string"==typeof h&&
(l+=h);a.setAttribute("style",l)}a=b.innerHTML}else for(;h=b.exec(a);)e=a.substring(0,h.index),g=h[0].toString(),a=a.substr(h.index+h[0].length),h=/style=("|'|)/i,1==h.test(g)?(l=RegExp.$1,"'"==l?d=d.replace(/'/gi,'"'):'"'==l&&(d=d.replace(/"/gi,"'")),g=g.replace(h,"style="+l+d+" "),h=new RegExp("class=(\"|'|)"+c.substr(1)+"(\"|'|)","i"),g=g.replace(h,"")):(h=new RegExp("class=(\"|'|)"+c.substr(1)+"(\"|'|)","i"),g=g.replace(h,"style='"+d+"'")),a=e+g+a;return a}
function setStyleToNonClass(a,b,c){b=/style=("|'|)/i;if(1==b.test(a)){var d=RegExp.$1;"'"==d?c=c.replace(/'/gi,'"'):'"'==d&&(c=c.replace(/"/gi,"'"));a=a.replace(b,"style="+d+c+" ")}else a+=" style='"+c+"'";return a}function GetFontSizeForWordH1ToH7Tag(a){var b="",c=a.indexOf("font-size");-1<c&&(a=a.substr(c),c=a.indexOf(";"),-1<c&&(b=a.substring(0,c),b+=";"));return b}
function isHwpPasteAction(a){return-1<a.indexOf(">\x3c!--p.")||-1<a.indexOf('<META NAME="Generator" CONTENT="Hancom HWP')||-1<a.indexOf("\x3c!--[if !supportEmptyParas]--\x3e")||-1<a.indexOf("<meta")&&-1<a.indexOf("\x3c!--[data-hwpjson]")?!0:!1}
function replaceMsComment(a,b,c,d){try{for(var e=c;;){var f=c.indexOf(a),g=-1;if(-1<f)g=c.indexOf(b,f+a.length);else break;if(-1<f&&-1<g)c=1==d?c.substring(0,f)+c.substring(g+b.length):c.substring(0,f)+c.substring(f+a.length,g)+c.substring(g+b.length);else break}}catch(h){c=e}return c}
"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.officeClean&&(DEXTTOP.DEXT5.util.officeClean=function(a,b){if(""==a||void 0==a)return"";var c=null,d=[];a=a.replace(/\n( )+/g,"\n");-1<a.indexOf("hairline")&&(a=a.replace(/<[^>]+hairline/g,function(a){return a.replace("hairline","dotted")}));-1<a.indexOf(".0px")&&(a=a.replace(/<[^>]+\.0px/g,function(a){return a.replace(".0px","px")}));a=a.replace(/\t/g,"");a=DEXTTOP.DEXT5.util.removeOfficeDummyTag(a,"\x3c!--[if supportFields]>",
"<![endif]--\x3e");c=RegExp("<o:p></o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p>\\s+</o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p ([^>]+)></o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p ([^>]+)>\\s+</o:p>","gi");a=a.replace(c,"");c=RegExp("<w:sdt[^>]*>","gi");a=a.replace(c,"");c=RegExp("</w:sdt>","gi");a=a.replace(c,"");c=RegExp('<[^>]+(lang=["]?en-us["])[^>]*>',"gi");if(c=a.match(c))for(var d=c.length,e=0;e<d;e++){var f=c[e],g=RegExp('\\slang=[\\"]?en-us[\\"]?',"gi"),f=f.replace(g,"");a=a.replace(c[e],
f)}c=RegExp("<[^>]+(mso)[^>]*>","gi");if(c=a.match(c))for(d=c.length,e=0;e<d;e++)f=c[e],"1"==DEXTTOP.G_CURREDITOR._config.removeMsoClass&&(g=RegExp('\\sclass=[\\"]?(mso)\\w+[\\"]?',"gi"),f=f.replace(g,"")),f=f.replace(/&quot;/gi,"^"),g=RegExp("mso-[^:]+:\\^\\^(;?)","gi"),f=f.replace(g,""),g=RegExp('(\\s+)?mso-number-format:(\\s+)?"(.+?)"(\\s+)?;',"gi"),f=f.replace(g,""),g=RegExp('(\\s+)?mso-number-format:(\\s+)?"(.+?)"(\\s+)?;?',"gi"),f=f.replace(g,""),g=RegExp("\\s?mso-[\\w\uac00-\ud7a3\\-: ?'\"\\^@%\\.\\\\_]+; ?",
"gi"),f=f.replace(g,""),g=RegExp('\\s?mso-[\\w\uac00-\ud7a3\\-: ?\'"\\^@%\\.\\\\_]+" ?',"gi"),f=f.replace(g,'"'),g=RegExp("\\s?mso-[\\w\uac00-\ud7a3\\-: ?]+(['\"])","gi"),f=f.replace(g,"$1"),f=f.replace(/\^/gi,"&quot;"),a=a.replace(c[e],f);c=new RegExp("(<span[^>]*?raon_placeholder.*?>)(?:\\s|<br>|<br />|  | |)</span>","gim");a=a.replace(c,"$1"+unescape("%u200B")+"</span>");for(e=0;5>e;e++){d=["o:p","span","font"];g=d.length;for(f=0;f<g;f++)-1<a.indexOf("<"+d[f])&&(c=new RegExp("<"+d[f]+"[^>]*></"+
d[f]+">","gi"),a=a.replace(c,""),"span"!=d[f]&&(c=new RegExp("<"+d[f]+"[^>]*> </"+d[f]+">","gi"),a=a.replace(c,"&nbsp;")));d=["o","v","w","m","x"];g=d.length;for(f=0;f<g;f++)0==f&&(a=a.replace(/<o:p/gi,"<dexto:p")),-1<a.indexOf("<"+d[f])&&(c=new RegExp("<"+d[f]+":[^/>]+/>","gi"),a=a.replace(c,""),c=new RegExp("<"+d[f]+":[^>]+>[^<]*</"+d[f]+":[^>]+>","gi"),a=a.replace(c,""),"v"==d[f]&&(c=new RegExp("<"+d[f]+":[^>]+>","gi"),a=a.replace(c,""),c=new RegExp("</"+d[f]+":[^>]+>","gi"),a=a.replace(c,""))),
f==g-1&&(a=a.replace(/<dexto:p/gi,"<o:p"))}e="(<span[^>]*?raon_placeholder.*?>)("+unescape("%u200B")+"?)</span>";c=new RegExp(e,"gim");a=a.replace(c,"$1</span>");a=a.replace(/style=""/gi,"");a=a.replace(/style=''/gi,"");a=a.replace(/\s>/gi,">");a=DEXTTOP.DEXT5.util.replaceOneSpaceToNbsp(a);a=a.replace(/<\/td>&nbsp;<\/tr>/g,"</td></tr>");a=a.replace(/<\/td>&nbsp;<\/td>/g,"</td></td>");a=a.replace(/<\/th>&nbsp;<\/tr>/g,"</th></tr>");a=a.replace(/<\/th>&nbsp;<\/th>/g,"</th></th>");if(DEXTTOP.DEXT5.browser.ie&&
10>DEXTTOP.DEXT5.browser.ieVersion&&(!DEXTTOP.G_CURREDITOR.setTextPaste||"1"==DEXTTOP.G_CURREDITOR.setTextPasteMode)){var c=a.length,f=d=!1,h=g="",l="";if(-1==a.indexOf("<")&&-1==a.indexOf(">"))for(e=0;e<c;e++)g=a.charAt(e),h=a.charAt(e+1)," "!=g&&32!=g.charCodeAt(0)||" "!=h&&32!=h.charCodeAt(0)||(g="&nbsp;"),l+=g;else for(e=0;e<c;e++)g=a.charAt(e),h=a.charAt(e+1),"<"==g?(d=!1,f="p"==h.toLowerCase()?!0:!1):">"==g&&1==f?d=!0:1!=d||" "!=g&&32!=g.charCodeAt(0)||" "!=h&&32!=h.charCodeAt(0)||(g="&nbsp;"),
l+=g;a=l}"1"!=DEXTTOP.G_CURREDITOR.setTextPasteMode&&(DEXTTOP.G_CURREDITOR.setTextPaste=!1);0==b&&(a=DEXTTOP.DEXT5.util.removeLocalFileImage(a));return a});"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.removeLocalFileImage&&(DEXTTOP.DEXT5.util.removeLocalFileImage=function(a){return""==a||void 0==a?"":a=a.replace(RegExp("<(img)([^>]*?)src=('|\")(file://)[^>]+>","gi"),"")});
"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.removeOfficeDummyTag&&(DEXTTOP.DEXT5.util.removeOfficeDummyTag=function(a,b,c){var d=a;try{for(var e=a.indexOf(b),f=a.indexOf(c);-1<e&&-1<f;)var g=d.substring(0,e),h=d.substring(f+c.length),d=g+h,e=d.indexOf(b),f=d.indexOf(c)}catch(l){d=a}return d});"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.replaceAll&&(DEXTTOP.DEXT5.util.replaceAll=function(a,b,c){a&&""!=a&&(a=a.split(b).join(c));return a});
"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.replaceOneSpaceToNbsp&&(DEXTTOP.DEXT5.util.replaceOneSpaceToNbsp=function(a){var b=a,c,d="";try{for(var e="span font a b strong i em strike u sup sub".split(" "),f=e.length,g=0;g<f;g++){var h=!0,l=e[g];("font"==l||"b"==l||"em"==l||"sup"==l||"sub"==l)&&0>b.toLowerCase().indexOf("<"+l)&&(h=!1);if(h)for(var k=0;k<f;k++){d=b;c=new RegExp("<"+e[g]+" *([^>?+])*>(\\s+)</"+e[k]+">","gi");reg_exp2="u"==e[k]?new RegExp("</"+e[g]+">(\\s+)<"+
e[k]+"[^l]","gi"):new RegExp("</"+e[g]+">(\\s+)<"+e[k]+" *([^>?+])*>","gi");reg_exp3=new RegExp("<"+e[g]+" *([^>?+])*>(\\s+)<"+e[k]+">","gi");reg_exp4="u"==e[k]?new RegExp("</"+e[g]+">(\\s+)</"+e[k]+"[^l]","gi"):new RegExp("</"+e[g]+">(\\s+)</"+e[k]+" *([^>?+])*>","gi");try{var m=b.match(c);if(m)for(var r=m.length,n=0;n<r;n++){var p=m[n];if(!("b"==e[g]&&-1<p.toLowerCase().indexOf("<br")))var q=/>\s+</.exec(p),t=q[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),p=p.replace(q,t),b=b.replace(m[n],p)}if(m=
b.match(reg_exp2))for(r=m.length,n=0;n<r;n++)p=m[n],"b"==e[k]&&-1<p.toLowerCase().indexOf("<br")||(q=/>\s+</.exec(p),t=q[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),p=p.replace(q,t),b=b.replace(m[n],p));if(m=b.match(reg_exp3))for(r=m.length,n=0;n<r;n++)p=m[n],"b"==e[g]&&-1<p.toLowerCase().indexOf("<br")||(q=/>\s+</.exec(p),t=q[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),p=p.replace(q,t),b=b.replace(m[n],p));if(m=b.match(reg_exp4))for(r=m.length,n=0;n<r;n++)p=m[n],q=/>\s+</.exec(p),t=q[0].replace(RegExp("\\s\\s",
"gi"),"&nbsp;&nbsp;"),p=p.replace(q,t),b=b.replace(m[n],p)}catch(u){b=d}}}for(g=0;g<f;g++)if(h=!0,l=e[g],("font"==l||"b"==l||"em"==l||"sup"==l||"sub"==l)&&0>d.toLowerCase().indexOf("<"+l)&&(h=!1),h){"b"==l?(b=b.replace(/<br/gi,"<temp_br"),b=b.replace(/<\/br/gi,"</temp_br")):"u"==l&&(b=b.replace(/<ul/gi,"<temp_ul"),b=b.replace(/<\/ul/gi,"</temp_ul"));for(k=0;k<f;k++)c=new RegExp("/"+e[g]+">\\s<"+e[k],"gi"),b=b.replace(c,"/"+e[g]+">&nbsp;<"+e[k]),c=new RegExp("/"+e[g]+">\\s\\n<"+e[k],"gi"),b=b.replace(c,
"/"+e[g]+">&nbsp;<"+e[k]);"b"==l?(b=b.replace(/<temp_br/gi,"<br"),b=b.replace(/<\/temp_br/gi,"</br")):"u"==l&&(b=b.replace(/<temp_ul/gi,"<ul"),b=b.replace(/<\/temp_ul/gi,"</ul"))}}catch(v){b=a}return b});"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.rtrim&&(DEXTTOP.DEXT5.util.rtrim=function(a){return""==a?a:a.replace(/[\s\uFEFF\xA0]+$/,"")});
"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.hexToBytes&&(DEXTTOP.DEXT5.util.hexToBytes=function(a){for(var b=[],c=a.length/2,d=0,d=0;d<c;d++)b.push(parseInt(a.substr(2*d,2),16));return b});
"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.bytesToBase64&&(DEXTTOP.DEXT5.util.bytesToBase64=function(a){for(var b="",c=a.length,d=0;d<c;d+=3){var e=a.slice(d,d+3),f=e.length,g=[],h=void 0;if(3>f)for(h=f;3>h;h++)e[h]=0;g[0]=(252&e[0])>>2;g[1]=(3&e[0])<<4|e[1]>>4;g[2]=(15&e[1])<<2|(192&e[2])>>6;g[3]=63&e[2];for(h=0;4>h;h++)b+=h<=f?"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(g[h]):"="}return b});var htmlProcessUtilFunctionList={};
htmlProcessUtilFunctionList.htmlTagRevision=htmlTagRevision;htmlProcessUtilFunctionList.SetCorrectOfficeHtml=SetCorrectOfficeHtml;htmlProcessUtilFunctionList.GetMsWordHtml=GetMsWordHtml;htmlProcessUtilFunctionList.GetMsExcelHtml=GetMsExcelHtml;htmlProcessUtilFunctionList.GetMsPptHtml2=GetMsPptHtml2;htmlProcessUtilFunctionList.GetJungumHtml=GetJungumHtml;htmlProcessUtilFunctionList.GetHanHwpHtml=GetHanHwpHtml;htmlProcessUtilFunctionList.GetStyleMap=GetStyleMap;
htmlProcessUtilFunctionList.RepaireSpanInImageTag4MsWord=RepaireSpanInImageTag4MsWord;htmlProcessUtilFunctionList.setPasteClassStyle=setPasteClassStyle;htmlProcessUtilFunctionList.setStyleToClass=setStyleToClass;htmlProcessUtilFunctionList.GetFontSizeForWordH1ToH7Tag=GetFontSizeForWordH1ToH7Tag;htmlProcessUtilFunctionList.isHwpPasteAction=isHwpPasteAction;htmlProcessUtilFunctionList.replaceMsComment=replaceMsComment;htmlProcessUtilFunctionList["DEXTTOP.DEXT5.util.officeClean"]=DEXTTOP.DEXT5.util.officeClean;
