var raonk_console=window.console||{log:function(){}},KPHOTOTOP=parent;setPHOTOwindow();setPHOTOWINdocument();var SIL=[],Z=[],___=KPHOTOTOP.KPHOTOWIN.location,_0_,_1_,_7_;KPHOTOTOP.RAONKPHOTO=parent.RAONKPHOTO;parent.KPHOTOTOP=KPHOTOTOP;
var _R_O_="K",R=[],T=[],K__="fe",M1="IEludmianzwFsoraWQgUHJvZHVjdCBLZXkuIA==",M2="IExpY2ianzwVuorc2UgRXhwaXJlZC4g",M3="IEludmianzwFsoraWQgRG9tYWluLiA=",M4="IEludmianzwFsoraWQgVUkgTW9kdWxlIExpY2Vuc2UuIA==",G_RAONKCanvas=null,G_workProcessComplete=!1,G_workers=[],G_workerCount=4;SIL[0]="t";var K__=K__+"ab",G_drag,G_dragPopup,G_coordX,G_coordY,G_offsetX,G_offsetY,K__=K__+"CDE",K__=K__+"FA";R[0]="h";SIL[1]="u";
var K__=K__+"BG",G_originImgForResize=null,G_currentWidth=0,G_currentHeight=0,G_LastImgInstance=null,K__=K__+R[0];R[1]="t";var G_BeforeToolBar="";function setPHOTOwindow(){try{topURL=top.location.href,"undefined"==typeof topURL?(KPHOTOTOP.KPHOTOWIN=parent,KPHOTOTOP.IsCrossDomain=!0):(KPHOTOTOP.KPHOTOWIN=parent,KPHOTOTOP.IsCrossDomain=!1)}catch(b){KPHOTOTOP.KPHOTOWIN=parent,KPHOTOTOP.IsCrossDomain=!0}}K__+="i";
function setPHOTOWINdocument(){try{topURL=top.location.href,"undefined"==typeof topURL?(KPHOTOTOP.KPHOTODOC=parent.document,KPHOTOTOP.IsCrossDomain=!0):(KPHOTOTOP.KPHOTODOC=parent.document,KPHOTOTOP.IsCrossDomain=!1)}catch(b){KPHOTOTOP.KPHOTODOC=parent.document,KPHOTOTOP.IsCrossDomain=!0}}Z[0]="h";K__+="j";R[2]="t";function raonk_frame_loaded_event(b,c,a){(new RAONKPhoto_Editor(b,c,a)).start(c)}K__+="k";R[3]="p";K__+="l";K__+="m";
function RAONKPhoto_Editor(b,c,a){this._config=c;this._config.id=b;this._frame=a;this.frameWin=window;this.ID=b;KPHOTOTOP.RAONKPHOTO.RAONKMULTIPLE[a.frameID]=this;KPHOTOTOP.G_CURRKPHOTO=this;this.____={};this.isNew=!0;this.lastCmd="";_R_O_+="/";_R_O_+="=";this.raonkEditorId=this.currUrl=this.currFileName="";this.raonkEditorIsInsert=!1;this.frameStatus="";this.myPicker=null;this.COLOR_PICKER="#ff0000 #ff5e00 #ffbb00 #ffe400 #abf200 #1fda11 #00d8ff #0055ff #0900ff #6600ff #ff00dd #ff007f #000000 #ffffff #ffd8d8 #fae0d4 #faecc5 #faf4c0 #e4f7ba #cefbc9 #d4f4fa #d9e5ff #dad9ff #e8d9ff #ffd9fa #ffd9ec #f6f6f6 #eaeaea #f15f5f #f29661 #f2cb61 #e5d85c #bce55c #86e57f #5cd1e5 #6699ff #6b66ff #a366ff #f261df #f261aa #a6a6a6 #8c8c8c #670000 #662500 #664b00 #665c00 #476600 #22741c #005766 #002266 #030066 #290066 #660058 #660033 #212121 #000000".split(" ");
this.callColorPickerPlugin="";this.getTextArr=[];try{"function"===typeof KPHOTOTOP.KPHOTOWIN.RAONKPHOTO_onLanguageDefinition&&KPHOTOTOP.KPHOTOWIN.RAONKPHOTO_onLanguageDefinition(b,RAONKPhoto_Lang)}catch(d){}}Z[1]="t";K__+="n";R[4]=":";R[5]="/";R[6]="/";
RAONKPhoto_Editor.prototype={start:function(b){var c=KPHOTOTOP.RAONKPHOTO.util.parseIntOr0(b.height)-2;"1"==b.toolbarUse&&(c-=b.headerHeight);"1"==b.statusbarUse&&(c-=b.statusHeight);c-=10;this.____.p=b.productKey;var a;a=""+('<div id="RAONK_UP_photo_wrapper" class="RAONK_photo_wrapper" style="width: 100%; height: '+b.height+'">');a+='<div id="raonkphoto_header" class="RAONK_photo_header"><div id="raonkphoto_header_1">';a+='<h1 style="background:url('+b.logoUrl1+') 10px 5px no-repeat;">RAONK PHOTO</h1>';
a+="</div>";a+='<input type="file" name="photo_image" id="photo_image" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff,.tif" style="display:none;">';a+='<ul id="photo_toolbar" class="RAONK_photo_icon">';for(var d=b.toolbar,e=d.length,f=!1,g=0;g<e;g++)0<g&&"separator"!=d[g-1]&&(G_BeforeToolBar=d[g-1]),"text"==d[g]&&(f=!0),a=createToolbar(d[g],a);0>a.indexOf('<a id="btn_save"')&&(a=createToolbar("save",a,!0));_7_=b.licenseKeyHtml5;a+="</ul>";a+="</div>";a+='<div id="photo_container" class="RAONK_photo_container" style="height:'+
c+'px;">';a+='<div id="loading_div" class="RAONK_photo_loading" style="width:577px; height:100%; z-index:'+(b.defaultZIndex-500)+'; position:absolute; left:0px; top:0px; display:none;">';a+='<span class="RAONK_photo_loading_img">'+RAONKPhoto_Lang.common.processing+"</span>";a+="</div>";a+='<div id="photo_background" style="filter:alpha(opacity=0); opacity:0; -moz-opacity:0; -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=0); -khtml-opacity: 0; background-color:white; z-index:'+(b.defaultZIndex-
100)+"; position:absolute; left:px; top:"+b.headerHeight+'px;overflow:hidden;width:100%;height:100%; display:none;"></div>';a+='<div id="crop_size_info" class="RAONK_UP_sizeinfo" style="position:absolute; left:0px; top:0px; z-index:'+(b.defaultZIndex-400)+'; display:none;"><span></span> x <span></span></div>';a+='<div id="mosaic_size_info" class="RAONK_UP_sizeinfo" style="position:absolute; left:0px; top:0px; z-index:'+(b.defaultZIndex-400)+'; display:none;"><span></span> x <span></span></div>';a+=
'<div class="left_v_line"></div>';a+='<div id="photo_image_area" class="RAONK_photo_image_area" style="background:url('+b.logoUrl2+') 50% 50% no-repeat;"><div></div></div>';a+='<div class="center_v_line"></div>';a+='<div id="raonk_right_toolbar" class="RAONK_photo_option_area fl">';a+='<div class="RAONK_photo_content_option">';a+='<div class="file_info">';a+='<h3 id="raonk_right_toolbar_1_name">'+RAONKPhoto_Lang.basic.title+"</h3>";a+='<div id="right_btn_zone_1"></div>';a+="</div>";a+='<div id="raonk_right_toolbar_1" class="option_box_layout">';
a+='<div id="right_background" style="left:0px; top:0px; filter:alpha(opacity=0); opacity:0; -moz-opacity:0; -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=0); -khtml-opacity: 0; background-color:white; z-index:9000; position:absolute; overflow:hidden;width:100%;height:100%; display:none;"></div>';a+='<div id="photo_color_picker" style="display:none; z-index:9999; padding:0px; margin:0px; border: 1px solid rgb(187, 187, 187); border-image: none; width: 208px; position: absolute;">';a+=
'<ul class="raonk_color" id="color_ul" style="margin: 0px; padding: 5px 0px 30px 5px; width: 203px; float: left; background-color: rgb(251, 251, 251);">';for(g=0;g<KPHOTOTOP.G_CURRKPHOTO.COLOR_PICKER.length;g++)a+='<li title="'+KPHOTOTOP.G_CURRKPHOTO.COLOR_PICKER[g]+'" style="font-size: 1pt; background-color: '+KPHOTOTOP.G_CURRKPHOTO.COLOR_PICKER[g]+';"><a title="'+KPHOTOTOP.G_CURRKPHOTO.COLOR_PICKER[g]+'" style="width: 11px; height: 11px; display: block; background:none;" href="javascript:void(0);"></a></li>';
a+='<div class="color" id="more_btn" style="width: 192px; text-align: center; cursor: pointer; line-height:normal;">More</div>';a+="</ul>";a+="</div>";a+='<div id="div_default_area" class="RAONK_photo_default_option" style="display:;">';a+="<dl>";a+="<dt>"+RAONKPhoto_Lang.basic.name+"</dt>";a+='<dd id="default_name" class="w150"></dd>';a+="<dt>"+RAONKPhoto_Lang.basic.width+"</dt>";a+='<dd id="default_width"></dd>';a+="<dt>"+RAONKPhoto_Lang.basic.height+"</dt>";a+='<dd id="default_height"></dd>';a+=
"<dt>"+RAONKPhoto_Lang.basic.type+"</dt>";a+='<dd id="default_type"></dd>';a+="</dl>";a+="</div>";a+="</div>";a+="</div>";a+='<div id="raonk_right_toolbar_2" class="RAONK_photo_graphic_option">';a+='<div class="file_info">';a+='<h3 id="raonk_right_toolbar_2_name" class="mar_l10"></h3>';a+='<div id="right_btn_zone_2">';a+="</div>";a+="</div>";a+='<div id="raonk_right_toolbar_2_content_zone" class="list_box_layout">';a+="</div>";a+='<div id="raonk_right_toolbar_2_icon_zone" class="RAONK_photo_icon_zone">';
a+='<ul class="RAONK_photo_icon">';c=b.rightMenu;d=c.length;e=!1;for(g=0;g<d;g++)"figure"==c[g]&&(e=!0),a=createRightMenu(c[g],a);a+="</ul>";a+="</div>";a+="</div>";a+="</div>";a+='<div class="right_v_line "></div>';a+="</div>";a+='<div id="raonkphoto_status" class="RAONK_photo_footer">';a+='<div class="xypositon_wrap">';a+='<span class="img_xpo"><b id="img_x">X :</b>&nbsp;<span id="img_x_value"></span></span>&nbsp;&nbsp;<span class="img_ypo"><b id="img_y">Y : </b>&nbsp;<span id="img_y_value"></span></span>';
a+="</div>";a+='<div class="whsize_wrap" id="footer_img_info" style="display:none;">';a+='<span class="img_width"><b>W : </b><span id="img_width"></span></span> &nbsp;&nbsp;<span class="img_height"><b>H : </b><span id="img_height"></span></span>';a+="</div>";a+="</div>";a+="</div>";document.body.innerHTML=a;setImageAreaSize();this.____.l=_L__.DE(_7_);try{this.____.l=this.____.l.split("\x0B"),_0_=this.____.l,_1_=this.____.p}catch(h){}"0"==b.toolbarUse&&(document.getElementById("raonkphoto_header").style.display=
"none");"0"==b.statusbarUse&&(document.getElementById("raonkphoto_status").style.display="none");KPHOTOTOP.RAONKPHOTO.util.addEvent(document.getElementById("right_background"),"click",function(){G_RAONKCanvas.plugins[KPHOTOTOP.G_CURRKPHOTO.callColorPickerPlugin].backgroundClicked()});KPHOTOTOP.RAONKPHOTO.util.addEvent(document.getElementById("photo_color_picker"),"click",function(a){(a=a.target)&&"A"==a.tagName&&G_RAONKCanvas.plugins[KPHOTOTOP.G_CURRKPHOTO.callColorPickerPlugin].changColor(a.title)});
if(f||e)KPHOTOTOP.G_CURRKPHOTO.myPicker=new jscolor.color(document.getElementById("more_btn"),{},null,null,null,function(a){G_RAONKCanvas.plugins[KPHOTOTOP.G_CURRKPHOTO.callColorPickerPlugin].changColor(a)});KPHOTOTOP.RAONKPHOTO.util.addEvent(document.getElementById("photo_background"),"click",function(){closeSubArea()});KPHOTOTOP.RAONKPHOTO.util.addEvent(document,"keyup",document_keyup);KPHOTOTOP.RAONKPHOTO.util.addEvent(document,"keydown",document_keydown);-1<KPHOTOTOP.G_CURRKPHOTO._config.userRunTimeMode.indexOf("html5")&&
!KPHOTOTOP.RAONKPHOTO.browser.mobile&&KPHOTOTOP.RAONKPHOTO.util.addEvent(document.body,"paste",fn_pasteEvt);KPHOTOTOP.RAONKPHOTO.util.addEvent(KPHOTOTOP.document.getElementById("raonkphoto_holder_header_close_"+b.id),"click",function(){closePhotoPopup()});var p=KPHOTOTOP.RAONKPHOTO.RAONKMULTIPLE["raonkphoto_frame_"+b.id];setTimeout(function(){createRAONKCanvas(p);setTimeout(_fn_0,2E3)},10)}};SIL[2]="o";Z[2]="t";R[7]="w";
function createRAONKCanvas(b){G_RAONKCanvas=new RAONKCanvas("#"+b._config.targetImgId,{minWidth:1,minHeight:1,maxWidth:null,maxHeight:null,plugins:{crop:{minHeight:10,minWidth:10},flip:!0},init:function(){try{closeSubArea(),document.getElementById("raonk_right_toolbar_1_name").innerHTML=RAONKPhoto_Lang.basic.title,document.getElementById("div_default_area").style.display="",b.getTextArr=[]}catch(c){}}},null,b)}R[8]="w";R[9]="w";R[10]=".";
function _fn_0(){if("undefined"!==typeof T){var b=T.toString(),b=b.replace(/,/gi,""),c,a,d,e,f;c=a=d=e=f="";try{KPHOTOTOP.RAONKPHOTO.util.writeLog("DEBUG",___,"",""),KPHOTOTOP.RAONKPHOTO.util.writeLog("DEBUG",_0_.join(),"",""),KPHOTOTOP.RAONKPHOTO.util.writeLog("DEBUG",_1_,"",""),f=_0_[7],c=_0_[3],a=_0_[5],d=_0_[0],e=_1_}catch(g){KPHOTOTOP&&KPHOTOTOP.G_CURRKPHOTO&&alert(b+g.toString());return}try{if(0==e.length||e!=d){KPHOTOTOP&&KPHOTOTOP.G_CURRKPHOTO&&alert(b+KPHOTOTOP.RAONKPHOTO.util.makeDecryptReponseMessage(M1)+
e);return}}catch(h){KPHOTOTOP&&KPHOTOTOP.G_CURRKPHOTO&&alert(b+h.toString());return}try{if(0==a.length){KPHOTOTOP&&KPHOTOTOP.G_CURRKPHOTO&&alert(b);return}if("0"!=a){var p=new Date;a=a.toString();a=a.split("-");var t=KPHOTOTOP.RAONKPHOTO.util.parseIntOr0(a[0],10),k=KPHOTOTOP.RAONKPHOTO.util.parseIntOr0(a[1],10),k=k-1,r=KPHOTOTOP.RAONKPHOTO.util.parseIntOr0(a[2],10);if(p>new Date(t,k,r,23,59,59)){KPHOTOTOP&&KPHOTOTOP.G_CURRKPHOTO&&alert(b+KPHOTOTOP.RAONKPHOTO.util.makeDecryptReponseMessage(M2)+a.join());
return}}}catch(m){KPHOTOTOP&&KPHOTOTOP.G_CURRKPHOTO&&alert(b+m.toString());return}try{if(0==c.length){KPHOTOTOP&&alert(b);return}c=c.split(",");a=!1;c.push("localhost");c.push("127.0.0.1");KPHOTOTOP&&KPHOTOTOP.RAONKPHOTO&&""==KPHOTOTOP.RAONKPHOTO.util.trim(___)&&(___=KPHOTOTOP.KUPLOADWIN.location.href);-1<___.indexOf("file://")&&(___=KPHOTOTOP.G_CURRKPHOTO._config.handlerUrl);for(d=0;d<c.length;d++){var n=c[d].replace("*.",""),l=n.split("-");if(!(3!=l.length&&4!=l.length||isNaN(l[0])||isNaN(l[1])||
isNaN(l[2]))){a=!0;break}if(-1!=___.toLowerCase().search(n.toLowerCase())){a=!0;break}else{var q=n.replace("www.","");if(q!=n&&(q="/"+q,-1!=___.toLowerCase().search(q.toLowerCase()))){a=!0;break}}}if(0==a){KPHOTOTOP&&KPHOTOTOP.G_CURRKPHOTO&&alert(b+KPHOTOTOP.RAONKPHOTO.util.makeDecryptReponseMessage(M3)+___);return}}catch(u){KPHOTOTOP&&KPHOTOTOP.G_CURRKPHOTO&&alert(b+u.toString());return}try{if(0==f.length){KPHOTOTOP&&KPHOTOTOP.G_CURRKPHOTO&&alert(b);return}}catch(v){KPHOTOTOP&&KPHOTOTOP.G_CURRKPHOTO&&
alert(b+v.toString());return}_1_=!0}}T[0]="Li";R[11]="L";T[1]="c";_R_O_+=R[11];R[12]="e";
function displayImageWidthHeight(b,c){var a,d;document.getElementById("default_width").innerHTML=b.getWidth();document.getElementById("default_height").innerHTML=b.getHeight();c?(a=b.getHeight(),d=b.getWidth()):(a=b.getWidth(),d=b.getHeight());document.getElementById("img_width").innerHTML=KPHOTOTOP.RAONKPHOTO.util.parseIntOr0(a);document.getElementById("img_height").innerHTML=KPHOTOTOP.RAONKPHOTO.util.parseIntOr0(d)}Z[3]="p";R[13]="x";T[2]="e";R[14]="t";
function closeSubArea(){try{document.getElementById("div_default_area").style.display="none"}catch(b){}try{document.getElementById("div_resize_area").style.display="none"}catch(c){}try{document.getElementById("div_resize_select_area").style.display="none"}catch(a){}try{document.getElementById("div_tone_area").style.display="none"}catch(d){}try{document.getElementById("div_filter_area").style.display="none"}catch(e){}try{document.getElementById("div_figure_area").style.display="none"}catch(f){}try{document.getElementById("div_addimage_area").style.display=
"none"}catch(g){}try{document.getElementById("div_emoticon_area").style.display="none"}catch(h){}try{document.getElementById("photo_background").style.display="none"}catch(p){}try{document.getElementById("div_align_area").style.display="none"}catch(t){}try{for(var k=document.getElementById("right_btn_zone_1").getElementsByTagName("a"),r=k.length,m=0;m<r;m++)k[m].style.display="none"}catch(n){}try{closeTextSubList("font_family_list"),closeTextSubList("font_size_list"),closeTextSubList("text_color_picker"),
G_RAONKCanvas.plugins.text&&G_RAONKCanvas.plugins.text.myPicker.hidePicker(),document.getElementById("div_text_area").style.display="none"}catch(l){}}
function closeSubArea2(){try{document.getElementById("figure_list").style.display="none",document.getElementById("btn_figure").className=document.getElementById("btn_figure").className.replace(" on","")}catch(b){}try{document.getElementById("addimage_list").style.display="none",document.getElementById("btn_addimage").className=document.getElementById("btn_addimage").className.replace(" on","")}catch(c){}try{document.getElementById("emoticon_list").style.display="none",document.getElementById("btn_emoticon").className=
document.getElementById("btn_emoticon").className.replace(" on","")}catch(a){}try{for(var d=document.getElementById("right_btn_zone_2").getElementsByTagName("a"),e=d.length,f=0;f<e;f++)d[f].style.display="none"}catch(g){}}_R_O_+="R";T[3]="n";R[15]="5";_R_O_+="S";R[16]=".";function showOrCloseSubArea(b,c){var a=document.getElementById(b);a&&(0==!!c?a.style.display="none":(closeSubArea(),a.style.display="block"))}
function showTextSubArea(b,c){var a=document.getElementById(b);a&&"none"==a.style.display&&(closeSubArea(),document.getElementById("raonk_right_toolbar_1_name").innerHTML=RAONKPhoto_Lang.text.title,a.style.display="block")}function closeTextSubArea(b){if(b=document.getElementById(b))closeTextSubList("font_family_list"),closeTextSubList("font_size_list"),G_RAONKCanvas.plugins.text&&G_RAONKCanvas.plugins.text.myPicker.hidePicker(),b.style.display="none"}
function showTextSubList(b){if(b=document.getElementById(b))b.style.display="block"}function closeTextSubList(b){if(b=document.getElementById(b))b.style.display="none"}function checkOtherObjects(b){var c=!1;1<b.raonkcanvas.canvas._objects.length&&(c=!0);return c}
function objectsToImage(b,c){var a=b.raonkcanvas,d=a.canvas;if(confirm(RAONKPhoto_Lang.common.objectToImage)){for(var e=d._objects.length,f=1;f<e;f++)"group"==d._objects[f].type&&d._objects[f]._objects&&d._objects[f]._objects[1]&&"i-text"==d._objects[f]._objects[1].type&&KPHOTOTOP.G_CURRKPHOTO.getTextArr.push(d._objects[f]._objects[1].text),d._objects[f].active=!1,d._objects[f].setCoords();d.renderAll();e=d.toDataURL();f=new Image;f.onload=function(){b.raonkcanvas.canvas.clear();b.raonkcanvas.canvas._iTextInstances=
[];var e=new fabric.Image(this,{selectable:!1,evented:!1,lockMovementX:!0,lockMovementY:!0,lockRotation:!0,lockScalingX:!0,lockScalingY:!0,lockUniScaling:!0,hasControls:!1,hasBorders:!1});a.image.remove();a.image=e;d.add(e);c&&c(b)};f.src=e}}function setIconNotSelected(){if(RAONKCanvas.plugins.text){var b=document.getElementById("btn_text");b.className.indexOf("_selected")&&(b.className=b.className.replace("_selected",""))}}T[4]="se";_R_O_+="T";R[17]="c";T[5]="k";_R_O_+="x";T[6]="e";
function createRightMenu(b,c){var a=c;switch(b){case "figure":a+='<li><a id="btn_figure" class="RAONK_photo_figure" href="javascript:;" title="'+RAONKPhoto_Lang.figure.title+'"></a></li>';break;case "addimage":a+='<li><a id="btn_addimage" class="RAONK_photo_temaimage" href="javascript:;" title="'+RAONKPhoto_Lang.addimage.title+'"></a></li>';break;case "emoticon":a+='<li><a id="btn_emoticon" class="RAONK_photo_icons" href="javascript:;" title="'+RAONKPhoto_Lang.emoticon.title+'"></a></li>'}return a}
function createToolbar(b,c,a){switch(b){case "open":"html5"==KPHOTOTOP.G_CURRKPHOTO._config.userRunTimeMode&&(c+='<li><a id="btn_load_img" class="RAONK_load_img" href="javascript:;" title="'+RAONKPhoto_Lang.tool.open+'"></a></li>');break;case "history":c+='<li><a id="btn_undo" class="RAONK_undo" href="javascript:;" title="'+RAONKPhoto_Lang.tool.history_undo+'"></a></li>';c+='<li><a id="btn_redo" class="RAONK_redo" href="javascript:;" title="'+RAONKPhoto_Lang.tool.history_redo+'"></a></li>';break;
case "rotate":c+='<li><a id="btn_rotate_r" class="RAONK_rotate_r" href="javascript:;" title="'+RAONKPhoto_Lang.tool.retate_r+'"></a></li>';c+='<li><a id="btn_rotate_l" class="RAONK_rotate_l" href="javascript:;" title="'+RAONKPhoto_Lang.tool.retate_l+'"></a></li>';break;case "crop":c+='<li><a id="btn_crop" class="RAONK_crop" href="javascript:;" title="'+RAONKPhoto_Lang.tool.crop+'"></a></li>';c+='<li style="display:none;"><a id="btn_crop_ok" class="RAONK_crop_ok" href="javascript:;" title="'+RAONKPhoto_Lang.tool.crop_ok+
'"></a></li>';c+='<li style="display:none;"><a id="btn_crop_cancel" class="RAONK_crop_cancel" href="javascript:;" title="'+RAONKPhoto_Lang.tool.crop_cancel+'"></a><span class="RAONK_UP_s_bar"></span></li>';break;case "select":c+='<li><a id="btn_select" class="RAONK_crop" href="javascript:;" title="'+RAONKPhoto_Lang.tool.select+'"></a></li>';c+='<li style="display:none;"><a id="btn_select_cancel" class="RAONK_crop_cancel" href="javascript:;" title="'+RAONKPhoto_Lang.tool.select_cancel+'"></a></li>';
b=KPHOTOTOP.G_CURRKPHOTO._config.selectTool.length;for(a=0;a<b;a++)"crop"==KPHOTOTOP.G_CURRKPHOTO._config.selectTool[a]&&(c+='<li style="display:none;"><a id="btn_crop_ok" class="RAONK_crop_ok" href="javascript:;" title="'+RAONKPhoto_Lang.tool.crop_ok+'"></a>'),"mosaic"==KPHOTOTOP.G_CURRKPHOTO._config.selectTool[a]&&(c+='<li style="display:none;"><a id="btn_mosaic_ok" class="RAONK_mosaic_ok" href="javascript:;" title="'+RAONKPhoto_Lang.tool.mosaic_ok+'"></a>'),a==b-1&&(c+='<span class="RAONK_s_bar"></span>'),
c+="</li>";break;case "flip":c+='<li><a id="btn_flip_h" class="RAONK_flip_h" href="javascript:;" title="'+RAONKPhoto_Lang.tool.flip_h+'"></a></li>';c+='<li><a id="btn_flip_v" class="RAONK_flip_v" href="javascript:;" title="'+RAONKPhoto_Lang.tool.flip_v+'"></a></li>';break;case "resize":c+='<li><a id="btn_resize_on" class="RAONK_resize" href="javascript:;" title="'+RAONKPhoto_Lang.tool.resize+'"></a></li>';break;case "tone":c+='<li><a id="btn_tone_on" class="RAONK_tone" href="javascript:;" title="'+
RAONKPhoto_Lang.tool.tone+'"></a></li>';break;case "filter":c+='<li><a id="btn_effect_on" class="RAONK_effect" href="javascript:;" title="'+RAONKPhoto_Lang.tool.filter+'"></a></li>';break;case "save":c+='<li><a id="btn_save" class="RAONK_save" href="javascript:;" title="'+RAONKPhoto_Lang.tool.save+'" ';a&&(c+='style="display:none;"');c+="></a></li>";break;case "fullscreen":c+='<li><a id="btn_fullscreen" class="RAONK_fullscreen" href="javascript:;" title="'+RAONKPhoto_Lang.tool.fullscreen+'"></a></li>';
break;case "size_in_decrease":c+='<li class="width_down"><a id="btn_size_increase" class="RAONK_size_increase" href="javascript:;" title="'+KPHOTOTOP.G_CURRKPHOTO._config.sizeInDecreaseUnit+" "+RAONKPhoto_Lang.tool.size_increase+'"></a></li>';c+='<li><a id="btn_size_decrease" class="RAONK_size_decrease" href="javascript:;" title="'+KPHOTOTOP.G_CURRKPHOTO._config.sizeInDecreaseUnit+" "+RAONKPhoto_Lang.tool.size_decrease+'"></a></li>';break;case "mosaic":c+='<li><a id="btn_mosaic" class="RAONK_mosaic" href="javascript:;" title="'+
RAONKPhoto_Lang.tool.mosaic+'"></a></li>';c+='<li style="display:none;"><a id="btn_mosaic_ok" class="RAONK_mosaic_ok" href="javascript:;" title="'+RAONKPhoto_Lang.tool.mosaic_ok+'"></a></li>';c+='<li style="display:none;"><a id="btn_mosaic_cancel" class="RAONK_mosaic_cancel" href="javascript:;" title="'+RAONKPhoto_Lang.tool.mosaic_cancel+'"></a><span class="RAONK_UP_s_bar"></span></li>';break;case "text":c+='<li><a id="btn_text" class="RAONK_text" href="javascript:;" title="'+RAONKPhoto_Lang.tool.text+
'"></a></li>';break;case "align":c+='<li><a id="btn_align" class="RAONK_align" href="javascript:;" title="'+RAONKPhoto_Lang.tool.align+'"></a></li>';break;case "separator":var d;"crop"==G_BeforeToolBar||"mosaic"==G_BeforeToolBar||"select"==G_BeforeToolBar?(a=c.indexOf("btn_"+G_BeforeToolBar),d=c.substring(a).indexOf("</li>"),b=c.substring(0,a+d),c=c.substring(a+d)):(a=c.lastIndexOf("</li>"),b=c.substring(0,a),c=c.substring(a));c=b+'<span class="RAONK_s_bar"></span>'+c}return c}SIL[3]="b";T[7]="y";
_R_O_+="y";R[18]="o";T[8]=" i";
function setCanvasPostionCenter(b,c){var a=b.getWidth(),d=b.getHeight();c&&(a=b.getHeight(),d=b.getWidth());var e=document.getElementById("photo_image_area"),f,g;e.clientWidth?(f=e.clientWidth,g=e.clientHeight):(g=KPHOTOTOP.RAONKPHOTO.util.getClientRect(e),f=g.width,g=g.height);d=Math.round(g/2-d/2);0>d&&(d=0);a=Math.round(f/2-a/2);0>a&&(a=0);(f=document.getElementById("canvas_container"))?(f.style.top=d+"px",f.style.left=a+"px"):0<e.getElementsByTagName("img").length&&(e.firstChild.style.top=d+"px",
e.firstChild.style.left=a+"px")}T[9]="s ";_R_O_+="z";R[19]="m";T[10]="i";T[11]="n";R[20]="/";Z[4]=":";T[12]="c";R[21]="r";T[13]="o";
function setSaveImgPostionCenter(b,c,a){var d=document.getElementById("photo_image_area"),d=KPHOTOTOP.RAONKPHOTO.util.getClientRect(d),e=b>d.width?!0:!1,f=c>d.height?!0:!1,g=0,h=0;e&&(a.style.width="100%",a.style.overflowX="auto",a.style.overflowY="hidden");f&&(a.style.height=document.getElementById("photo_container").style.height,a.style.overflowX="hidden",a.style.overflowY="auto");e&&f&&(a.style.overflowX="auto",a.style.overflowY="auto");g=f?0:Math.round(d.height/2-c/2);h=e?0:Math.round(d.width/
2-b/2);a.style.top=g+"px";a.style.left=h+"px"}_R_O_+="u";R[22]="a";Z[5]="/";Z[6]="/";_R_O_+="v";R[23]="o";T[14]="r";Z[7]="w";T[15]="r";function displayLoadingDiv(b){document.getElementById("loading_div").style.display=b?"":"none"}Z[8]="w";_R_O_+="w";T[16]="e";Z[9]="w";R[24]="n";T[17]="c";Z[10]=".";function removeWorker(){for(var b=0;b<G_workers.length;b++)G_workers[b]&&G_workers[b].terminate();G_workers=[]}Z[11]="d";_R_O_+="H";T[18]="t";_R_O_+="M";R[25]=".";Z[12]="e";T[19]=". P";
function getExtFromImageDataSrc(b){var c="";b=b.replace("data:","").split(";");0<b.length&&(b=b[0].split("/"),2==b.length&&(c=b[1]));return c}T[20]="l";_R_O_+="N";Z[13]="x";R[26]="a";Z[14]="t";T[21]=T[2]+"a";
function document_keyup(b){var c="which"in b?b.which:b.keyCode;if((8==c||46==c)&&G_RAONKCanvas.canvas&&G_RAONKCanvas.canvas.getActiveObject()&&(b=b.target?b.target:b.srcElement,b=b.tagName?b.tagName.toLowerCase():"","textarea"!=b&&"input"!=b))try{var a=G_RAONKCanvas.canvas.getActiveObject();G_RAONKCanvas.canvas.remove(a);G_RAONKCanvas.dispatchEvent("image:change");closeSubArea();a.isRAONKFigure?G_RAONKCanvas.plugins.figure.backgroundClicked():a.isText&&G_RAONKCanvas.plugins.text.backgroundClicked();
document.getElementById("raonk_right_toolbar_1_name").innerHTML=RAONKPhoto_Lang.basic.title;document.getElementById("div_default_area").style.display=""}catch(d){}}Z[15]="5";_R_O_+="O";T[22]=T[4];Z[16]=".";_R_O_+="P";Z[17]="c";
function document_keydown(b){var c="which"in b?b.which:b.keyCode;1==b.ctrlKey&&(b.altKey&&48==c?alert("- RAON K Photo Information -\n  Client Ver. "+KPHOTOTOP.RAONKPHOTO.ReleaseVer):b.altKey||86!=c||(KPHOTOTOP.RAONKPHOTO.browser.ie&&11<=KPHOTOTOP.RAONKPHOTO.browser.ieVersion||KPHOTOTOP.RAONKPHOTO.browser.gecko)&&fn_makePasteEvt(b))}___=1==KPHOTOTOP.IsCrossDomain?___.href:top.location.href;R[27]="s";T[23]=",";
___=1==KPHOTOTOP.IsCrossDomain?null!=KPHOTOTOP.KPHOTODOC.referrer&&void 0!=KPHOTOTOP.KPHOTODOC.referrer&&""!=KPHOTOTOP.KPHOTODOC.referrer?KPHOTOTOP.KPHOTODOC.referrer:___:___;function removeStringTagForAlt(b){b=b.replace(RegExp("<span ([^>]+)>","gi"),"");return b=b.replace("</span>","")}Z[18]="o";Z[19]="m";K__+=Z[18];_R_O_+="Q";T[24]=" c";
function loadNewImg(b){var c=new Image;c.id=KPHOTOTOP.G_CURRKPHOTO._config.targetImgId;c.style.visibility="hidden";var a=document.getElementById("photo_image_area");a.innerHTML="";a.appendChild(c);c.onload=function(){G_RAONKCanvas&&(G_RAONKCanvas=null,KPHOTOTOP.G_CURRKPHOTO.isNew=!1);setTimeout(function(){try{createRAONKCanvas(KPHOTOTOP.G_CURRKPHOTO)}catch(a){try{KPHOTOTOP.RAONKPHOTO_OnError(currPhoto.ID,{strCode:"201",strMessage:"Error occurred load img.\nMessage:"+a.message})}catch(b){}}try{(window.URL||
window.webkitURL||window).revokeObjectURL(c.src),c=void 0}catch(f){}},100)};c.src=b}K__+="p";_R_O_+="I";T[25]=T[13];K__+="XYZ";_R_O_+="J";_R_O_+="c";_R_O_+="d";_R_O_+="g";
function resetPhoto(){document.getElementById("photo_image_area").innerHTML="";document.getElementById("img_width").innerHTML="";document.getElementById("img_height").innerHTML="";closeSubArea();try{G_RAONKCanvas.plugins[KPHOTOTOP.G_CURRKPHOTO.callColorPickerPlugin].backgroundClicked()}catch(b){}document.getElementById("raonk_right_toolbar_1_name").innerHTML=RAONKPhoto_Lang.basic.title;document.getElementById("div_default_area").style.display="";document.getElementById("default_name").innerHTML="";
document.getElementById("default_width").innerHTML="";document.getElementById("default_height").innerHTML="";document.getElementById("default_type").innerHTML="";try{if(KPHOTOTOP.G_CURRKPHOTO._config.rightMenu[0])switch(KPHOTOTOP.G_CURRKPHOTO._config.rightMenu[0]){case "figure":G_RAONKCanvas.plugins.figure.toggleFigure();break;case "emoticon":G_RAONKCanvas.plugins.emoticon.toggleEmoticonBtn();break;case "addimage":G_RAONKCanvas.plugins.addimage.toggleAddImage()}}catch(c){}G_RAONKCanvas&&(G_RAONKCanvas=
null,KPHOTOTOP.G_CURRKPHOTO.isNew=!1);setTimeout(function(){createRAONKCanvas(KPHOTOTOP.G_CURRKPHOTO)},10)}Z[20]="/";T[26]="n";K__+="qrstU";
function showPhotoPopup(){var b="raonkphoto_holder_"+KPHOTOTOP.G_CURRKPHOTO.ID,c=getWindowClientSize(KPHOTOTOP.window),a=getWindowScrollPos(KPHOTOTOP.window),d;if(null==document.getElementById("photo_popup_background")){d=document.createElement("div");d.setAttribute("id","photo_popup_background");var e='<div style="'+KPHOTOTOP.G_CURRKPHOTO._config.popupBackgroundStyle+" z-index:"+(KPHOTOTOP.G_CURRKPHOTO._config.defaultZIndex-1)+'; position:fixed; _position:absolute; left:0px; top:0px;overflow:hidden;width:100%;height:100%;"></div>',
e=e+('<iframe frameborder="0" scrolling="no" style="filter:alpha(opacity=0); opacity:0; -moz-opacity:0; -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=0); -khtml-opacity: 0; left: 0px; top: 0px; width: 100%; height: 100%; display: block; position: absolute; z-index: '+(KPHOTOTOP.G_CURRKPHOTO._config.defaultZIndex-2)+';"></iframe>');d.innerHTML=e;KPHOTOTOP.document.body.appendChild(d);d.getElementsByTagName("iframe")[0].style.height=c[1]+a[1]+"px"}b=KPHOTOTOP.document.getElementById(b);
b.style.display="";b.style.position="absolute";b.style.zIndex=KPHOTOTOP.G_CURRKPHOTO._config.defaultZIndex;KPHOTOTOP.document.getElementById("raonkphoto_holder_header_"+KPHOTOTOP.G_CURRKPHOTO.ID).style.display="";d=KPHOTOTOP.RAONKPHOTO.util.getClientRect(b);e=d.bottom-d.top;b.style.left=a[0]+c[0]/2-(d.right-d.left)/2+"px";b.style.top=a[1]+c[1]/2-e/2+"px";adjustPopupPosition();makeDragPopup(b);setImageAreaSize();try{KPHOTOTOP.KPHOTOWIN.RAONKPHOTO_OnPopupEvent(KPHOTOTOP.G_CURRKPHOTO.ID,{strValue:"show"})}catch(f){}}
Z[21]="z";K__+="VW";function getWindowClientSize(b){var c=0,a=0;"number"==typeof b.innerWidth?(c=b.innerWidth,a=b.innerHeight):b.document.documentElement&&(b.document.documentElement.clientWidth||b.document.documentElement.clientHeight)?(c=b.document.documentElement.clientWidth,a=b.document.documentElement.clientHeight):b.document.body&&(b.document.body.clientWidth||b.document.body.clientHeight)&&(c=b.document.body.clientWidth,a=b.document.body.clientHeight);return[c,a]}K__+="89012";T[27]=T[18];
function getWindowScrollPos(b){return"number"===typeof b.pageYOffset?[b.pageXOffset,b.pageYOffset]:b.document.body&&(b.document.body.scrollLeft||b.document.body.scrollTop)?[b.document.body.scrollLeft,b.document.body.scrollTop]:b.document.documentElement&&(b.document.documentElement.scrollLeft||b.document.documentElement.scrollTop)?[b.document.documentElement.scrollLeft,b.document.documentElement.scrollTop]:[0,0]}T[28]="a";
function getClientSize(){var b={};"number"===typeof window.innerWidth?(b.width=window.innerWidth,b.height=window.innerHeight):document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?(b.width=document.documentElement.clientWidth,b.height=document.documentElement.clientHeight):document.body&&(document.body.clientWidth||document.body.clientHeight)?(b.width=document.body.clientWidth,b.height=document.body.clientHeight):(b.width=0,b.height=0);return b}
Z[25]=".";T[29]="c";function makeDragPopup(b){G_drag=!1;var c=b.firstChild;KPHOTOTOP.RAONKPHOTO.util.addEvent(c,"mousedown",startDrag);KPHOTOTOP.RAONKPHOTO.util.addEvent(c,"mouseover",function(){c.style.cursor="move"});KPHOTOTOP.RAONKPHOTO.util.addEvent(c,"mouseout",function(){c.style.cursor="default"});G_dragPopup=b}K__+="367";
function startDrag(b){""==KPHOTOTOP.G_CURRKPHOTO.frameStatus&&(b||(b=KPHOTOTOP.window.event),G_offsetX=b.clientX,G_offsetY=b.clientY,G_dragPopup.style.left||(G_dragPopup.style.left="0px"),G_dragPopup.style.top||(G_dragPopup.style.top="0px"),G_coordX=parseInt(G_dragPopup.style.left),G_coordY=parseInt(G_dragPopup.style.top),G_drag=!0,KPHOTOTOP.document.getElementById("raonkphoto_holder_body_"+KPHOTOTOP.G_CURRKPHOTO.ID).style.display="",KPHOTOTOP.RAONKPHOTO.util.addEvent(KPHOTOTOP.document,"mousemove",
dragDiv),KPHOTOTOP.RAONKPHOTO.util.addEvent(KPHOTOTOP.document,"mouseup",stopDrag));KPHOTOTOP.RAONKPHOTO.util.cancelEvent(b)}T[30]="t ";
function dragDiv(b){if(G_drag){b||(b=KPHOTOTOP.window.event);var c=getWindowClientSize(KPHOTOTOP.window),a=KPHOTOTOP.RAONKPHOTO.util.getClientRect(G_dragPopup),a=[a.right-a.left||0,a.bottom-a.top||0];currentScrollPos=getWindowScrollPos(KPHOTOTOP.window);var d=G_coordX+b.clientX-G_offsetX,e=G_coordY+b.clientY-G_offsetY;0>=d-currentScrollPos[0]&&(d=currentScrollPos[0]);0>=e-currentScrollPos[1]&&(e=currentScrollPos[1]);d+a[0]>=c[0]+currentScrollPos[0]&&(d=c[0]-a[0]+currentScrollPos[0]);e+a[1]>=c[1]+
currentScrollPos[1]&&(e=c[1]-a[1]+currentScrollPos[1]);G_dragPopup.style.left=d+"px";G_dragPopup.style.top=e+"px";KPHOTOTOP.document.getElementById("raonkphoto_holder_header_"+KPHOTOTOP.G_CURRKPHOTO.ID);adjustPopupPosition(G_dragPopup);KPHOTOTOP.RAONKPHOTO.util.stopEvent(b);KPHOTOTOP.RAONKPHOTO.util.cancelEvent(b)}}Z[26]="a";K__+="45";SIL[4]="a";
function stopDrag(b){G_drag=!1;G_dragPopup.style.cursor="";KPHOTOTOP.RAONKPHOTO.util.removeEvent(KPHOTOTOP.document,"mousemove",dragDiv);KPHOTOTOP.RAONKPHOTO.util.removeEvent(KPHOTOTOP.document,"mouseup",stopDrag);KPHOTOTOP.document.getElementById("raonkphoto_holder_body_"+KPHOTOTOP.G_CURRKPHOTO.ID).style.display="none"}Z[27]="s";T[31]="u";
function closePhotoPopup(){"fullscreen"==KPHOTOTOP.G_CURRKPHOTO.frameStatus&&fullSreenToOriginalSize();KPHOTOTOP.document.getElementById("raonkphoto_holder_header_"+KPHOTOTOP.G_CURRKPHOTO.ID).style.display="none";KPHOTOTOP.document.getElementById("raonkphoto_holder_body_"+KPHOTOTOP.G_CURRKPHOTO.ID).style.display="none";KPHOTOTOP.document.getElementById("raonkphoto_holder_"+KPHOTOTOP.G_CURRKPHOTO.ID).style.display="none";var b=KPHOTOTOP.document.getElementById("photo_popup_background");b&&KPHOTOTOP.document.body.removeChild(b);
""!=KPHOTOTOP.G_CURRKPHOTO.raonkEditorId&&(KPHOTOTOP.G_CURRKPHOTO.raonkEditorIsInsert=!1);try{KPHOTOTOP.KPHOTOWIN.RAONKPHOTO_OnPopupEvent(KPHOTOTOP.G_CURRKPHOTO.ID,{strValue:"close"})}catch(c){}}R[28]="p";function photoShow(){KPHOTOTOP.document.getElementById("raonkphoto_holder_"+KPHOTOTOP.G_CURRKPHOTO.ID).style.display="";setImageAreaSize()}Z[28]="p";K__+="+";T[32]="s.";
function photoHidden(){"fullscreen"==KPHOTOTOP.G_CURRKPHOTO.frameStatus&&fullSreenToOriginalSize();KPHOTOTOP.document.getElementById("raonkphoto_holder_"+KPHOTOTOP.G_CURRKPHOTO.ID).style.display="none"}K__+="/";
function getPhotoFromEvent(b){var c=null;try{if(null!=b){var a=b.target?b.target:b.srcElement;if(a){b=null;b=9!=a.nodeType?a.ownerDocument:a;try{b=b.defaultView?b.defaultView:b.parentWindow,c=KPHOTOTOP.RAONKPHOTO.RAONKMULTIPLE[b.frameElement.id]}catch(d){c=KPHOTOTOP.G_CURRKPHOTO}}else c=KPHOTOTOP.G_CURRKPHOTO}else c=KPHOTOTOP.G_CURRKPHOTO}catch(e){c=KPHOTOTOP.G_CURRKPHOTO}return c}
function adjustPopupPosition(b){void 0==b&&(b=KPHOTOTOP.document.getElementById("raonkphoto_holder_"+KPHOTOTOP.G_CURRKPHOTO.ID));var c=KPHOTOTOP.document.getElementById("raonkphoto_holder_header_"+KPHOTOTOP.G_CURRKPHOTO.ID),c=KPHOTOTOP.RAONKPHOTO.util.getClientRect(c);0>c.top&&(b.style.top=KPHOTOTOP.RAONKPHOTO.util.parseIntOr0(b.style.top)-KPHOTOTOP.RAONKPHOTO.util.parseIntOr0(c.top)+"px")}
var _L__={_K:_R_O_+K__,DE:function(b){var c="",a,d,e,f,g,h=0;for(b=b.replace(/[^A-Za-z0-9\+\/\=]/g,"");h<b.length;)a=this._K.indexOf(b.charAt(h++)),d=this._K.indexOf(b.charAt(h++)),f=this._K.indexOf(b.charAt(h++)),g=this._K.indexOf(b.charAt(h++)),a=a<<2|d>>4,d=(d&15)<<4|f>>2,e=(f&3)<<6|g,c+=String.fromCharCode(a),64!=f&&(c+=String.fromCharCode(d)),64!=g&&(c+=String.fromCharCode(e));return c=_L__._utf8_d(c)},_utf8_d:function(b){for(var c="",a=0,d=c1=c2=0;a<b.length;)d=b.charCodeAt(a),128>d?(c+=String.fromCharCode(d),
a++):191<d&&224>d?(c2=b.charCodeAt(a+1),c+=String.fromCharCode((d&31)<<6|c2&63),a+=2):(c2=b.charCodeAt(a+1),c3=b.charCodeAt(a+2),c+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63),a+=3);return c}};
function setImageAreaSize(b){var c;c=KPHOTOTOP.RAONKPHOTO.util.getClientRect(document.getElementById("photo_container")).width;var a=KPHOTOTOP.RAONKPHOTO.util.getClientRect(document.getElementById("raonk_right_toolbar")).width;c=c-a-17;document.getElementById("loading_div").style.width=c+"px";document.getElementById("photo_image_area").style.width="2px";document.getElementById("photo_image_area").style.width=c+"px";document.getElementById("photo_image_area").style.height=parseInt(document.getElementById("photo_container").style.height,
0)-1+"px";G_LastImgInstance&&setCanvasPostionCenter(G_LastImgInstance,b);b=document.getElementById("raonk_right_toolbar_2");b=KPHOTOTOP.RAONKPHOTO.util.getClientRect(b);c=KPHOTOTOP.RAONKPHOTO.util.getClientRect(document.getElementById("raonk_right_toolbar_2_icon_zone")).height;a=KPHOTOTOP.RAONKPHOTO.util.getClientRect(document.getElementById("raonk_right_toolbar_2_name")).height;document.getElementById("raonk_right_toolbar_2_content_zone").style.height=b.height-c-a-4+"px";b=document.getElementById("raonk_right_toolbar_1");
c=KPHOTOTOP.RAONKPHOTO.util.getClientRect(b.parentNode).height;a=document.getElementById("raonk_right_toolbar_1_name");a=KPHOTOTOP.RAONKPHOTO.util.getClientRect(a).height;b.style.height=c-a+"px"}
function notAciveObjects(b){try{var c=b.raonkcanvas.canvas,a=c.getActiveObject();if(a&&a.active){var d=document.getElementById("div_figure_area"),e=document.getElementById("div_addimage_area"),f=document.getElementById("div_emoticon_area");if("none"!=document.getElementById("div_text_area").style.display||d&&"none"!=d.style.display||e&&"none"!=e.style.display||f&&"none"!=f.style.display)closeSubArea(),document.getElementById("raonk_right_toolbar_1_name").innerHTML=RAONKPhoto_Lang.basic.title,document.getElementById("div_default_area").style.display=
"";c.deactivateAll();c.renderAll()}}catch(g){}}
function fn_makePasteEvt(b){try{if(b&&(KPHOTOTOP.G_CURRKPHOTO=getPhotoFromEvent(b)),KPHOTOTOP.RAONKPHOTO.browser.ie){var c=document.createElement("div");c.id="pasteDiv";c.innerHTML=unescape("%uFEFF");c.style.position="absolute";c.style.filter="alpha(opacity=0)";c.style.overflow="hidden";c.style.left="-1000px";c.style.top="-1000px";c.style.width="0px";c.style.height="0px";c.contentEditable=!0;document.body.appendChild(c);c.focus()}else if(KPHOTOTOP.RAONKPHOTO.browser.gecko){var a=document.createElement("iframe");
a.id="pasteIframe";a.frameBorder=0;a.style.width="0px";a.style.height="0px";a.style.position="absolute";a.style.left="0px";a.style.top="0px";if(KPHOTOTOP.RAONKPHOTO.browser.mobile||KPHOTOTOP.RAONKPHOTO.browser.iOS)a.style.overflow="hidden",a.style.display="inline-block";var d="document.open();"+(KPHOTOTOP.RAONKPHOTO.browser.isCustomDomain(document)?'document.domain="'+document.domain+'";':"")+" document.close();",d=KPHOTOTOP.RAONKPHOTO.browser.ie?"javascript:void(function(){"+encodeURIComponent(d)+
"}())":"";a.src=d;document.body.appendChild(a);var e=KPHOTOTOP.RAONKPHOTO.util.getIframeDocument(a);e.open("text/html","replace");KPHOTOTOP.RAONKPHOTO.browser.isCustomDomain(document)&&(e.domain=document.domain);e.write('<body contenteditable="true">'+unescape("%uFEFF")+"</body>");e.close();e.body.contentEditable=!0;e.body.onpaste=fn_pasteEvt;e.body.focus()}}catch(f){}}
function fn_pasteEvt(b){try{var c=KPHOTOTOP.G_CURRKPHOTO;document.createElement("canvas").getContext("2d");if(KPHOTOTOP.RAONKPHOTO.browser.ie||KPHOTOTOP.RAONKPHOTO.browser.gecko)setTimeout(function(){var a=null,b=null;if(KPHOTOTOP.RAONKPHOTO.browser.ie)b=a=document.getElementById("pasteDiv");else if(KPHOTOTOP.RAONKPHOTO.browser.gecko)try{var d=document.getElementById("pasteIframe");d&&(a=KPHOTOTOP.RAONKPHOTO.util.getIframeDocument(d).body,b=d)}catch(e){a=null}a&&(a.blur(),a=a.getElementsByTagName("img"),
0<a.length&&(c.currFileName=".jpg",loadNewImg(a[0].src)),b.parentNode.removeChild(b))},0);else if(KPHOTOTOP.RAONKPHOTO.browser.chrome||KPHOTOTOP.RAONKPHOTO.browser.opera){var a=b.clipboardData.items,d=a.length;for(b=0;b<d;++b){var e=a[b].getAsFile(),f=new FileReader;f.onload=function(a){a=a.target.result;c.currFileName=".jpg";loadNewImg(a);f=void 0};f.readAsDataURL(e)}}}catch(g){}};
