/*
 Copyright (c) 2015, Raonwiz Technology Inc. All rights reserved.
*/
if(!window.RAONKPHOTO){window.RAONKPHOTO=function(){var a=window.RAONKPHOTO_ROOTPATH||"";if(!a)for(var b=document.getElementsByTagName("script"),c=b.length,d=null,e=0;e<c;e++)if(d=b[e],d=d.src.match(/(^|.*[\\\/])raonkphoto\.js/i)){a=d[1];break}-1==a.indexOf(":/")&&(a=0===a.indexOf("/")?location.href.match(/^.*?:\/\/[^\/]*/)[0]+a:location.href.match(/^[^\?]*\/(?:)/)[0]+a);a=a.substring(0,a.length-1);a=a.substring(0,a.lastIndexOf("/"))+"/";if(!a)throw"RAONK Photo installation path could not be automatically detected.";
return{isRelease:!0,debugMode:!1,debugLevel:"ALL",debugLogGroupingName:"",version:"RAONK Photo",ReleaseVer:"2018.1472233.1603.01",ServerReleaseVer:"",rootPath:a,RAONKMULTIPLE:{},RAONKHOLDER:{}}}();try{"undefined"==typeof raonkSolutionLog&&"undefined"!=typeof RAONKPhotoDebugMode&&RAONKPhotoDebugMode&&(RAONKPHOTO.debugMode=!0,"undefined"!=typeof RAONKPhotoDebugModeLogLevel&&(RAONKPHOTO.debugLevel=RAONKPhotoDebugModeLogLevel.toUpperCase()),document.write('<script src="'+RAONKPHOTO.rootPath+"js/log4javascript/raonk.log4javascript.min.js?ver="+
RAONKPHOTO.ReleaseVer+'" type="text/javascript">\x3c/script>'))}catch(e$$4){}RAONKPHOTO.browser||(RAONKPHOTO.browser=function(){var a=navigator.userAgent.toLowerCase(),b=window.opera,b={ie:-1<a.search("trident")||-1<a.search("msie")||-1<a.search("edge/12")?!0:!1,opera:!!b&&b.version,webkit:-1<a.indexOf(" applewebkit/"),mac:-1<a.indexOf("macintosh"),quirks:"BackCompat"==document.compatMode,mobile:-1<a.indexOf("mobile"),iOS:/(ipad|iphone|ipod)/.test(a),isCustomDomain:function(a){if(!this.ie)return!1;
var b=a.domain;a=RAONKPHOTO.util.getDocWindow(a).location.hostname;return b!=a&&b!="["+a+"]"},isHttps:"https:"==location.protocol,HTML5Supported:!0};b.gecko="Gecko"==navigator.product&&!b.webkit&&!b.opera;b.ie&&(b.gecko=!1);b.webkit&&(-1<a.indexOf("chrome")?(b.chrome=!0,-1<a.indexOf("opr")&&(b.opera=!0,b.chrome=!1)):b.safari=!0);var c;b.ieVersion=0;b.ie&&(c=b.quirks||!document.documentMode?-1<a.indexOf("msie")?parseFloat(a.match(/msie (\d+)/)[1]):-1<a.indexOf("trident")?parseFloat(a.match(/rv:([\d\.]+)/)[1]):
-1<a.indexOf("edge/12")||-1<a.indexOf("edge/13")?12:7:document.documentMode,b.ieVersion=c,b.ie12=12==c,b.ie11=11==c,b.ie10=10==c,b.ie9=9==c,b.ie8=8==c,b.ie7=7==c,b.ie6=7>c||b.quirks);b.gecko&&(c=a.match(/rv:([\d\.]+)/))&&(c=c[1].split("."),c=1E4*c[0]+100*(c[1]||0)+1*(c[2]||0));b.webkit&&(c=parseFloat(a.match(/ applewebkit\/(\d+)/)[1]));b.HTML5Supported="File"in window&&"FileReader"in window&&"Blob"in window;b.WorkerSupported="Worker"in window;b.PhotoEditorSupported=b.HTML5Supported&&"FormData"in window&&
!!document.createElement("canvas").getContext;return b}());RAONKPHOTO.ajax||(RAONKPHOTO.ajax=function(){var a=function(){if(!RAONKPHOTO.browser.ie||"file:"!=location.protocol){try{return new XMLHttpRequest}catch(a){}try{return new ActiveXObject("Msxml2.XHLHTTP")}catch(b){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}}return null},b=function(a){return 4==a.readyState&&(200<=a.status&&300>a.status||304==a.status||0===a.status||1223==a.status)},c=function(a){return b(a)?a.responseText:
null},d=function(a){if(b(a)){var c=a.responseXML;return c?c:a.responseText}return null},e=function(b,c,d){var e=!!c,f=a();if(!f)return null;f.open("GET",b,e);e&&(f.onreadystatechange=function(){4==f.readyState&&(c(d(f)),f=null)});try{f.send(null)}catch(m){return null}if(!e)var q=setTimeout(function(){try{f.abort()}catch(a){}clearTimeout(q)},5E3);return e?"":d(f)},f=function(b,c,d,e){var f=!!d,m=a();if(!m)return null;m.open("POST",b,f);"object"!=typeof c&&m.setRequestHeader("Content-Type","application/x-www-form-urlencoded;charset=UTF-8");
f&&(m.onreadystatechange=function(){4==m.readyState&&(d(e(m)),m=null)});try{m.send(c)}catch(q){return null}if(!f)var t=setTimeout(function(){try{m.abort()}catch(a){}clearTimeout(t)},5E3);return f?"":e(m)};return{load:function(a,b){return e(a,b,c)},loadXml:function(a,b){return e(a,b,d)},postData:function(a,b,d){return f(a,b,d,c)},postFileData:function(a,b){return postFileData(a,b)},createXMLHttpRequest:function(){return a()}}}());RAONKPHOTO.util||(RAONKPHOTO.util={G_IMG_LIST:{},writeLog:function(a,
b,c,d){if("undefined"!=typeof raonkSolutionLog&&"undefined"!=typeof RAONKPhotoDebugMode&&RAONKPhotoDebugMode){var e="";"string"==typeof d&&(d=d.split("#"),2==d.length&&(""==RAONKPHOTO.debugLogGroupingName&&"s"==d[1].toLowerCase()?(RAONKPHOTO.debugLogGroupingName=d[0].toLowerCase(),e="#separator#"):""!=RAONKPHOTO.debugLogGroupingName&&RAONKPHOTO.debugLogGroupingName==d[0].toLowerCase()&&"e"==d[1].toLowerCase()&&(RAONKPHOTO.debugLogGroupingName="")));RAONKSolution.writeLog(e+"[RAONK Photo]",a,b,c)}},
trim:function(a){return a.trim?a.trim():a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},makeIframe:function(){var a;try{a=document.createElement('<iframe frameborder="0" >')}catch(b){a=document.createElement("iframe")}a.style.margin="0px";a.style.padding="0px";a.frameBorder=0;a.style.overflow="auto";a.style.overflowX="hidden";a.style.backgroundColor="#ffffff";return a},addEvent:function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,d):a.attachEvent&&a.attachEvent("on"+b,c)},removeEvent:function(a,b,
c,d){a.removeEventListener?a.removeEventListener(b,c,d):a.detachEvent&&a.detachEvent("on"+b,c)},stopEvent:function(a){"bubbles"in a?a.bubbles&&a.stopPropagation():a.cancelBubble=!0},cancelEvent:function(a){a.preventDefault?a.preventDefault():a.returnValue=!1},ajax:{xml_http_request:function(){var a;window.XMLHttpRequest?a=new XMLHttpRequest:window.ActiveXObject&&(a=new ActiveXObject("Microsoft.XMLHTTP"));return a}},url:{full_url:function(a){var b="";if(0==a.indexOf("http://")||0==a.indexOf("https://"))b=
a;else if(0==a.indexOf("/"))b=location.protocol+"//"+location.host+a;else var b=location.href,c=b.lastIndexOf("/"),b=b.substring(0,c+1),b=b+a;return b}},xml:{count:function(a,b){return a?a.getElementsByTagName(b).length:0},getNode:function(a,b){return null==a||void 0==a?null:this.getNodeIdx(a,b,0)},getNodeIdx:function(a,b,c){return a.getElementsByTagName(b)[c]},getNodeValue:function(a,b){return null==a||void 0==a?"":this.getNodeValueIdx(a,b,0)},getNodeValueIdx:function(a,b,c){a=this.getNodeIdx(a,
b,c);return this.getValue(a)},getValue:function(a){var b="",c="";if(void 0!=a)try{0<a.childNodes.length&&(c=b=a.firstChild.nodeValue);try{("product_key"==a.nodeName||"font"==a.nodeName||"encoding"==a.nodeName||"doctype"==a.nodeName)&&2<=a.childNodes.length&&(b=a.textContent?a.textContent:c)}catch(d){b=c}}catch(e){b="parsing error"}return b}},removeEvents:function(a,b,c){a=b.split(",");b=c.length;for(var d=0,e=0;e<b;e++)for(var d=a.length,f=0;f<d;f++)c[e].removeAttribute(a[f])},getDate:function(){var a=
0,b=new Date,a=""+b.getFullYear(),c=""+(b.getMonth()+1);1==c.length&&(c="0"+c);b=""+b.getDate();1==b.length&&(b="0"+b);return a=parseInt(a+c+b,10)},parseIntOr0:function(a){a=parseInt(a,10);return isNaN(a)?0:a},makeGuidTagName:function(a){var b=0,c=(new Date).getTime().toString(32),d;for(d=0;5>d;d++)c+=Math.floor(65535*Math.random()).toString(32);return(a||"o_")+c+(b++).toString(32)},makeGuid:function(a){var b=function(){return(65536*(1+Math.random())|0).toString(16).substring(1)},b=(b()+b()+"-"+b()+
"-"+b()+"-"+b()+"-"+b()+b()+b()).toUpperCase();void 0!=a&&(b=a+"-"+b);return b},getUserLang:function(a){a=a.toLowerCase();var b="ko-kr";"auto"==a&&(b="en-us",(a=navigator.language||navigator.userLanguage)||(a=b),a=a.toLowerCase());-1<a.indexOf("ko")?b="ko-kr":-1<a.indexOf("en")?b="en-us":-1<a.indexOf("ja")?b="ja-jp":-1<a.indexOf("zh-cn")?b="zh-cn":-1<a.indexOf("zh-tw")&&(b="zh-tw");return b},getDocWindow:function(a){return a.parentWindow||a.defaultView},getClientRect:function(a){var b={left:0,top:0,
right:0,bottom:0};try{b=a.getBoundingClientRect()}catch(c){}return b},getParentbyTagName:function(a,b){for(var c=a;null!=c&&(!c.tagName||c.tagName.toLowerCase()!=b);)c=c.parentNode;return c},getElementsByClass:function(a,b,c){var d=[];null==b&&(b=document);null==c&&(c="*");b=b.getElementsByTagName(c);c=b.length;a=new RegExp("(^|\\s)"+a+"(\\s|$)");for(j=i=0;i<c;i++)a.test(b[i].className)&&(d[j]=b[i],j++);return d},createNewBtn:function(a){var b=document.createElement("div");b.innerHTML=a.outerHTML;
b=b.firstChild;a.parentNode.insertBefore(b,a);a.parentNode.removeChild(a);return b},setButton:function(a){a.setDisabled=function(a){var c=this.className.split(" ")[0],d=c.indexOf("_off");a?0>d&&(this.className=c+"_off"):-1<d&&(this.className=c.substring(0,d))}},setMouseEvent:function(a){if(0>a.className.indexOf("_off")){var b=a.className.split(" ");a.className=b[0]}RAONKPHOTO.util.addEvent(a,"mouseover",function(){if(0>a.className.indexOf("_off"))a.className+=" on";else{var b=a.className.split(" ");
a.className=b[0]}});RAONKPHOTO.util.addEvent(a,"mouseout",function(){var b=(a.className.indexOf("_off"),a.className.split(" "));a.className=b[0]})},onlyNumber:function(a){window.netscape?34<a.which&&41>a.which||47<a.which&&58>a.which||95<a.which&&106>a.which||8==a.which||9==a.which||13==a.which||46==a.which||RAONKPHOTO.util.cancelEvent(a):34<a.keyCode&&41>a.keyCode||47<a.keyCode&&58>a.keyCode||95<a.keyCode&&106>a.keyCode||8==a.keyCode||9==a.keyCode||13==a.keyCode||46==a.keyCode||RAONKPHOTO.util.cancelEvent(a)},
set_handlerUrl:function(a){var b="",b=0==a.length?RAONKPHOTO.rootPath:"/"==a.substring(0,1)?location.protocol+"//"+location.host:4<a.length&&"http"==a.substring(0,4).toLowerCase()?"":RAONKPHOTO.rootPath;return b+a},postFormData:function(a,b,c,d){void 0==d&&(d=[]);var e=a.createElement("form");e.method="post";e.action=b;e.target=c;b=d.length;for(c=0;c<b;c++){var f=a.createElement("input");f.type="hidden";f.name=d[c][0];f.value=d[c][1];e.appendChild(f)}a.body.appendChild(e);e.submit();a.body.removeChild(e)},
base64_encode:function(a){var b="",c,d,e,f,k,g,h=0;for(a=RAONKPHOTO.util.utf8_encode(a);h<a.length;)c=a.charCodeAt(h++),d=a.charCodeAt(h++),e=a.charCodeAt(h++),f=c>>2,c=(c&3)<<4|d>>4,k=(d&15)<<2|e>>6,g=e&63,isNaN(d)?k=g=64:isNaN(e)&&(g=64),b=b+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(f)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(k)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g);
return b},utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);128>d?b+=String.fromCharCode(d):(127<d&&2048>d?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b},base64_decode:function(a){var b="",c,d,e,f,k,g=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");g<a.length;)c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(g++)),
d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(g++)),f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(g++)),k="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(g++)),c=c<<2|d>>4,d=(d&15)<<4|f>>2,e=(f&3)<<6|k,b+=String.fromCharCode(c),64!=f&&(b+=String.fromCharCode(d)),64!=k&&(b+=String.fromCharCode(e));return b=RAONKPHOTO.util.utf8_decode(b)},utf8_decode:function(a){for(var b="",c=0,d=
c1=c2=0;c<a.length;)d=a.charCodeAt(c),128>d?(b+=String.fromCharCode(d),c++):191<d&&224>d?(c2=a.charCodeAt(c+1),b+=String.fromCharCode((d&31)<<6|c2&63),c+=2):(c2=a.charCodeAt(c+1),c3=a.charCodeAt(c+2),b+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63),c+=3);return b},makeDecryptReponseMessage:function(a){var b=function(a,b){var e=a.split("");e.splice(b,1);return e=e.join("")};a=a.replace(/ /g,"");a=a.replace(/\r/g,"");a=a.replace(/\n/g,"");a=a.replace(/%2B/g,"+");15<=a.length?(a=b(a,9),a=b(a,6),a=
b(a,8),a=b(a,7),a=b(a,9),a=b(a,6),a=b(a,8)):(a=a.replace(/#/g,""),a=a.replace(/$/g,""));return a=RAONKPHOTO.util.base64_decode(a)},replaceAll:function(a,b,c){for(var d=a.indexOf(b);-1!=d;)a=a.replace(b,c),d=a.indexOf(b);return a},stringToXML:function(a){var b;try{window.DOMParser?b=(new DOMParser).parseFromString(a,"text/xml"):(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",b.loadXML(a))}catch(c){b=null}return b},getIframeDocument:function(a){return"undefined"!=typeof a.contentDocument?a.contentDocument:
"undefined"!=typeof a.contentWindow?a.contentWindow.document:null},isExistPhotoName:function(a,b){if(void 0==a||""==a)return 1;var c=RAONKPHOTO.RAONKMULTIPLE["raonkphoto_frame_"+a];return void 0==c||null==c?0:""!=b&&RAONKPHOTO.RAONKHOLDER[a]==b?3:2},getNewNextPhotoName:function(a){var b="",c=a.split("_"),d=0;do b=c.length,1<b&&(a=a.replace("_"+c[b-1],"")),b=a+"_"+d,d++;while(0<RAONKPHOTO.util.getNewNextPhotoName(b));return b},initHandlerCheck:function(a,b,c){a&&("hi, raonk photo !!!"==a.toLowerCase()||
-1<a.toLowerCase().indexOf("hi, raonk photo !!!"))?-1<a.indexOf("-")&&(RAONKPHOTO.ServerReleaseVer=a.split("-")[1]):(a&&0<a.length||(a="",c=0<c.InitXml.length?c.InitXml:"raonkphoto.config.xml","ko-kr"==b.lang?(a="RAONK Photo\uc758 \uc124\uc815\uac12\uc774 \uc62c\ubc14\ub974\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4. \uc544\ub798 URL \uc811\uadfc\uc774 \uc720\ud6a8\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.\n\n"+(b.handlerUrl+"\n\n"),a+=c+" \ud30c\uc77c\uc758 uploader_setting \uc139\uc158\uc758 <develop_langage>\uc640 <handler_url> \uc124\uc815\uac12\uc744 \ud655\uc778\ud558\uc138\uc694."):
(a="RAONK Photo's setting is not correct. Access the following URL is not valid.\n\n"+(b.handlerUrl+"\n\n"),a+='Please check the settings, <handler_url> and <develop_langage> in "uploader_setting" section in the "'+c+'."'),b.handlerUrlCheck=!1),alert(a))},createPhotoIframe:function(a,b,c,d,e,f){var k=document.createElement("iframe");b.appendChild(k);k.id=d;k.title=e;k.frameBorder=0;k.style.width="100%";k.style.height=RAONKPHOTO.browser.quirks?a.height:"100%";k.style.borderWidth="0px";b="document.open();"+
(RAONKPHOTO.browser.isCustomDomain(document)?'document.domain="'+document.domain+'";':"")+" document.close();";b=RAONKPHOTO.browser.ie?"javascript:void(function(){"+encodeURIComponent(b)+"}())":"";k.src=b;b=function(){try{k.contentWindow.raonk_frame_loaded_event(f,a,c);var b=window.document,d=b.getElementsByTagName("head")[0],e=d.getElementsByTagName("link"),g=e.length,h="raonkphoto.min.css",l="css";RAONKPHOTO.isRelease||(h="raonkphoto.css",l="cssDev");for(var r=!1,p=0;p<g;p++)-1<e[p].href.indexOf(h)&&
(r=!0);if(!r){var n=b.createElement("link");n.type="text/css";n.rel="stylesheet";n.href=a.webPath[l]+h+"?ver="+KPHOTOTOP.RAONKPHOTO.ReleaseVer;d.appendChild(n)}}catch(u){alert("Error occurred load Frame")}};k.addEventListener?k.addEventListener("load",b,!1):k.attachEvent&&k.attachEvent("onload",b);b=RAONKPHOTO.util.getIframeDocument(k);d='<!DOCTYPE html><html lang="ko">';d+="<head>";d+='<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">';d+='<meta http-equiv="Content-Style-Type" content="text/css">';
d+="<title>RAONK Photo</title>";e=RAONKPHOTO.ReleaseVer;"1"==a.cacheProtectMode&&(e=(new Date).getTime());for(var g=!1,h=0;h<=a.rightMenu.length;h++)"figure"==a.rightMenu[h]&&(g=!0);if(RAONKPHOTO.isRelease){d+='<link rel="stylesheet" type="text/css" href="'+a.webPath.css+"k_photo.min.css?ver="+e+'" />';RAONKPHOTO.browser.isCustomDomain(document)&&(d+='<script type="text/javascript"> document.domain = "'+document.domain+'"; \x3c/script>');d+='<script type="text/javascript" src="'+a.webPath.lang+a.lang+
".js?ver="+e+'">\x3c/script>';d+='<script type="text/javascript" src="'+a.webPath.js+"raonkphoto.core.js?ver="+e+'">\x3c/script>';d+='<script type="text/javascript" src="'+a.webPath.js+"plugins/raonkcanvas.min.js?ver="+e+'">\x3c/script>';d+='<script type="text/javascript" src="'+a.webPath.js+"plugins/raonkcanvas.save.min.js?ver="+e+'">\x3c/script>';for(var l=a.toolbar.length,h=0;h<l;h++)if("separator"!=a.toolbar[h]&&"save"!=a.toolbar[h]){"open"==a.toolbar[h]?"html5"==a.userRunTimeMode&&(d+='<script type="text/javascript" src="'+
a.webPath.js+"plugins/raonkcanvas."+a.toolbar[h]+".min.js?ver="+e+'">\x3c/script>'):d+='<script type="text/javascript" src="'+a.webPath.js+"plugins/raonkcanvas."+a.toolbar[h]+".min.js?ver="+e+'">\x3c/script>';"filter"==a.toolbar[h]&&(d+='<script type="text/javascript" src="'+a.webPath.js+"plugins/raonkphoto.filtertools.js?ver="+e+'">\x3c/script>');if("tone"==a.toolbar[h]||"text"==a.toolbar[h]||"figure"==a.rightMenu[0]||"emoticon"==a.rightMenu[0]||"addimage"==a.rightMenu[0])d+='<link rel="stylesheet" type="text/css" href="'+
a.webPath.css+"slidertool.min.css?ver="+e+'" />',d+='<script type="text/javascript" src="'+a.webPath.js+"plugins/slidertool.min.js?ver="+e+'">\x3c/script>';("text"==a.toolbar[h]||g)&&0>d.indexOf(a.webPath.js+"jscolor/jscolor.js?ver=")&&(d+='<script type="text/javascript" src="'+a.webPath.js+"jscolor/jscolor.js?ver="+e+'">\x3c/script>')}g=a.rightMenu.length;for(h=0;h<g;h++)d+='<script type="text/javascript" src="'+a.webPath.js+"plugins/raonkcanvas."+a.rightMenu[h]+".min.js?ver="+e+'">\x3c/script>'}else{d+=
'<link rel="stylesheet" type="text/css" href="'+a.webPath.cssDev+"k_photo.css?ver="+e+'" />';RAONKPHOTO.browser.isCustomDomain(document)&&(d+='<script type="text/javascript"> document.domain = "'+document.domain+'"; \x3c/script>');d+='<script type="text/javascript" src="'+a.webPath.langDev+a.lang+".js?ver="+e+'">\x3c/script>';d+='<script type="text/javascript" src="'+a.webPath.jsDev+"raonkphoto.src.js?ver="+e+'">\x3c/script>';d+='<script type="text/javascript" src="'+a.webPath.jsDev+"plugins/fabric.js?ver="+
e+'">\x3c/script>';d+='<script type="text/javascript" src="'+a.webPath.jsDev+"plugins/fabric.extension.js?ver="+e+'">\x3c/script>';d+='<script type="text/javascript" src="'+a.webPath.jsDev+"plugins/raonkcanvas.js?ver="+e+'">\x3c/script>';d+='<script type="text/javascript" src="'+a.webPath.jsDev+"plugins/raonkcanvas.save.js?ver="+e+'">\x3c/script>';l=a.toolbar.length;for(h=0;h<l;h++)if("separator"!=a.toolbar[h]&&"save"!=a.toolbar[h]){"open"==a.toolbar[h]?"html5"==a.userRunTimeMode&&(d+='<script type="text/javascript" src="'+
a.webPath.jsDev+"plugins/raonkcanvas."+a.toolbar[h]+".js?ver="+e+'">\x3c/script>'):d+='<script type="text/javascript" src="'+a.webPath.jsDev+"plugins/raonkcanvas."+a.toolbar[h]+".js?ver="+e+'">\x3c/script>';"filter"==a.toolbar[h]&&(d+='<script type="text/javascript" src="'+a.webPath.jsDev+"plugins/raonkphoto.filtertools.js?ver="+e+'">\x3c/script>');if("tone"==a.toolbar[h]||"text"==a.toolbar[h]||"figure"==a.rightMenu[0]||"emoticon"==a.rightMenu[0]||"addimage"==a.rightMenu[0])d+='<link rel="stylesheet" type="text/css" href="'+
a.webPath.cssDev+"nouislider.css?ver="+e+'" />',d+='<script type="text/javascript" src="'+a.webPath.jsDev+"plugins/nouislider.js?ver="+e+'">\x3c/script>';("text"==a.toolbar[h]||g)&&0>d.indexOf(a.webPath.jsDev+"jscolor/jscolor.js?ver=")&&(d+='<script type="text/javascript" src="'+a.webPath.jsDev+"jscolor/jscolor.js?ver="+e+'">\x3c/script>')}g=a.rightMenu.length;for(h=0;h<g;h++)d+='<script type="text/javascript" src="'+a.webPath.jsDev+"plugins/raonkcanvas."+a.rightMenu[h]+".js?ver="+e+'">\x3c/script>'}d+=
"</head>";d+='<body oncontextmenu="return false">';d+="</body>";d+="</html>";b.open("text/html","replace");b.write(d);b.close();return k},GetUserRunTimePhoto:function(a){a=a.toLowerCase();var b="";""==a||"html5"==a?b=1==RAONKPHOTO.browser.HTML5Supported?"html5":"html4":"html4"==a?b="html4":"ieplugin"==a?b=1==RAONKPHOTO.browser.ie&&12>RAONKPHOTO.browser.ieVersion?"ieplugin":1==RAONKPHOTO.browser.HTML5Supported?"html5":"html4":-1<a.indexOf("ieplugin")&&8<a.length?(a=RAONKPHOTO.util.parseIntOr0(a),b=
1==RAONKPHOTO.browser.ie&&a>=RAONKPHOTO.browser.ieVersion?"ieplugin":1==RAONKPHOTO.browser.HTML5Supported?"html5":"html4"):b=1==RAONKPHOTO.browser.HTML5Supported?"html5":"html4";return b},_setRAONKPhoto:function(a){a=RAONKPHOTO.util._getRAONKPhoto(a);return void 0==a||null==a?!1:a},_getRAONKPhoto:function(a){var b=null,b=RAONKPHOTO.util.getPhotoByName(a);return void 0==b||null==b?null:b},getPhotoByName:function(a){var b=null;void 0==a||""==a?b=KPHOTOTOP.G_CURRKPHOTO:(b=RAONKPHOTO.RAONKMULTIPLE["raonkphoto_frame_"+
a],"object"!=typeof b&&(b=null));return b},hexToRgb:function(a){var b=null;-1<a.indexOf("rgb")?(a=a.replace("rgb(",""),a=a.replace("rgba(",""),a=a.replace(")",""),a=a.split(","),b={r:parseInt(a[0]),g:parseInt(a[1]),b:parseInt(a[2]),a:parseFloat(a[3])}):(a=a.replace(/^#?([a-f\d])([a-f\d])([a-f\d])$/i,function(a,b,e,f){return b+b+e+e+f+f}),b=(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?{r:parseInt(a[1],16),g:parseInt(a[2],16),b:parseInt(a[3],16)}:null);return b},rgbToHex:function(){var a,
b,c;1==arguments.length?(a=arguments[0],a=a.replace("rgb(",""),a=a.replace("rgba(",""),a=a.replace(")",""),c=a.split(","),a=parseInt(c[0],10),b=parseInt(c[1],10),c=parseInt(c[2],10)):3<=arguments.length&&(a=arguments[0],b=arguments[1],c=arguments[2]);return"#"+(16777216+(a<<16)+(b<<8)+c).toString(16).slice(1)},parseDataFromServer:function(a){var b=a.toLowerCase().indexOf("<raonk>");-1<b&&(a=a.substring(b+7));b=a.toLowerCase().indexOf("</raonk>");-1<b&&(a=a.substring(0,b));return a},makeDecryptReponseMessage:function(a){var b=
function(a,b){var e=a.split("");e.splice(b,1);return e=e.join("")};a=a.replace(/ /g,"");a=a.replace(/\r/g,"");a=a.replace(/\n/g,"");a=a.replace(/%2B/g,"+");a=b(a,9);a=b(a,6);a=b(a,8);a=b(a,7);a=b(a,9);a=b(a,6);a=b(a,8);return a=RAONKPHOTO.util.base64_decode(a)},parseDataFromServer:function(a){var b=a.toLowerCase().indexOf("<raonk>");-1<b&&(a=a.substring(b+7));b=a.toLowerCase().indexOf("</raonk>");-1<b&&(a=a.substring(0,b));return a},getCodeAndMessage:function(a){var b={code:"",message:""};a=a.split("|");
0==a.length?b.message=a[0]:(b.code=a[0],b.message=a[1]);return b}});window.RAONKSolution||(window.RAONKSolution={Agent:{vertical:"\x0B",formfeed:"\f",backspace:"\b",space:" ",rtnCode1:"2000",parseRtn:function(a){var b={code:0,valueArr:[],splitCode:""};a=a.trim?a.trim():a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"");0==a.indexOf("7777")&&5==a.toLowerCase().indexOf("<pre")&&(a=a.replace(/ <pre/i,RAONKSolution.Agent.vertical+"<pre"),a=a.replace(RAONKSolution.Agent.vertical+"<pre>",RAONKSolution.Agent.vertical),
a=a.replace(/<\/pre>$/i,""));var c;-1<a.indexOf(RAONKSolution.Agent.vertical)?(c=a.split(RAONKSolution.Agent.vertical),b.splitCode=RAONKSolution.Agent.vertical):(c=a.split(RAONKSolution.Agent.space),b.splitCode=RAONKSolution.Agent.space);b.code=parseInt(c[0],10);if(7777==b.code){a=c.length;for(var d=1;d<a;d++)b.valueArr[d-1]=c[d]}else c[1]?(c=RAONKSolution.Agent.decryptManagerParam(c[1]),b.valueArr=c.split(RAONKSolution.Agent.vertical),""==b.valueArr[b.valueArr.length-1]&&b.valueArr.splice(b.valueArr.length-
1,1)):isNaN(b.code)&&(b.valueArr[0]=a);return b},parseRtnInWorker:function(a,b){var c="",c=RAONKUPLOAD.ReleaseVer;"1"==KUPLOADTOP.G_CURRKUPLOADER._config.cacheProtectMode&&(c=RAONKUPLOAD.util.getTimeStamp());var c=RAONKUPLOAD.isRelease?KUPLOADTOP.G_CURRKUPLOADER._config.webPath.js+"raonkupload.processmanagerparam.min.js?ver="+c:KUPLOADTOP.G_CURRKUPLOADER._config.webPath.jsDev+"raonkupload.processmanagerparam.js?ver="+c,d=new Worker(c),e={code:0,valueArr:[]};d.onmessage=function(a){a=a.data;switch(a.type){case "decrypt":e=
a.agentMsg,d.terminate()}"undefined"!=typeof b&&b(e)};d.onerror=function(a){d.terminate();"undefined"!=typeof b&&(e.valueArr[0]="Agent Param Process Worker Error",b(e))};d.postMessage({type:"decrypt",agentMsg:a,agentVar:{vertical:"\x0B",formfeed:"\f",backspace:"\b",space:" "}})},isLoaded:!1,isUpdating:!1,isStartInstall:!1,isOtherUploadWaiting:!1,G_AP:{G_AP29:"w",G_AP22:"a"},makeEncryptManagerParam:function(a){var b=null;try{RAONKEDITOR&&RAONKEDITOR.util&&(b=RAONKEDITOR.util.base64_encode)}catch(c){}try{null==
b&&RAONKUPLOAD&&RAONKUPLOAD.util&&(b=RAONKUPLOAD.util.base64_encode)}catch(d){}try{null==b&&RAONKPHOTO&&RAONKPHOTO.util&&(b=RAONKPHOTO.util.base64_encode)}catch(e){}a="R"+b(a);a=b(a);a=a.replace(/[+]/g,"%2B");return a+="\x0B"},decryptManagerParam:function(a){var b=null;try{RAONKEDITOR&&RAONKEDITOR.util&&(b=RAONKEDITOR.util.base64_decode)}catch(c){}try{null==b&&RAONKUPLOAD&&RAONKUPLOAD.util&&(b=RAONKUPLOAD.util.base64_decode)}catch(d){}try{null==b&&RAONKPHOTO&&RAONKPHOTO.util&&(b=RAONKPHOTO.util.base64_decode)}catch(e){}a=
a.replace(/%2B/g,"+");a=b(a);a=a.substring(1);return a=b(a)},G_AP10:8,G_AP23:"n",G_AP20:"z",isCheckingPort:!1,connectedPort:"",sendCount:0,managerFinalUrl:"",reset:function(){this.isCheckingPort=this.isOtherUploadWaiting=this.isStartInstall=this.isUpdating=this.isLoaded=!1;this.connectedPort="";this.sendCount=0;this.managerFinalUrl=""}}});RAONKPHOTO.OpenFileDialog=function(a){try{var b=RAONKPHOTO.util._setRAONKPhoto(a);if(b){KPHOTOTOP.G_CURRKPHOTO=b;var c=KPHOTOTOP.G_CURRKPHOTO.frameWin;c&&"html5"==
b._config.userRunTimeMode&&c.document.getElementById("photo_image").click()}}catch(d){}};RAONKPHOTO.LoadImgFromUrl=function(a,b){try{var c=RAONKPHOTO.util._setRAONKPhoto(b);if(c){KPHOTOTOP.G_CURRKPHOTO=c;var d=KPHOTOTOP.G_CURRKPHOTO.frameWin;if(d){d.displayLoadingDiv(!0);c="";"object"==typeof a?(c=a.url,""!=a.width&&(KPHOTOTOP.G_CURRKPHOTO.originWidth=a.width),""!=a.height&&(KPHOTOTOP.G_CURRKPHOTO.originHeight=a.height)):c=a;var e="";if(a.fileName&&""!=a.fileName)e=a.fileName;else{var f=c.split("/"),
e=f[f.length-1];-1<e.indexOf("?")&&(e=e.substring(0,e.indexOf("?")))}KPHOTOTOP.G_CURRKPHOTO.currFileName=e;KPHOTOTOP.G_CURRKPHOTO.currUrl=c;d.loadNewImg(c)}}}catch(k){}};RAONKPHOTO.LoadImgFromElem=function(a,b){try{var c=RAONKPHOTO.util._setRAONKPhoto(b);if(c){KPHOTOTOP.G_CURRKPHOTO=c;var d=KPHOTOTOP.G_CURRKPHOTO.frameWin;d&&(d.displayLoadingDiv(!0),KPHOTOTOP.G_CURRKPHOTO.currFileName="",d.loadNewImg(a.src))}}catch(e){}};RAONKPHOTO.LoadImgFromFileObj=function(a,b){try{var c=RAONKPHOTO.util._setRAONKPhoto(b);
if(c){KPHOTOTOP.G_CURRKPHOTO=c;var d=KPHOTOTOP.G_CURRKPHOTO.frameWin;if(d){d.displayLoadingDiv(!0);try{KPHOTOTOP.G_CURRKPHOTO.currFileName=a.name;var e=(window.URL||window.webkitURL||window).createObjectURL(a);d.loadNewImg(e)}catch(f){}}}}catch(k){}};RAONKPHOTO.ShowPopup=function(a){try{var b=RAONKPHOTO.util._setRAONKPhoto(a);if(b){KPHOTOTOP.G_CURRKPHOTO=b;var c=KPHOTOTOP.G_CURRKPHOTO.frameWin;c&&c.showPhotoPopup()}}catch(d){}};RAONKPHOTO.ClosePopup=function(a){try{var b=RAONKPHOTO.util._setRAONKPhoto(a);
if(b){KPHOTOTOP.G_CURRKPHOTO=b;var c=KPHOTOTOP.G_CURRKPHOTO.frameWin;c&&c.closePhotoPopup()}}catch(d){}};RAONKPHOTO.Reset=function(a){try{var b=RAONKPHOTO.util._setRAONKPhoto(a);if(b){KPHOTOTOP.G_CURRKPHOTO=b;var c=KPHOTOTOP.G_CURRKPHOTO.frameWin;c&&c.resetPhoto()}}catch(d){}};RAONKPHOTO.Show=function(a){try{var b=RAONKPHOTO.util._setRAONKPhoto(a);if(b){KPHOTOTOP.G_CURRKPHOTO=b;var c=KPHOTOTOP.G_CURRKPHOTO.frameWin;c&&c.photoShow()}}catch(d){}};RAONKPHOTO.Hidden=function(a){try{var b=RAONKPHOTO.util._setRAONKPhoto(a);
if(b){KPHOTOTOP.G_CURRKPHOTO=b;var c=KPHOTOTOP.G_CURRKPHOTO.frameWin;c&&c.photoHidden()}}catch(d){}};RAONKPHOTO.SetRAONKEditorID=RAONKPHOTO.setRAONKEditorID=function(a,b){try{var c=RAONKPHOTO.util._setRAONKPhoto(b);c&&(KPHOTOTOP.G_CURRKPHOTO=c,KPHOTOTOP.G_CURRKPHOTO.frameWin&&(KPHOTOTOP.G_CURRKPHOTO.raonkEditorId=a))}catch(d){}};RAONKPHOTO.SetRAONKEditorID=RAONKPHOTO.setRAONKEditorID=function(a,b,c){try{var d=RAONKPHOTO.util._setRAONKPhoto(c);d&&(KPHOTOTOP.G_CURRKPHOTO=d,KPHOTOTOP.G_CURRKPHOTO.frameWin&&
(KPHOTOTOP.G_CURRKPHOTO.raonkEditorId=a,b&&(KPHOTOTOP.G_CURRKPHOTO.raonkEditorIsInsert=!0)))}catch(e){}};RAONKPHOTO.Save=RAONKPHOTO.save=function(a){try{var b=RAONKPHOTO.util._setRAONKPhoto(a);if(b){KPHOTOTOP.G_CURRKPHOTO=b;var c=KPHOTOTOP.G_CURRKPHOTO.frameWin;c&&c.document.getElementById("btn_save").click()}}catch(d){}};RAONKPHOTO.SetConfig=function(a,b,c){try{var d=RAONKPHOTO.util._setRAONKPhoto(c);if(d&&(KPHOTOTOP.G_CURRKPHOTO=d,KPHOTOTOP.G_CURRKPHOTO.frameWin)){var e=a.substring(0,1).toLowerCase()+
a.substring(1);switch(e){case "handlerUrl":d._config[e]=RAONKPHOTO.util.set_handlerUrl(b);break;case "folderNameRule":_uploader._config[e]=b;break;case "fileNameRule":_uploader._config[e]=b}}}catch(f){}}}
function user_config(){return{InitXml:"",InitServerXml:"",IgnoreSameUploadName:"",SaveMethod:"",DevelopLangage:"",HandlerUrl:"",FolderNameRule:"",FileNameRule:"",DuplicationCharacter:"",Lang:"",ToolBarUse:"",ToolBar:"",RightMenu:"",AddImageXmlUrl:"",EmoticonXmlUrl:"",SelectTool:"",StatusBarUse:"",ResizeSelectMenu:"",ResizeSelectMenuUse:"",Width:"",Height:"",SkinName:"",Filter:"",PhotoHolder:"",PhotoButtonHolder:"",Visibility:"",UploadOverwrite:"",ProductKey:"",LicenseKey:"",LicenseKeyEx:"",LicenseKeyHtml5:"",
ServerDomain:"",CreationCompleteEvent:"",SaveCompleteEvent:"",LicenseKeySE:"",DefaultZIndex:"",CanvasDefaultImageType:"",CanvasDefaultImageQuality:"",SizeInDecreaseUnit:"",SizeInDecreaseMin:"",SizeInDecreaseMax:"",Title:"",FullscreenType:"",PopupBackgroundStyle:"",TextFontFamily:"",TextDefaultFontFamily:"",TextFontSize:"",TextDefaultFontSize:"",FigureWidth:"",FigureHeight:"",FigureAngle:"",FigureBackColor:"",FigureBackOpacity:"",FigureBorderColor:"",FigureBorderWidth:"",FigureBorderOpacity:"",LineLength:"",
LineThickness:"",LineColor:"",LineAngle:"",LineOpacity:"",GetText:"",TextColor:"",TextBackgroundWidth:"",TextBackgroundHeight:"",TextBackgroundColor:"",TextBackgroundOpacity:"",TextBackgroundBorderColor:"",TextBackgroundBorderWidth:"",TextBackgroundBorderOpacity:"",MosaicPixel:""}}
function RAONKPhoto_Config(){this.licenseKey=this.productKey="";this.licenseKeySE="0";this.licenseKeyHtml5=this.licenseKeyEx="";this.webPath={image:RAONKPHOTO.rootPath+"images/",skin:RAONKPHOTO.rootPath+"images/skin/",js:RAONKPHOTO.rootPath+"js/",jsDev:RAONKPHOTO.rootPath+"js_dev/",lang:RAONKPHOTO.rootPath+"js/lang/",langDev:RAONKPHOTO.rootPath+"js_dev/lang/",css:RAONKPHOTO.rootPath+"css/",cssDev:RAONKPHOTO.rootPath+"css_dev/",config:RAONKPHOTO.rootPath+"config/"};this.configUrl=this.webPath.config+
"raonkphoto.config.xml";this.lang="ko-kr";this.skinName="blue";this.width="800px";this.height="580px";this.userRunTimeMode="html5";this.headerHeight=50;this.statusHeight=31;this.toolbarUse="1";this.toolbar="open separator history separator rotate separator crop separator flip separator resize tone filter separator save".split(" ");this.rightMenu=["figure","emoticon","addimage"];this.addImageXmlUrl=this.webPath.config+"raonkphoto.userimage.xml";this.emoticonXmlUrl=this.webPath.config+"raonkphoto.emoticon.xml";
this.selectTool=["crop","mosaic"];this.resizeSelectMenu=[];this.statusbarUse=this.resizeSelectMenuUse="1";this.filter=["vintage","blur","grayscale","sepia"];this.saveMethod="";this.developLang="NET";this.fileNameRule=this.folderNameRule=this.handlerUrl="";this.duplicationCharacter="_";this.isCrossDomain=!1;this.targetImgId="raonkphoto_target";this.photoButtonHolder="";this.visibility="show";this.uploadOverwrite="0";this.id=this.saveCompleteEvent=this.creationCompleteEvent=this.serverDomain="";this.defaultZIndex=
1E3;this.canvasDefaultImageType="jpeg";this.canvasDefaultImageQuality=1;this.sizeInDecreaseUnit="10%";this.sizeInDecreaseMax=this.sizeInDecreaseMin=0;this.title="RAONK Photo";this.fullscreenType="0";this.popupBackgroundStyle="filter:alpha(opacity=50); opacity:0.5; -moz-opacity:0.5; -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=50); -khtml-opacity: 0.5; background-color:black;";this.textFontFamily=[];this.textDefaultFontFamily="\ub9d1\uc740 \uace0\ub515";this.textFontSize=[];this.textDefaultFontSize=
14;this.figureHeight=this.figureWidth=50;this.figureAngle=0;this.figureBackColor="#5B9BD5";this.figureBackOpacity=100;this.figureBorderColor="#000000";this.figureBorderWidth=1;this.lineLength=this.figureBorderOpacity=100;this.lineThickness=1;this.lineColor="#000000";this.lineAngle=0;this.lineOpacity=100;this.getText="0";this.textColor="#000000";this.textBackHeight=this.textBackWidth="";this.textBackColor="#FFFFFF";this.textBackOpacity=100;this.textBackBorderColor="#000000";this.textBackBorderWidth=
0;this.textBackBorderOpacity=100;this.mosaicPixel=7;this.logoUrl1=this.webPath.image+"logo.png";this.logoUrl2=this.webPath.image+"v_logo.png"}
function RAONKPhoto(a){var b=a.Id,c=new user_config,d;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);void 0==b&&(b=RAONKPHOTO.util.makeGuidTagName("raonkphoto_"));a=RAONKPHOTO.util.isExistPhotoName(b,c.PhotoHolder);if(1==a)alert("photo's name is empty. Please, check photo's name");else{if(2==a)if("1"==c.IgnoreSameUploadName)b=getNewNextPhotoName(b);else{alert("photo's name is already exist. Please, check photo's name");return}3!=a&&(RAONKPHOTO.RAONKMULTIPLE["raonk_frame_"+b]=b,RAONKPHOTO.RAONKHOLDER[b]=
c.PhotoHolder);RAONKPHOTO.RAONKMULTIPLE["raonkphoto_frame_"+b]=b;this.frameID="raonkphoto_frame_"+b;this.ID=b;a=new RAONKPhoto_Config;if(0<c.InitServerXml.length)if(-1<c.InitServerXml.indexOf("f="))a.configUrl=c.InitServerXml+"&raonkCMD=cr";else{alert("Error occurred reading the Photo Editor Settings");return}else 0<c.InitXml.length&&(0==c.InitXml.indexOf("http")?a.configUrl=c.InitXml:a.configUrl=RAONKPHOTO.rootPath+"config/"+c.InitXml);-1<a.configUrl.indexOf("?")?a.configUrl+="&t="+(new Date).getTime():
a.configUrl+="?t="+(new Date).getTime();var e=null,e=0<c.InitServerXml.length?RAONKPHOTO.ajax.load(a.configUrl):RAONKPHOTO.ajax.loadXml(a.configUrl);if(null==e)alert("Error occurred reading the Photo Settings");else{"object"==typeof e?""==e.xml&&(e=RAONKPHOTO.ajax.load(a.configUrl),e=RAONKPHOTO.util.stringToXML(e)):(e=RAONKPHOTO.util.parseDataFromServer(e),0==e.indexOf("[OK]")?(0==e.indexOf("[OK]")&&(e=e.substring(4),e=RAONKPHOTO.util.makeDecryptReponseMessage(e)),e=e.substring(e.indexOf("<?")),e=
RAONKPHOTO.util.stringToXML(e)):0==e.indexOf("[FAIL]")?alert("Error occurred reading the Photo Settings"):(e=RAONKPHOTO.util.stringToXML(e))||alert("Error occurred reading the Photo Settings"));d=RAONKPHOTO.util.xml.getNode(e,"license");a.productKey=""!=c.ProductKey?c.ProductKey:RAONKPHOTO.util.xml.getNodeValue(d,"product_key");a.licenseKey=""!=c.LicenseKey?c.LicenseKey:RAONKPHOTO.util.xml.getNodeValue(d,"license_key");a.licenseKeyEx=""!=c.LicenseKeyEx?c.LicenseKeyEx:RAONKPHOTO.util.xml.getNodeValue(d,
"license_key_ex");if(""!=c.LicenseKeySE)a.licenseKeySE=c.LicenseKeySE;else{var f=RAONKPHOTO.util.xml.getNode(d,"license_key");f&&f.getAttribute("se")&&"1"==f.getAttribute("se")&&(a.licenseKeySE="1")}a.licenseKeyHtml5=""!=c.LicenseKeyHtml5?c.LicenseKeyHtml5:RAONKPHOTO.util.xml.getNodeValue(d,"license_key_html5");d=RAONKPHOTO.util.xml.getNode(e,"setting");if(""!=c.SaveMethod)a.saveMethod=c.SaveMethod;else{var k=RAONKPHOTO.util.xml.getNode(d,"save");k&&k.getAttribute("method")&&""!=k.getAttribute("method")&&
(a.saveMethod=k.getAttribute("method"))}""!=c.GetText?a.getText=c.GetText:(k=RAONKPHOTO.util.xml.getNode(d,"save"))&&k.getAttribute("get_text")&&""!=k.getAttribute("get_text")&&(a.getText=k.getAttribute("get_text"));k=RAONKPHOTO.util.xml.getNode(k,"upload");""!=c.UploadOverwrite?a.uploadOverwrite=c.UploadOverwrite:k&&k.getAttribute("overwrite")&&(a.uploadOverwrite=k.getAttribute("overwrite"));""!=c.ServerDomain?a.serverDomain=c.ServerDomain:(f=RAONKPHOTO.util.xml.getNodeValue(k,"server_domain"),0<
f.length&&(a.serverDomain=f));""!=c.DevelopLangage?a.developLang=c.DevelopLangage:(f=RAONKPHOTO.util.xml.getNodeValue(k,"develop_langage"),0<f.length&&(a.developLang=f));switch(a.developLang.toUpperCase()){case "JAVA":case "JSP":a.handlerUrl=RAONKPHOTO.rootPath+"handler/raonkhandler.jsp";break;case "PHP":a.handlerUrl=RAONKPHOTO.rootPath+"handler/raonkkhandler.php";break;default:a.handlerUrl=RAONKPHOTO.rootPath+"handler/raonkhandler.ashx"}""!=c.HandlerUrl?a.handlerUrl=c.HandlerUrl:(f=RAONKPHOTO.util.xml.getNodeValue(k,
"handler_url"),0<f.length&&(a.handlerUrl=f));a.handlerUrl=RAONKPHOTO.util.set_handlerUrl(a.handlerUrl);4<a.handlerUrl.length&&"http"==a.handlerUrl.substring(0,4).toLowerCase()&&a.handlerUrl.match(/:\/\/(.[^\/]+)/)[1]!=window.location.host&&(a.isCrossDomain=!0);a.userRunTimeMode=RAONKPHOTO.util.GetUserRunTimePhoto("");""!=c.FolderNameRule?a.folderNameRule=c.FolderNameRule:(f=RAONKPHOTO.util.xml.getNodeValue(k,"foldername_rule"),0<f.length&&(a.folderNameRule=f));var g;if(""!=c.FileNameRule)a.fileNameRule=
c.FileNameRule;else if(g=RAONKPHOTO.util.xml.getNode(k,"filename_rule"))a.fileNameRule=RAONKPHOTO.util.xml.getNodeValue(k,"filename_rule");""!=c.DuplicationCharacter?a.duplicationCharacter=c.DuplicationCharacter:g&&g.getAttribute("duplication_character")&&""!=g.getAttribute("duplication_character")&&(a.duplicationCharacter=g.getAttribute("duplication_character"));""!=c.Lang?a.lang=RAONKPHOTO.util.getUserLang(c.Lang):(g=RAONKPHOTO.util.xml.getNodeValue(d,"lang"),0<g.length&&(a.lang=RAONKPHOTO.util.getUserLang(g)));
var h;""!=c.ToolBarUse?a.toolbarUse=c.ToolBarUse:(h=RAONKPHOTO.util.xml.getNode(d,"toolbar"))&&h.getAttribute("use")&&""!=h.getAttribute("use")&&(a.toolbarUse=h.getAttribute("use"));if(""!=c.ToolBar)c.ToolBar=c.ToolBar.replace(/ /gi,"").toLowerCase(),a.toolbar=c.ToolBar.split(",");else if(h)if(k=RAONKPHOTO.util.xml.count(h,"menu"),0==k)a.toolbarUse="0";else for(a.toolbar=[],g=0;g<k;g++)a.toolbar.push(RAONKPHOTO.util.xml.getNodeValueIdx(h,"menu",g)),"size_in_decrease"==RAONKPHOTO.util.xml.getNodeValueIdx(h,
"menu",g)?(RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("unit")&&(a.sizeInDecreaseUnit=RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("unit")),RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("min")&&(a.sizeInDecreaseMin=RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("min")),RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("max")&&(a.sizeInDecreaseMax=RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("max"))):"fullscreen"==RAONKPHOTO.util.xml.getNodeValueIdx(h,
"menu",g)?RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("type")&&(a.fullscreenType=RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("type")):"select"==RAONKPHOTO.util.xml.getNodeValueIdx(h,"menu",g)?(RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("tool")&&(a.selectTool=RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("tool").split(",")),RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("mosaic_pixel")&&""!=RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("mosaic_pixel")&&
(a.mosaicPixel=RAONKPHOTO.util.parseIntOr0(RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("mosaic_pixel")))):"text"==RAONKPHOTO.util.xml.getNodeValueIdx(h,"menu",g)&&(f=RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g),f.getAttribute("color")&&""!=f.getAttribute("color")&&(a.textColor=f.getAttribute("color")),f.getAttribute("back_width")&&""!=f.getAttribute("back_width")&&(a.textBackWidth=f.getAttribute("back_width")),f.getAttribute("back_height")&&""!=f.getAttribute("back_height")&&(a.textBackHeight=
f.getAttribute("back_height")),f.getAttribute("back_color")&&""!=f.getAttribute("back_color")&&(a.textBackColor=f.getAttribute("back_color")),f.getAttribute("back_opacity")&&""!=f.getAttribute("back_opacity")&&(a.textBackOpacity=f.getAttribute("back_opacity")),f.getAttribute("border_color")&&""!=f.getAttribute("border_color")&&(a.textBackBorderColor=f.getAttribute("border_color")),f.getAttribute("border_width")&&""!=f.getAttribute("border_width")&&(a.textBackBorderWidth=f.getAttribute("border_width")),
f.getAttribute("border_opacity")&&""!=f.getAttribute("border_opacity")&&(a.textBackBorderOpacity=f.getAttribute("border_opacity")));""!=c.TextColor&&(a.textColor=c.TextColor);""!=c.TextBackgroundWidth&&(a.textBackWidth=c.TextBackgroundWidth);""!=c.TextBackgroundHeight&&(a.textBackHeight=c.TextBackgroundHeight);""!=c.TextBackgroundColor&&(a.textBackColor=c.TextBackgroundColor);""!=c.TextBackgroundOpacity&&(a.textBackOpacity=c.TextBackgroundOpacity);""!=c.TextBackgroundBorderColor&&(a.textBackBorderColor=
c.TextBackgroundBorderColor);""!=c.TextBackgroundBorderWidth&&(a.textBackBorderWidth=c.TextBackgroundBorderWidth);""!=c.TextBackgroundBorderOpacity&&(a.textBackBorderOpacity=c.TextBackgroundBorderOpacity);if(""!=c.RightMenu)c.RightMenu=c.RightMenu.replace(/ /gi,"").toLowerCase(),a.rightMenu=c.RightMenu.split(",");else for(h=RAONKPHOTO.util.xml.getNode(d,"right_menu"),k=RAONKPHOTO.util.xml.count(h,"menu"),a.rightMenu=[],g=0;g<k;g++)if(a.rightMenu.push(RAONKPHOTO.util.xml.getNodeValueIdx(h,"menu",g)),
"addimage"==RAONKPHOTO.util.xml.getNodeValueIdx(h,"menu",g))RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("xml_url")&&""!=RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("xml_url")&&(a.addImageXmlUrl=RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("xml_url"));else if("figure"==RAONKPHOTO.util.xml.getNodeValueIdx(h,"menu",g)){if(f=RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g))f.getAttribute("width")&&""!=f.getAttribute("width")&&(a.figureWidth=parseInt(f.getAttribute("width"),
10)),f.getAttribute("height")&&""!=f.getAttribute("height")&&(a.figureHeight=parseInt(f.getAttribute("height"),10)),f.getAttribute("angle")&&""!=f.getAttribute("angle")&&(a.figureAngle=parseInt(f.getAttribute("angle"),10)),f.getAttribute("back_color")&&""!=f.getAttribute("back_color")&&(a.figureBackColor=f.getAttribute("back_color")),f.getAttribute("back_opacity")&&""!=f.getAttribute("back_opacity")&&(a.figureBackOpacity=parseInt(f.getAttribute("back_opacity"),10)),f.getAttribute("border_color")&&
""!=f.getAttribute("border_color")&&(a.figureBorderColor=f.getAttribute("border_color")),f.getAttribute("border_width")&&""!=f.getAttribute("border_width")&&(a.figureBorderWidth=parseInt(f.getAttribute("border_width"),10)),f.getAttribute("border_opacity")&&""!=f.getAttribute("border_opacity")&&(a.figureBorderOpacity=parseInt(f.getAttribute("border_opacity"),10)),f.getAttribute("line_length")&&""!=f.getAttribute("line_length")&&(a.lineLength=parseInt(f.getAttribute("line_length"),10)),f.getAttribute("line_thickness")&&
""!=f.getAttribute("line_thickness")&&(a.lineThickness=parseInt(f.getAttribute("line_thickness"),10)),f.getAttribute("line_color")&&""!=f.getAttribute("line_color")&&(a.lineColor=f.getAttribute("line_color")),f.getAttribute("line_angle")&&""!=f.getAttribute("line_angle")&&(a.lineAngle=parseInt(f.getAttribute("line_angle"),10)),f.getAttribute("line_opacity")&&""!=f.getAttribute("line_opacity")&&(a.lineOpacity=parseInt(f.getAttribute("line_opacity"),10))}else"emoticon"==RAONKPHOTO.util.xml.getNodeValueIdx(h,
"menu",g)&&RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("xml_url")&&""!=RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("xml_url")&&(a.emoticonXmlUrl=RAONKPHOTO.util.xml.getNodeIdx(h,"menu",g).getAttribute("xml_url"));""!=c.AddImageXmlUrl&&(a.addImageXmlUrl=c.AddImageXmlUrl);""!=c.EmoticonXmlUrl&&(a.emoticonXmlUrl=c.EmoticonXmlUrl);0<a.addImageXmlUrl.length&&0!=a.addImageXmlUrl.indexOf("http")&&(a.addImageXmlUrl=RAONKPHOTO.rootPath+"config/"+a.addImageXmlUrl);""!=c.FigureWidth&&
(a.figureWidth=parseInt(c.FigureWidth,10));""!=c.FigureHeight&&(a.figureHeight=parseInt(c.FigureHeight,10));""!=c.FigureAngle&&(a.figureAngle=parseInt(c.FigureAngle,10));""!=c.FigureBackColor&&(a.figureBackColor=c.FigureBackColor);""!=c.FigureBackOpacity&&(a.figureBackOpacity=parseInt(c.FigureBackOpacity,10));""!=c.FigureBorderColor&&(a.figureBorderColor=c.FigureBorderColor);""!=c.FigureBorderWidth&&(a.figureBorderWidth=parseInt(c.FigureBorderWidth,10));""!=c.FigureBorderOpacity&&(a.figureBorderOpacity=
parseInt(c.FigureBorderOpacity,10));""!=c.LineLength&&(a.lineLength=parseInt(c.LineLength,10));""!=c.LineThickness&&(a.lineThickness=parseInt(c.LineThickness,10));""!=c.LineColor&&(a.lineColor=c.LineColor);""!=c.LineAngle&&(a.lineAngle=parseInt(c.LineAngle,10));""!=c.LineOpacity&&(a.lineOpacity=parseInt(c.LineOpacity,10));""!=c.SizeInDecreaseUnit&&(a.sizeInDecreaseUnit=c.SizeInDecreaseUnit);""!=c.SizeInDecreaseMin&&(a.sizeInDecreaseMin=c.SizeInDecreaseMin);""!=c.SizeInDecreaseMax&&(a.sizeInDecreaseMax=
c.SizeInDecreaseMax);""!=c.SelectTool&&(a.selectTool=c.SelectTool.split(","));""!=c.MosaicPixel&&(a.mosaicPixel=RAONKPHOTO.util.parseIntOr0(c.MosaicPixel));""!=c.FullscreenType&&(a.fullscreenType=c.FullscreenType);var l;""!=c.ResizeSelectMenuUse?a.resizeSelectMenuUse=c.ResizeSelectMenuUse:(l=RAONKPHOTO.util.xml.getNode(d,"resize_select_menu"))&&l.getAttribute("use")&&""!=l.getAttribute("use")&&(a.resizeSelectMenuUse=l.getAttribute("use"));if(""!=c.ResizeSelectMenu)c.ResizeSelectMenu=c.ResizeSelectMenu.replace(/ /gi,
"").toLowerCase(),a.resizeSelectMenu=c.ResizeSelectMenu.split(",");else if(l)if(h=RAONKPHOTO.util.xml.count(l,"value"),0==h)a.resizeSelectMenuUse="0";else for(a.resizeSelectMenu=[],g=0;g<h;g++)a.resizeSelectMenu.push(RAONKPHOTO.util.xml.getNodeValueIdx(l,"value",g));""!=c.StatusBarUse?a.statusbarUse=c.StatusBarUse:(l=RAONKPHOTO.util.xml.getNode(d,"statusbar"))&&l.getAttribute("use")&&""!=l.getAttribute("use")&&(a.statusbarUse=l.getAttribute("use"));""!=c.Width?a.width=c.Width:(l=RAONKPHOTO.util.xml.getNode(d,
"size"))&&l.getAttribute("width")&&""!=l.getAttribute("width")&&(a.width=l.getAttribute("width"));""!=c.Height?a.height=c.Height:(l=RAONKPHOTO.util.xml.getNode(d,"size"))&&l.getAttribute("height")&&""!=l.getAttribute("height")&&(a.height=l.getAttribute("height"));""!=c.DefaultZIndex?a.defaultZIndex=RAONKPHOTO.util.parseIntOr0(c.DefaultZIndex):(l=RAONKPHOTO.util.xml.getNodeValue(d,"default_zIndex"),""!=l&&(a.defaultZIndex=RAONKPHOTO.util.parseIntOr0(l)));if(e=RAONKPHOTO.util.xml.getNode(e,"canvas"))if(a.canvasDefaultImageType=
RAONKPHOTO.util.xml.getNodeValue(e,"default_image_type"),e=RAONKPHOTO.util.xml.getNode(e,"default_image_type"))e=parseFloat(e.getAttribute("quality")),isNaN(e)||(a.canvasDefaultImageQuality=e);""!=c.CanvasDefaultImageType&&(a.canvasDefaultImageType=c.CanvasDefaultImageType);""!=c.CanvasDefaultImageQuality&&(a.canvasDefaultImageQuality=parseFloat(c.CanvasDefaultImageQuality));""!=c.SkinName?a.skinName=c.SkinName:(e=RAONKPHOTO.util.xml.getNodeValue(d,"skinname"),""!=e&&(a.skinName=e));""!=c.Visibility?
a.visibility=c.Visibility:(e=RAONKPHOTO.util.xml.getNodeValue(d,"visibility"),""!=e&&(a.visibility=e));""!=c.CreationCompleteEvent&&(a.creationCompleteEvent=c.CreationCompleteEvent);""!=c.SaveCompleteEvent&&(a.saveCompleteEvent=c.SaveCompleteEvent);if(""!=c.Filter)c.Filter=c.Filter.replace(/ /gi,"").toLowerCase(),a.filter=c.Filter.split(",");else if(e=RAONKPHOTO.util.xml.getNode(d,"filter"))if(l=RAONKPHOTO.util.xml.count(e,"item"),0==l)for(e=a.toolbar.length,g=0;g<e;g++){if("filter"==a.toolbar[g]){a.toolbar.splice(g,
1);break}}else for(a.filter=[],g=0;g<l;g++)a.filter.push(RAONKPHOTO.util.xml.getNodeValueIdx(e,"item",g));if(-1<a.toolbar.indexOf("text")){if(""!=c.TextFontFamily)c.TextFontFamily=c.TextFontFamily.replace(/ /gi,"").toLowerCase(),a.textFontFamily=c.TextFontFamily.split(",");else if(e=RAONKPHOTO.util.xml.getNode(d,"text_font_family"))for(l=RAONKPHOTO.util.xml.count(e,"font"),g=0;g<l;g++)a.textFontFamily.push(RAONKPHOTO.util.xml.getNodeValueIdx(e,"font",g)),RAONKPHOTO.util.xml.getNodeIdx(e,"font",g).getAttribute("default")&&
(a.textDefaultFontFamily=RAONKPHOTO.util.xml.getNodeValueIdx(e,"font",g));""!=c.TextDefaultFontFamily&&(a.textDefaultFontFamily=c.TextDefaultFontFamily);if(""!=c.TextFontSize)c.TextFontSize=c.TextFontSize.replace(/ /gi,"").toLowerCase(),a.textFontSize=c.TextFontSize.split(",");else if(e=RAONKPHOTO.util.xml.getNode(d,"text_font_size"))for(l=RAONKPHOTO.util.xml.count(e,"size"),g=0;g<l;g++)a.textFontSize.push(parseInt(RAONKPHOTO.util.xml.getNodeValueIdx(e,"size",g),10)),RAONKPHOTO.util.xml.getNodeIdx(e,
"size",g).getAttribute("default")&&(a.textDefaultFontSize=RAONKPHOTO.util.xml.getNodeValueIdx(e,"size",g));""!=c.TextDefaultFontSize&&(a.textDefaultFontSize=parseInt(c.TextDefaultFontSize,10))}""!=c.Title?a.title="0"==c.Title?"":c.Title:(e=RAONKPHOTO.util.xml.getNodeValue(d,"title"),""!=e&&(a.title="0"==e?"":e));""!=c.PopupBackgroundStyle?a.popupBackgroundStyle=c.PopupBackgroundStyle:(d=RAONKPHOTO.util.xml.getNodeValue(d,"popup_background_style"),""!=d&&(a.popupBackgroundStyle=d));0==RAONKPHOTO.browser.PhotoEditorSupported?
(b="",b=0==a.lang.indexOf("ko")?"RAONK Photo\ub97c \uc9c0\uc6d0\ud558\uc9c0 \uc54a\ub294 \ube0c\ub77c\uc6b0\uc800 \uc785\ub2c8\ub2e4.":"The browser does not support RAONK Photo.",alert(b)):(divHolder='<div id="raonkphoto_holder_'+b+'" style="width:'+a.width+"; height:"+a.height+"; z-index:"+a.defaultZIndex+';">',divHolder+='<div id="raonkphoto_holder_header_'+b+'" class="RAONK_photo_header" style="width:'+a.width+'; height:27px; position:absolute; display:none;">',divHolder+='<h1 style="margin:0; background:url('+
a.logoUrl1+') 10px 5px no-repeat;"></h1>',divHolder+='<a id="raonkphoto_holder_header_close_'+b+'" href="javascript:;" class="close"><img src="'+a.webPath.image+'btn_close.png"/></a>',divHolder+="</div>",divHolder+='<div id="raonkphoto_holder_body_'+b+'" style="width:100%; height:'+a.height+'; background-color:white; position:absolute; top:30px; display:none; filter:alpha(opacity=0); opacity:0; -moz-opacity:0; -ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=0); -khtml-opacity: 0;"></div>',
divHolder+="</div>",""!=c.PhotoHolder?(c=document.getElementById(c.PhotoHolder))?c.innerHTML=divHolder:document.write(divHolder):document.write(divHolder),c=document.getElementById("raonkphoto_holder_"+b),"show"!=a.visibility&&(c.style.display="none"),RAONKPHOTO.util.createPhotoIframe(a,c,this,"raonkphoto_frame_"+b,"",b))}}};
