/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-08-13 01:57:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import java.util.zip.*;
import com.nexacro.xapi.tx.*;
import com.nexacro.xapi.data.*;
import com.nexacro.xapi.data.datatype.*;

public final class RP_005f102338_005fService_005fDefault2_005ftree_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {



//Respond to Client
	private void flushBuffer(GZIPOutputStream gzipOut, StringBuffer buff) {
		try {

			byte[] arrByteRslt = buff.toString().getBytes();
			gzipOut.write(arrByteRslt, 0, arrByteRslt.length);
			gzipOut.flush();
		} catch(Throwable th) {
			System.out.println("flushBuffer() Exception : "+th.getMessage());
		}
	}

	private GZIPOutputStream getGZipOut(BufferedOutputStream bous)  throws IOException {
		GZIPOutputStream gzip = new GZIPOutputStream(bous);
		return gzip;
	}

	public  PrintWriter getZipWriter(HttpServletResponse response) throws IOException{
		short TOBE_COMPRESS_MARK   = (short)0xFFAD;
		
		response.resetBuffer();
       	response.setContentType("application/octet-stream"); 
		
		DataOutputStream ostream = new DataOutputStream(response.getOutputStream());
		ostream.writeShort(TOBE_COMPRESS_MARK);
		
		DeflaterOutputStream compress = new DeflaterOutputStream(ostream);
		return new PrintWriter(compress);
	}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(9);
    _jspx_imports_packages.add("com.nexacro.xapi.tx");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("com.nexacro.xapi.data");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("java.util.zip");
    _jspx_imports_packages.add("com.nexacro.xapi.data.datatype");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	out.clear();       
    String strCharset = "euc-kr";

 	  
    PlatformRequest platformRequest = new PlatformRequest(request.getInputStream(), PlatformType.CONTENT_TYPE_SSV, strCharset);
    platformRequest.receiveData();  
    PlatformData inPD = platformRequest.getData();

    VariableList    inVariableList  = inPD.getVariableList();
    DataSetList     inDataSetList   = inPD.getDataSetList();
  
    String row_cnt 	=  inVariableList.getString("row_cnt");
    String type 	=  inVariableList.getString("type");
    String compress =  inVariableList.getString("compress"); 
      
    if(row_cnt==null || row_cnt.equals(""))
    	row_cnt = "3";
            
    if(type==null || row_cnt.equals(""))
    	type = "XML";
    
    if(compress==null || compress.equals(""))
    	compress = "false";
	
    DataSet ds1 = inDataSetList.get("input1");
	//DataSet ds2 = inDataSetList.get("input2");
	//DataSet ds3 = inDataSetList.get("input3");
	
    PlatformData outPD = platformRequest.getData();
    VariableList    outVariableList  = new VariableList();
    DataSetList     outDataSetList   = new DataSetList();
    GZIPOutputStream gzipOut = null;
   


    DataSet outDataSet = null;
    try {
         outDataSet = new DataSet("dsMasterTemp");

         outDataSet.addColumn("CPRT_DATE", 	DataTypes.DATE, 100);
		outDataSet.addColumn("PV_TIME", 	DataTypes.TIME, 100);
		outDataSet.addColumn("ALL_DATETIME", 	DataTypes.DATE_TIME, 100);

		
		int newRow = outDataSet.newRow();	

		outDataSet.set(newRow, "CPRT_DATE", "20250101");
		outDataSet.set(newRow, "PV_TIME", "112720123");
		outDataSet.set(newRow, "ALL_DATETIME", "20250101112720123");
		
        outDataSetList.add(outDataSet);

        outVariableList.add("ErrorCode", 0);
        outVariableList.add("ErrorMsg",  "SUCCESS");
		 

        outVariableList.add("strOutputData", "※ Output Vairable을 받으려면, 화면의 전역변수로 선언하면 됩니다.");

    } catch(Exception e) {
		//excepttion 처리 시 원하는 에러메시지를 화면에 전송가능
        outVariableList.add("ErrorCode", -1020);
        outVariableList.add("ErrorMsg",  "테스트중");
	
 
    } finally {

        outPD.setDataSetList(outDataSetList);
        outPD.setVariableList(outVariableList); 

        String Contents_type;  

        if(type.equals("SSV"))
        {
        	Contents_type = PlatformType.CONTENT_TYPE_SSV;
        } else if(type.equals("XML")) {
        	Contents_type = PlatformType.CONTENT_TYPE_XML;
        } else if(type.equals("ZLIB")) {  
        	Contents_type = PlatformType.CONTENT_TYPE_BINARY;
        } else {    
			    Contents_type = PlatformType.CONTENT_TYPE_XML;
        }  
        
        if(compress.equals("true"))
        {
        	 response.setHeader("Accept-Encoding", "gzip, deflate");
       	   	 response.setHeader("X-Compression", "gzip");
       	     response.setHeader("Content-Encoding", "gzip");
      	     response.setHeader("Content-Type", "text/xml");	

        	String RS = String.valueOf((char) 0x1e); //rs(record seperator)
    			String US = String.valueOf((char) 0x1f); //us(unit seperator)
    			StringBuffer sb = new StringBuffer();
    			sb.append("SSV:").append("euc-kr").append(RS); //헤더의 처음 4바이트는 "SSV"로 시작(53 53 56)
			
        	VariableList varLstOut = new VariableList();
        	varLstOut.add("ErrorCode", 0);
    		varLstOut.add("ErrorMsg", "Success!!!!"); 
    		if(varLstOut != null) {
    			int size = varLstOut.size();
    			
    			for(int i=0; i<size; i++) {
    				//Type 생략시 STRING 으로 고정
    				Variable var = varLstOut.get(i);
    				sb.append(var.getName()).append("=").append(var.getString()); //각 Variable 은 US 로 구분
    				
    				if(i<size-1) {
    					sb.append(US);
    				}
    			}
    			sb.append(RS); 
    		}
    		
			sb.append("Dataset:").append("output").append(RS);  //데이터셋 생성
			sb.append("_RowType_"+US); 
			
			for(int i=0; i<outDataSet.getColumnCount(); i++) {
				sb.append(outDataSet.getColumn(i).getName());
				sb.append(":String(255)");
				if(i<outDataSet.getColumnCount()-1) {
					sb.append(US);
				}
			}
        	sb.append(RS);
        	
        	for(int totCnt=0; totCnt<outDataSet.getRowCount(); totCnt++) {
				sb.append("N"+US); //"N" is RowType. (N : Normal Record)
				for(int i=0; i<outDataSet.getColumnCount(); i++) {

					sb.append(outDataSet.getString(totCnt, i)); //Row Value
					if(i<outDataSet.getColumnCount()-1) {
						sb.append(US);
					}
				}
				sb.append(RS);   
			}
		
        	
        	gzipOut = getGZipOut(new BufferedOutputStream(response.getOutputStream())); 
        	
        	try{
        		flushBuffer(gzipOut, sb);
        		
	    	}
	    	catch(Exception e) { 
	    	}

       		if(gzipOut != null) {
       			try {
       				gzipOut.close();
       			} catch (IOException e) {
       				e.printStackTrace();
       			}
       		}
  

        } else {
        	HttpPlatformResponse res = new HttpPlatformResponse(response, Contents_type, "UTF-8");
        	res.setData(outPD);
	        res.sendData();     
        } 

    }

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
