/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-01-10 07:03:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.nexacro.java.xapi.data.*;
import com.nexacro.java.xapi.tx.*;
import java.util.*;
import java.sql.*;
import java.io.*;
import java.net.URLDecoder.*;
import java.net.URLEncoder.*;
import org.apache.commons.logging.*;
import java.util.*;
import java.io.*;
import java.util.*;
import java.net.*;

public final class RP_005f101590_005fNXImageList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(12);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.nexacro.java.xapi.tx");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.net.URLEncoder");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.nexacro.java.xapi.data");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("java.net.URLDecoder");
    _jspx_imports_packages.add("org.apache.commons.logging");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/xml; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	// PlatformData ����
	PlatformData o_xpData = new PlatformData();

	int nErrorCode = 0;
	String strErrorMsg = "START";
	String aa = request.getParameter("arg");
//	String args = java.net.URLDecoder.decode(aa,"utf-8");

 
	try
	{
      DataSet RDS = new DataSet("output");
    	RDS.addColumn("img_file", DataTypes.STRING,255);	
    	RDS.addColumn("img_size", DataTypes.INT,255);	
    	RDS.addColumn("img", DataTypes.BLOB,255);	
    	for (int i = 1 ; i <= 3 ; i++ )
    	{
    	  
    
    	  String search;
    		HttpSession ses = request.getSession(true);
    		if(request.getParameter("url") == null)
    			search = "http://172.10.12.45:9090/";
    		else
    			search =request.getParameter("url");
    	
    		InputStream resultInStream = null;
    		
    		int Row = 0;
    	
    		Row = RDS.newRow();
    	
    		try
    		 {
    			//URL url = new URL(search + "date_" + i + ".jpg");
    			URL url = new URL(search + "RP_101590_MiImageView.jpg");
    			//System.out.println("url 1---- " + url);

    			resultInStream = url.openStream();
    			
    			//System.out.println("resultInStream ---- " + resultInStream);
    			
    			byte[] buffer = new byte[4096];
    			int bytes_read;
    			ByteArrayOutputStream ImageData = new ByteArrayOutputStream();
    	
    			while((bytes_read=resultInStream.read(buffer)) != -1)
    			{
    			    ImageData.write(buffer,0,bytes_read);
    			}
    	

    			RDS.set(Row,"img_file", search);
    			RDS.set(Row,"img_size", ImageData.toByteArray().length);
    			RDS.set(Row,"img", ImageData.toByteArray());
    System.out.println("RDS ---- " + RDS.saveXml());
    
    			resultInStream.close();
    	
    			  
    	 	} catch (Exception e) {
    	 	}
    		finally{ 
    			try {  
    				resultInStream.close();  
    			}
    			catch (Exception e) 
    			{
    			}
    		}
    	}
  	// DataSet�� PlatformData�� �߰�
		o_xpData.addDataSet(RDS);

		nErrorCode = 0;
		strErrorMsg = "SUCC";//args;
	} 
	catch (Exception e) {
		nErrorCode = -1;
		strErrorMsg = e.getMessage();
	}

	// VariableList
	VariableList varList = o_xpData.getVariableList();

	// VariableList
	varList.add("ErrorCode", nErrorCode);
	varList.add("ErrorMsg", strErrorMsg);
	varList.add("EncodeMsg", aa);

	// HttpServletResponse
	HttpPlatformResponse pRes = new HttpPlatformResponse(response, PlatformType.CONTENT_TYPE_XML, "euc-kr");
	pRes.setData(o_xpData);

	pRes.sendData();

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
