/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-02-12 05:47:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class RP_005f95505_005ftobe_005fnexacro_005fview_005frun_005ftest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<HTML>\r\n");
      out.write("<HEAD>\r\n");
      out.write("<TITLE></TITLE>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT LANGUAGE=\"javascript\">\r\n");
      out.write("	function fn_onload() {\r\n");
      out.write("		alert(navigator.userAgent);\r\n");
      out.write("		NexacroLauncher.key = \"TESTING1\";\r\n");
      out.write("		NexacroLauncher.bjson = \"http://172.10.12.45:9090/nexacro14/14.0.1.4202/mdi_test/start.json\";\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		NexacroLauncher.splashmessage = \"none\";\r\n");
      out.write("		NexacroLauncher.download();\r\n");
      out.write("\r\n");
      out.write("		NexacroAXCtrl.key = \"TESTING1\";\r\n");
      out.write("		NexacroAXCtrl.bjson = \"http://172.10.12.45:9090/nexacro14/14.0.1.4202/mdi_test/start.json\";	//http://localhost:8080/dbcc/\r\n");
      out.write("		NexacroAXCtrl.initbktext = \"Loading\";\r\n");
      out.write("\r\n");
      out.write("		NexacroAXCtrl.run();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT LANGUAGE=javascript FOR=NexacroAXCtrl EVENT=\"addlog(strMsg)\">\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<SCRIPT LANGUAGE=javascript FOR=NexacroAXCtrl EVENT=\"beforeexit(bCloseFlag, bHandledFlag)\">\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<SCRIPT LANGUAGE=javascript FOR=NexacroAXCtrl EVENT=\"communication(bStart)\">\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<SCRIPT LANGUAGE=javascript FOR=NexacroAXCtrl EVENT=\"error(nError, strErrMsg)\">\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<SCRIPT LANGUAGE=javascript FOR=NexacroAXCtrl EVENT=\"exit()\">\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<SCRIPT LANGUAGE=javascript FOR=NexacroAXCtrl EVENT=\"load(strURL)\">\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT LANGUAGE=javascript FOR=NexacroAXCtrl EVENT=\"loadingglobalvariables(strURL)\">\r\n");
      out.write("\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT LANGUAGE=javascript FOR=NexacroAXCtrl EVENT=\"loadtypedefinition(strURL)\">\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<SCRIPT LANGUAGE=javascript FOR=NexacroAXCtrl EVENT=\"usernotify(nNotifyID, strMsg)\">\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	// TM íì ì¢ë£ ì ê¸°ê°ê³ ìª½ íë©´ì íì ì ì²´ë¤ê¸° ì¤í ì©ë (ë¹ì ìì¢ë£ ì´ì)\r\n");
      out.write("	function fn_abc(uiNm) {\r\n");
      out.write("		\r\n");
      out.write("		NexacroAXCtrl.callscript(\"application.gfn_call('\" + uiNm + \"')\");\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("</style>\r\n");
      out.write("</HEAD>\r\n");
      out.write("<BODY onload=\"fn_onload()\" style=\"border: 0; padding: 0; margin: 0; overflow: hidden;\">\r\n");
      out.write("\r\n");
      out.write("<!--overflow: hidden;-->\r\n");
      out.write("\r\n");
      out.write("<OBJECT ID=\"NexacroLauncher\" CLASSID=\"CLSID:A7969122-0BB8-452A-93C9-72641B76CFB7\" width=\"0\" height=\"0\" style=\"padding:0; margin:0; border:0;\"></OBJECT>\r\n");
      out.write("<OBJECT ID=\"NexacroAXCtrl\" CLASSID=\"CLSID:6DB5422D-536F-4B80-B32C-16BEA0971512\" width=\"100%\" height=\"200%\" style=\"padding:0; margin:0; border:0; \"></OBJECT>\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" id=\"hidNotiMsg\"/> <!--ìë¦¬ìì íëë¬¸ì hiddenì¼ë¡ ê°ì ê°ëë¤.-->\r\n");
      out.write("\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
