/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-11-19 07:03:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.nexacro17.xapi.data.*;
import com.nexacro17.xapi.tx.*;
import java.util.*;
import java.sql.*;
import java.io.*;
import org.apache.commons.logging.*;

public final class RP_005f101044_005ffileDownload_005fservlet_005flist_005fXML_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(9);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("com.nexacro17.xapi.tx");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("org.apache.commons.logging");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.nexacro17.xapi.data");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	String filePath = request.getRealPath("./file") + "/"; //íì¼ì´ ì¡´ì¬íë ì¤ì ê²½ë¡
	String url = request.getRequestURL().substring(0, request.getRequestURL().lastIndexOf("/") - 3) + "nex/file/";

	System.out.println("filePath :" + filePath);
	System.out.println("url :" + url);

	PlatformData resData = new PlatformData();
	VariableList resVarList = resData.getVariableList();
	
	DataSet ds = new DataSet("dsList");
	ds.addColumn("FILE_NAME", DataTypes.STRING, 255);
	ds.addColumn("FILE_URL", DataTypes.STRING, 255);
	ds.addColumn("DEPTH", DataTypes.STRING, 255);
	ds.addColumn("STATUS", DataTypes.STRING, 255);
	int row;

	File rf = new File(filePath); 
	File[] rfiles = rf.listFiles(); //íì¼ì ë¦¬ì¤í¸ë¥¼ ëì

	if(rfiles != null)
	{
		for(int i=0; i<rfiles.length; i++)
		{
			if(rfiles[i].isDirectory())		//histoy í´ë
			{
				row = ds.newRow();
				ds.set(row, "FILE_NAME", rfiles[i].getName());
				ds.set(row, "DEPTH", "0");
				if(!rfiles[i].getName().equals("temp"))
				{
					ds.set(row, "STATUS", "1");
				}
				
				File evf = new File(filePath + rfiles[i].getName());
				File[] evfiles = evf.listFiles();

				for(int j=0; j<evfiles.length; j++)
				{
					if(evfiles[j].isDirectory())		//ê° íê²½ í´ë
					{
						row = ds.newRow();
						ds.set(row, "FILE_NAME", evfiles[j].getName());
						//ds.set(row, "FILE_URL", url + rfiles[i].getName());
						ds.set(row, "DEPTH", "1");
						//ds.set(row, "STATUS", "1");
						
						File subf = new File(filePath + rfiles[i].getName() +"/"+ evfiles[j].getName());
						File[] subfiles = subf.listFiles();

						for(int k=0; k<subfiles.length; k++)
						{
							if(subfiles[k].isDirectory())		//id(ë ì§) í´ë
							{
								row = ds.newRow();
								ds.set(row, "FILE_NAME", subfiles[k].getName());
								//ds.set(row, "FILE_URL", url + rfiles[i].getName() +"/"+ evfiles[j].getName() +"/"+ subfiles[k].getName());
								ds.set(row, "DEPTH", "2");
								
								File sub2f = new File(filePath + rfiles[i].getName() +"/"+ evfiles[j].getName() +"/"+ subfiles[k].getName());								
								File[] sub2files = sub2f.listFiles();
								
								for(int q=0; q<sub2files.length; q++)
								{
									if(sub2files[q].isDirectory())		//service í´ë
									{
										row = ds.newRow();
										ds.set(row, "FILE_NAME", sub2files[q].getName());
										//ds.set(row, "FILE_URL", url + rfiles[i].getName() +"/"+ evfiles[j].getName() +"/"+ subfiles[k].getName() +"/"+ sub2files[q].getName());
										ds.set(row, "DEPTH", "3");							
									}
									
									if(sub2files[q].isFile())		//service íì¼
									{
										row = ds.newRow();
										ds.set(row, "FILE_NAME", sub2files[q].getName());
										ds.set(row, "FILE_URL", url + rfiles[i].getName() +"/"+ evfiles[j].getName() +"/"+ subfiles[k].getName() +"/"+ sub2files[q].getName());
										ds.set(row, "DEPTH", "3");
									}
								}
							}
							
							if(subfiles[k].isFile())		//id(ë ì§) íì¼
							{
								row = ds.newRow();
								ds.set(row, "FILE_NAME", subfiles[k].getName());
								ds.set(row, "FILE_URL", url + rfiles[i].getName() +"/"+ evfiles[j].getName() +"/"+ subfiles[k].getName());
								ds.set(row, "DEPTH", "2");
							}
						}
					}
					
					if(evfiles[j].isFile())		//ê° íê²½ íì¼
					{
						row = ds.newRow();
						ds.set(row, "FILE_NAME", evfiles[j].getName());
						ds.set(row, "FILE_URL", url + rfiles[i].getName() +"/"+ evfiles[j].getName());
						ds.set(row, "DEPTH", "1");
					}
				}
			}
			
			if(rfiles[i].isFile())		//histoy íì¼
			{ 
				row = ds.newRow();
				ds.set(row, "FILE_NAME", rfiles[i].getName());
				ds.set(row, "FILE_URL", url + rfiles[i].getName());
				ds.set(row, "DEPTH", "0");
			}
		}
	}
	else
	{
		System.out.println("rfiles is null");
	}

	resData.addDataSet(ds);
	resVarList.add("ErrorCode", 0);
	resVarList.add("ErrorMsg", "Success" );
		
	HttpPlatformResponse pRes = new HttpPlatformResponse(response, request);
	pRes.setContentType(PlatformType.CONTENT_TYPE_XML);
	pRes.setCharset("UTF-8");
	pRes.setData(resData);
	pRes.sendData();

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
