/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2025-06-25 08:52:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.Enumeration;
import com.tobesoft.platform.*;
import com.tobesoft.platform.data.*;

public final class RP_005f9719_005fTestU_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.tobesoft.platform");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("com.tobesoft.platform.data");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("java.util.Enumeration");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("  \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");


	String default_charset = "euc-kr";
	String outDSnm = "output";
	System.out.println("&&&&&&&&&&&&&&&&&&&&&&&&");
	PlatformRequest  greq = null;
	greq = new PlatformRequest(request, default_charset);

	greq.receiveData();	
	// ZLIB_COMP,LZSS_COMP,XML
	int default_encode_method = PlatformRequest.XML;
	
	VariableList in_vl = greq.getVariableList();
	DatasetList in_dl = greq.getDatasetList();
	
	in_vl = greq.getVariableList();
	
	VariableList out_vl = new VariableList();
	DatasetList  out_dl = new DatasetList();
	
	
	try {

		Dataset test =  in_dl .getDataset("input");
  
 
		Dataset outds1 = new Dataset("output1",default_charset);
 
		outds1.addColumn("column0",ColumnInfo.CY_COLINFO_STRING, 256);
		
		String strNull = null;
		//String str2 = undefined;
		int row = outds1.appendRow();

		outds1.setColumn(row, "column0", "");
		
		row = outds1.appendRow();
		outds1.setColumn(row, "column0", strNull);
		
		row = outds1.appendRow();
		outds1.setColumn(row, "column0", "1");
		row = outds1.appendRow();
		
		Dataset outds2 = new Dataset("output2",default_charset);
		outds2.addColumn("column0",ColumnInfo.CY_COLINFO_STRING, 256);

		//String str2 = undefined;
		int row1 = outds2.appendRow();
		outds2.setColumn(row1, "column0", "1");
		
		row1 = outds2.appendRow();
		outds2.setColumn(row1, "column0", "");
		
		row1 = outds2.appendRow();
		outds2.setColumn(row1, "column0", strNull);
		
		row1 = outds2.appendRow();
		
		System.out.println("-------------------------------");
		
		out_dl.addDataset(outds1);
		out_dl.addDataset(outds2);
		out_vl.addStr("ErrorCode", "0");    // 
		out_vl.addStr("ErrorMsg" , "SUCC2");

	  request.setAttribute("variableList", out_vl);
	  request.setAttribute("datasetList", out_dl);

	  VariableList vl = (VariableList)request.getAttribute("variableList");
	  DatasetList  dl = (DatasetList)request.getAttribute("datasetList");
		
	} catch ( Exception e ) {
		System.out.println(e);
			out_vl.addStr("ErrorCode", "-1");    //
			out_vl.addStr("ErrorMsg" , "FAIL");
	}
	
	new PlatformResponse(response, PlatformRequest.XML).sendData(out_vl, out_dl);;

	//PlatformResponse pRes = new PlatformResponse(response, PlatformRequest.ZLIB_COMP);
	//pRes.sendData(out_vl, out_dl);
	

      out.write('\n');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
