/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2026-01-13 01:31:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.math.RoundingMode;
import java.math.BigDecimal;
import org.apache.commons.logging.*;
import com.nexacro.java.xapi.data.*;
import com.nexacro.java.xapi.tx.*;
import java.util.*;
import java.sql.*;
import java.io.*;

public final class select_005femp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(9);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.nexacro.java.xapi.tx");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("org.apache.commons.logging");
    _jspx_imports_packages.add("com.nexacro.java.xapi.data");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.math.BigDecimal");
    _jspx_imports_classes.add("java.math.RoundingMode");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/xml; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

// PlatformData
PlatformData out_pData = new PlatformData();
String sDept = (request.getParameter("sDept") == null) ? "" : request.getParameter("sDept");
	
int    nErrorCode  = 0;
String strErrorMsg = "START";

try {    
	/******* JDBC Connection *******/
	Connection conn = null;
	Statement  stmt = null;
	ResultSet  rs   = null;
	PreparedStatement pstmt = null;
	
	//try { 		

	    String driverName="com.mysql.jdbc.Driver";
	    String url = "jdbc:mysql://localhost:3306/";
	    String id = "root"; // MySQL ID
	    String pwd ="!kjh2362";     // MYSQL Password	    
	    
	    //try{
	        //[1] JDBC 드라이버 로드
	        //Class.forName(driverName);     
	    //}catch(ClassNotFoundException e){
	        //out.println("Where is your mysql jdbc driver?");
	        //e.printStackTrace();
	    //    return;
	    //}
	    //out.println("mysql jdbc Driver registered!!");
	   
	    //[2]데이타베이스 연결 
	    //conn = DriverManager.getConnection(url,id,pwd);
	    //out.println("DB연결성공!!");
	    
	    //pstmt = conn.prepareStatement("SELECT * FROM `world`.`vpt_rid_info` order by userid");
	    
	    //rs = pstmt.executeQuery();
		
	  
	    
	    
		DataSet ds = new DataSet("out_ds");

		ds.addColumn("RID" 	  ,DataTypes.BIG_DECIMAL  ,(short)10 );
		ds.addColumn("HRID"  ,DataTypes.STRING  ,(short)50 );
		ds.addColumn("STATUS"    ,DataTypes.STRING  ,(short)10 );
		ds.addColumn("FINGERPRINT"     ,DataTypes.STRING  ,(short)10 );
		ds.addColumn("AUTH_TYPE"     ,DataTypes.STRING  ,(short)10 );
		ds.addColumn("USERID"  ,DataTypes.DATE    ,(short)10 );
		ds.addColumn("CURRENT_PUB"    ,DataTypes.STRING  ,(short)10 );
		ds.addColumn("CURRENT_SEED"     ,DataTypes.INT     ,(short)10 );
		ds.addColumn("KEY_CHANGE_DATE"       ,DataTypes.STRING  ,(short)10 );
			
		//while(rs.next())
		//{
			
			int row = ds.newRow();
			
			
			ds.set(row ,"RID"       , "0.0000005");
			ds.set(row ,"HRID"     ,"111");
			ds.set(row ,"STATUS"       ,"2");
			ds.set(row ,"FINGERPRINT"        ,"111");
			ds.set(row ,"AUTH_TYPE"        ,"Y");
			ds.set(row ,"USERID"     ,"111");
			ds.set(row ,"CURRENT_PUB"       ,"111");
			ds.set(row ,"CURRENT_SEED"        ,"111");
			ds.set(row ,"KEY_CHANGE_DATE"          ,"111");
			//ds.set(row ,"RID"       ,rs.getString("RID")  );
			//ds.set(row ,"HRID"     ,rs.getString("HRID"));
			//ds.set(row ,"STATUS"       ,rs.getString("STATUS")  );
			//ds.set(row ,"FINGERPRINT"        ,rs.getString("FINGERPRINT")   );
			//ds.set(row ,"AUTH_TYPE"        ,rs.getString("AUTH_TYPE")   );
			//ds.set(row ,"USERID"     ,rs.getString("USERID"));
			//ds.set(row ,"CURRENT_PUB"       ,rs.getString("CURRENT_PUB")  );
			//ds.set(row ,"CURRENT_SEED"        ,rs.getString("CURRENT_SEED")   );
			//ds.set(row ,"KEY_CHANGE_DATE"          ,rs.getString("KEY_CHANGE_DATE")     );
		//}
		  
		// #1 dataset -> PlatformData
		out_pData.addDataSet(ds);

		// #2 dataset -> PlatformData
		//DataSetList dsList = out_pData.getDataSetList();
		//dsList.add(ds);

		nErrorCode  = 0;
		strErrorMsg = "SUCC";
		//conn.close(); //대체로 finally 블록에 시스템 자원을 반납하는 Code를 넣는다.
	//} catch (SQLException e) {
	//	nErrorCode = -1;
	//	strErrorMsg = e.getMessage();
	//}    
	
	/******** JDBC Close ********/
	//if ( stmt != null ) try { stmt.close(); } catch (Exception e) {nErrorCode = -1; strErrorMsg = e.getMessage();}
	//if ( conn != null ) try { conn.close(); } catch (Exception e) {nErrorCode = -1; strErrorMsg = e.getMessage();}
			
	} catch (Throwable th) {
		nErrorCode = -1;
		strErrorMsg = th.getMessage();
}




VariableList varList = out_pData.getVariableList();
varList.add("ErrorCode", nErrorCode);
varList.add("ErrorMsg" , strErrorMsg);


/*
Variable varErrCD = new Variable("ErrorCode");
varErrCD.set(nErrorCode);

Variable varErrMSG = new Variable("ErrorMsg");
varErrMSG.set(strErrorMsg);

out_pData.addVariable(varErrCD);
out_pData.addVariable(varErrMSG);
*/
Thread.sleep(3000);

HttpPlatformResponse pRes = new HttpPlatformResponse(response, PlatformType.CONTENT_TYPE_XML, "utf-8");
pRes.setData(out_pData);

// Send data
pRes.sendData();

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
